### ISSUE TITLE
Investigate what's wrong with #freenode_#krita:matrix.org

### ISSUE THREAD

**Issue by Twi1ightSparkle** [matrix-org/synapse#10187]
!MGPzswjKaKwEyQHnpl:matrix.org
#freenode_#krita:matrix.org
#krita:kde.org

Trying to promote someone in this room. But get errors

`/_synapse/admin/v1/rooms/<room_id_or_alias>/make_room_admin` returns
`{"errcode":"M_UNKNOWN","error":"No local admin user in room with power to update power levels."}`

`/_matrix/client/r0/join/{{roomId}}`
```html
<html>

<body>
	<h1>429 Too Many Requests</h1>
	No server is available to handle this request.
</body>

</html>
```

The room is a v1 room created by @appservice-irc:matrix.org

My contact is in the room and say it shows the IRC bot as a room member, but when calling `/_matrix/client/r0/rooms/{{roomId}}/state/m.room.power_levels`:
```json
{
    "errcode": "M_FORBIDDEN",
    "error": "User @appservice-irc:matrix.org not in room !MGPzswjKaKwEyQHnpl:matrix.org, and room previews are disabled"
}
```

Contact got an error when trying to invite @support:matrix.org and the IRC bot.

When they invited me, I got the invite, but am unable to join the room. The invite is persisting.
The room does however show me as joined
```json
{
  "content": {
    "avatar_url": "mxc://twilightsparkle.dev/TkIuQGnsGzKAJGYPeXukNZkn",
    "displayname": "twilight",
    "membership": "join"
  },
  "event_id": "$162384152139WFPqo:twilightsparkle.dev",
  "origin_server_ts": 1623841521819,
  "sender": "@twilight:twilightsparkle.dev",
  "state_key": "@twilight:twilightsparkle.dev",
  "type": "m.room.member",
  "unsigned": {
    "age": 44,
    "replaces_state": "$162384150640309pQCBi:kde.org",
    "prev_content": {
      "avatar_url": "mxc://twilightsparkle.dev/TkIuQGnsGzKAJGYPeXukNZkn",
      "displayname": "twilight",
      "membership": "invite"
    },
    "prev_sender": "@someone:domain.com"
  },
  "room_id": "!MGPzswjKaKwEyQHnpl:matrix.org"
}
```

**Comment by Twi1ightSparkle** [comment]
Also, this spinner thing has been in my Element for hours. Even over clear cache and reload
![Screen Shot 2021-06-16 at 07 25 07 PM](https://user-images.githubusercontent.com/19155609/122272815-addafd80-ced8-11eb-92f5-44e34dd98075.png)

**Comment by tusooa** [comment]
I'm not sure whether that belongs here... 
(1) I'm pretty sure the krita team has moved on to `#krita:libera.chat`, so maybe you want to look into that.

(2) `/_synapse/admin/v1/rooms/<room_id_or_alias>/make_room_admin`
I checked the room, there is indeed no room admins at twilightsparkle.dev in that room, so I think this is legit.

(3) `/_matrix/client/r0/join/{{roomId}}`
Again, I have no problem joining the room (@tusooa.xyz). It is quite a big room, and your homeserver may take a lot of time to fetch room data, so you timed out. This happens when a homeserver first joins a room. Check or ask your homeserver admin to check your homeserver logs.

(4) `/_matrix/client/r0/rooms/{{roomId}}/state/m.room.power_levels`
I think it's the same problem as (3).
(5) 
>When they invited me, I got the invite, but am unable to join the room. The invite is persisting.
>The room does however show me as joined

No idea so I will leave it unexplained.

**Comment by Twi1ightSparkle** [comment]
@tusooa

2. This was done using a matrix.org admin account
3/4. This was attempted using the account @support:matrix.org

**Comment by babolivier** [comment]
It looks like the view of the room from the matrix.org homeserver is hugely different from the one of kde.org. According to the matrix.org database the only users in that room are a couple of users from `fairydust.space` and a bot from `nordgedanken.dev` - that's according to the `local_current_membership` and `current_state_events` tables. The `room_memberships` table seems unaffected by whatever confused the two other tables, according to

```sql
select stream_ordering, event_id, user_id, membership from room_memberships inner join events using (event_id) where events.room_id = '!MGPzswjKaKwEyQHnpl:matrix.org' and user_id like '%:matrix.org' order by stream_ordering;
```

I'll poke the EMS people to investigate the kde.org database, and will try to have a look at what went down in that room before it went boom on the matrix.org HS tomorrow.

**Comment by babolivier** [comment]
I've only had time for a quick look at the kde.org database, and it indeed looks like it still sees the room as one with many members, including loads of freenode users through the matrix.org bridge.

@Twi1ightSparkle I wonder what happens if you add `?server_name=kde.org` to your join request from matrix.org (i.e. `/_matrix/client/r0/join/!MGPzswjKaKwEyQHnpl:matrix.org?server_name=kde.org`). I've got no idea if this will work, but maybe this will force it to synchronise its view of the room.

**Comment by erikjohnston** [comment]
> The room_memberships table seems unaffected by whatever confused the two other tables

Worth noting that `room_memberships` is a table with all room memberships that have ever happened, rather than the *current* memberships.

It sounds like matrix.org thinks its not in the room, it's possible/probable that a type of state reset happened and users on other servers erroneously see matrix.org user as joined until they resync their account?

**Comment by erikjohnston** [comment]
kde.org does still think that matrix.org is in the room though.
