### ISSUE TITLE
An invited user didn't received the invitation

### ISSUE THREAD

**Issue by jlemangarin** [matrix-org/synapse#10277]
### Description
After inviting a user in a room, the user doesn't see the invitation even after refreshing the Element cache from the settings.

From my point of view the user has been invited : 
![element_jle](https://user-images.githubusercontent.com/22454938/123933520-c0523e00-d992-11eb-88ad-998fbdb32773.PNG)

From the user's point of view, no invitation or reference to the room : 
![element_cde](https://user-images.githubusercontent.com/22454938/123933576-cd6f2d00-d992-11eb-991c-b040e3b0bad1.png)

After a while (10-15 min), the user finally received the invitation without any actions.

### Steps to reproduce

- Invite a user in a room

This is a rare issue, first time it happens for us.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information
<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: Private company homeserver not connected to any other external homeserver

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:1.12.4

- **Install method**: pip
<!-- examples: package manager/git clone/pip  -->

- **Platform**: CentOS 7 VM
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by babolivier** [comment]
Hey there, and thanks for filing this issue!

I notice your homeserver is running v1.12.4, which is over a year old. Development around Synapse is fairly active, with a biweekly release cadence, so there's a high probability this bug has been fixed in the 25+ versions that have been released since. I'd recommend updating to a recent version of Synapse and see if this bug happens again.

I appreciate that such a release cadence isn't very practical for companies, and something a LTS version would help a long way here; however we're not at a point where we feel comfortable shipping one.

I'll close this issue for now, but feel free to open a new one if the issue comes back with a recent version.
