### ISSUE TITLE
It is currently not possible to make phone calls

### ISSUE THREAD

**Issue by Florian-Sabonchi** [matrix-org/synapse#10652]
https://github.com/vector-im/element-web/issues/16395

Hi I unfortunately have the problem that it is not possible to make peer to peer calls. 
I followed this tutorial, others who followed this tutorial also have problems, but I am not sure if it is a bug in the configuration or if it is a bug of Matrix, because this tutorial seems correct to me.

https://adminguide.pages.dev/services/communication/matrix/?h=matrix

**Comment by babolivier** [comment]
Calls in Matrix are entirely client-side, so this is a client issue.

**Comment by richvdh** [comment]
> Calls in Matrix are entirely client-side,

well that's kinda true, but they also require a working TURN server, which is server-side. @Florian-Sabonchi: ensure you've read https://matrix-org.github.io/synapse/develop/turn-howto.html.

However, this is almost certainly a configuration problem rather than a Synapse bug, so this bug-tracker is not the place to get support. `#synapse:matrix.org` is the place to get support in configuring your system.

**Comment by Florian-Sabonchi** [comment]
Hello thanks for your message, I think it is simply a configuration problem.
