### ISSUE TITLE
Sometimes the image gets 404 in Element, even though blurhash is returned properly

### ISSUE THREAD

**Issue by Palid** [matrix-org/synapse#10751]
### Description
In some cases you can get a media(image) message that after it gets decrypted returns 404 for the image.
Element web warning: `Failed to load resource: the server responded with a status of 404 ()`
Example of the behavior (we're not handling errors, so this one's on us though).

<img width="1354" alt="CleanShot 2021-09-03 at 15 02 21@2x" src="https://user-images.githubusercontent.com/3636685/132010532-404e3cf0-0464-47f0-b9c8-bdb90a660c91.png">

### Steps to reproduce
Hard to reproduce, seems that it sometimes appears when there's a lot of people in the room. It just got 404 instead of the proper URL for the image, so I'd assume that there's some small IO race condition on file uploads and sending a message.
We already have an issue for that in element-web (we can kinda handle it by properly handling errors on image load, but that's only 50% of the solution): https://github.com/vector-im/element-web/issues/18819

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

I expected the image to load properly (blurhash disappear) and not 404 on the backend side.

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: matrix.org
- **Version**: {"server_version":"1.41.1 (b=matrix-org-hotfixes,ca2e5b206)","python_version":"3.7.3"}

**Comment by babolivier** [comment]
Blurhashes are 100% client-side, so if the upload of the image didn't work out but the event was sent anyway it's possible the blurhash shows but the image doesn't exist on the server.
As far as I can tell Synapse will reply with a 404 if it can't find the file (or the remote server responded with a 404 if the media is remote), or if the media has been quarantined.
As things stand, I don't think there's anything we can do without Synapse logs for the file's upload and attempt to download - I've tried looking at the rageshake associated with the Element web bug but couldn't find a media ID to look up in the matrix.org database (though that might be because of my lack of fluency in Element's logging).
