### ISSUE TITLE
Key lookup failed from 'matrix.org': Not retrying server matrix.org.

### ISSUE THREAD

**Issue by davehayes** [matrix-org/synapse#10978]
### Description

```
2021-09-30 07:02:52,337 - synapse.crypto.keyring - 588 - WARNING - PerspectivesKeyFetcher-13565- Key lookup failed from 'matrix.org': Failed to send request: RequestTransmissionFailed: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', '(UNKNOWN)SSL_internal', 'certificate verify failed')]>]

synapse.crypto.keyring - 588 - WARNING - PerspectivesKeyFetcher-28- Key lookup failed from 'matrix.org': Not retrying server matrix.org.
```

So I'm not sure why this suddenly started happening.  My theory is something to do with the Let's Encrypt root certificate expiring. 

More importantly, once I can fix the certificate verification (if that is even possible), how do I get my server to actually retry matrix.org?  Is there a way to force a retry?

### Steps to reproduce

- This was just discovered last week. I did nothing to cause this and thus have no idea how to reproduce it. 

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: matrix.jetcafe.org
- **Version**: 1.41.1
- **Install method**: ports/poudriere
- **Platform**: FreeBSD 12.0

**Comment by babolivier** [comment]
This sounds like an issue with your setup, maybe your system's base of CAs is outdated and doesn't have the new root certificate for Let's Encrypt.

This error message means Synapse will wait a bit before contacting this destination again (ie exponential backoff) in order to save on resources. If you think your issue is fixed and would like to make Synapse forget about waiting before retrying matrix.org, you can run the following database query:

```sql
UPDATE destinations SET retry_last_ts = 0 AND retry_interval = 0 WHERE destination = 'matrix.org';
```

and restart Synapse for this change to be taken into account.

For further support, and additional questions, please ask in the room `#synapse:matrix.org` on Matrix, as we use GitHub issues for bug reports exclusively.

**Comment by davehayes** [comment]
Thanks for that SQL. That's actually what I was after, the fix for the cert verify error seems to be to delete the expired cert from the store. I don't know where to file a bug for verification (verification should consider all the certs in the store right?), and I suspect that's not here.
