### ISSUE TITLE
can't disable identity server

### ISSUE THREAD

**Issue by horstepipe** [matrix-org/synapse#11131]
### Description

Hello
I want to use matrix as a private chat for friends so there's no need for identity servers, here. 
So in nginx I entered this to make my users not use an identity server per default:
```
location /.well-known/matrix/client {
      return 200 '{"m.homeserver": {"base_url": "https://matrix.homeserver.com"},"m.identity_server": {"base_url"""}}';
      add_header Content-Type application/json;
      add_header "Access-Control-Allow-Origin" *;
    }
```

But after logging in, I'm still seeing this:
![identity](https://user-images.githubusercontent.com/10515479/138077374-fa7143f9-6621-4401-8929-e2678014075d.PNG)

So this doesn't seem to work as intended.

### Version information

- own synapse homeserver installation

If not matrix.org:

- **Version**: 1.45.0"

- **Install method**:
 package manager (apt)

- **Platform**:

Ubuntu 20.04

**Comment by babolivier** [comment]
Hi, this is an issue with the Element client rather than Synapse (since the client is the one deciding which identity server to use, part from some edge cases), so I'd suggest opening an issue on https://github.com/vector-im/element-web (or even better, ask in their support room on Matrix: `#element-web:matrix.org`).
