### ISSUE TITLE
Extend ModuleApi with APIs to find out how many messages a user has sent and when the account was created

### ISSUE THREAD

**Issue by Yoric** [matrix-org/synapse#11173]
Both APIs would be very useful to write spam checkers.

**Comment by rhetenor** [comment]
Hey,

The account creation date can already be queried via `ModuleApi.get_userinfo_by_id`. 
For the message count I've just created a pull request that should fix this issue.

**Comment by babolivier** [comment]
As @rhetenor points out, `ModuleApi.get_userinfo_by_id` already tells modules about account creation dates. It only does it for local accounts, but that's because a homeserver has no way of knowing the creation date of an account that was created on another homeserver.

About message counts, we just had a discussion about this in #synapse-dev (https://matrix.to/#/!XaqDhxuTIlvldquJaV:matrix.org/$IQwnIgcWDM3gQ83WquHu_4e0VwNC9kHRGvMTr5PGelQ?via=matrix.org&via=vector.modular.im&via=envs.net) and concluded that the best way to do this would be on the module side, by leveraging the new `on_new_event` callback (https://matrix-org.github.io/synapse/develop/modules/third_party_rules_callbacks.html#on_new_event) that will be added by Synapse 1.47.0 (expected later today), and is called every time Synapse persists a new event. Doing it on Synapse looks like it would likely be quite expensive and non-trivial, for a result that wouldn't be complete for remote users anyway (since a homeserver has no way to know about messages it doesn't see). Plus doing it on the module's side would give the module more freedom to be peckish about what events they want to count, and how it wants to store its counts.
