### ISSUE TITLE
rename remote_thumbnail to remote_thumbnails

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-org/synapse#11222]
### Description

Configuring backups, I want to exclude media that can be regenerated since it originates on other servers. I almost did this incorrectly, since `/media_store/remote_thumbnail` does not end in `s` while the other 2 thumbnail folders for local and url previews do.

### Steps to reproduce

look at the `/media_store`

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org: my own

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.43.0

- **Install method**:
<!-- examples: package manager/git clone/pip  -->
pip

- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->
Debian 9 stretch

**Comment by squahtx** [comment]
The inconsistency surprised me too!

Unfortunately it's not trivial to rename the directory since we have to keep existing Synapse deployments in mind. While we could do the rename on startup, files in storage providers would still retain the old spelling, so we'd end up maintaining extra logic to check both spellings.

Also there's this script that would need updating too:
https://github.com/matrix-org/synapse-s3-storage-provider/blob/04d5fb7fe983672320d45a37186f396c543e891a/scripts/s3_media_upload#L131-L138

**Comment by clokep** [comment]
See also #10556.

**Comment by clokep** [comment]
I'm going to close this -- it is annoying, but documented. I think the effort to fix it is not worthwhile.
