### ISSUE TITLE
Create public spaces only available for server members 

### ISSUE THREAD

**Issue by PxBCPG** [matrix-org/synapse#11227]
Hi! 
As spaces is a new feature, I understand that some of the rooms features aren't yet here for the spaces. 
Here is my request : be able to create some spaces only visible by the server members, and not other servers.

**Comment by reivilibre** [comment]
I think this could be done by creating a public space with `m.federate` set to `false` (much like you can create non-federatable rooms), or alternatively perhaps with room ACLs (since spaces are just rooms, after all).

As such, I don't think there's anything new to be done in Synapse today to support this — but it's possible that the clients don't make it super easy to do.

I think part of this might be because creating single-server rooms defeats the purpose of Matrix, can't be changed later and feels like the wrong way to approach things in many cases.
Instead of restricting rooms/spaces to members of a server, I think the suggested approach now is to restrict rooms/spaces to members of a *space* (using 'restricted rooms'). This still gives you the simplicity and privacy, but also means that you can still allow select members from other servers to join.

Of course, creating a public space with `m.federate` set to false will probably still work and do what you asked for.

**Comment by PxBCPG** [comment]
Hi!
Thanks for your answer
How to create a public space with `m.federate` set to `false` ?

**Comment by reivilibre** [comment]
> How to create a public space with m.federate set to false ?

This is probably more of a client question, but if you're happy using cURL, then I figured it out by looking at what Element does when creating a public space and when creating a non-federated room.

1. Creating a public space using Element, copying as cURL using Firefox developer tools
```
curl 'https://matrix.librepush.net/_matrix/client/r0/createRoom' -X POST -H 'Accept: application/json' -H 'Authorization: Bearer syt_REPLACEME' -H 'content-type: application/json' --data-raw '{"name":"bob space","preset":"public_chat","power_level_content_override":{"events_default":100,"invite":0},"room_alias_name":"bob-space","topic":"","visibility":"private","creation_content":{"type":"m.space"},"initial_state":[{"type":"m.room.guest_access","state_key":"","content":{"guest_access":"can_join"}},{"type":"m.room.history_visibility","content":{"history_visibility":"world_readable"}}]}'
```

2. Creating a non-federating room using Element, copying as cURL using Firefox developer tools
```
curl 'https://matrix.librepush.net/_matrix/client/r0/createRoom' -X POST -H 'Accept: application/json' -H 'Authorization: Bearer syt_REPLACEME' -H 'content-type: application/json' --data-raw '{"name":"bob room","creation_content":{"m.federate":false},"preset":"private_chat","visibility":"private","initial_state":[{"type":"m.room.guest_access","state_key":"","content":{"guest_access":"can_join"}}]}'
```

3. Combining those together, ***this* will create a non-federated public space** (you may wish to change the name 'bob space' and the alias 'bob-space' to something less silly; also you need to fill in your access token):
```
curl 'https://matrix.librepush.net/_matrix/client/r0/createRoom' -X POST -H 'Accept: application/json' -H 'Authorization: Bearer syt_REPLACEME' -H 'content-type: application/json' --data-raw '{"name":"bob space","preset":"public_chat","power_level_content_override":{"events_default":100,"invite":0},"room_alias_name":"bob-space","topic":"","visibility":"private","creation_content":{"type":"m.space", "m.federate":false},"initial_state":[{"type":"m.room.guest_access","state_key":"","content":{"guest_access":"can_join"}},{"type":"m.room.history_visibility","content":{"history_visibility":"world_readable"}}]}'
```

Hope that's useful?

**Comment by PxBCPG** [comment]
Yes....
Is there a more "easy way" to make it, right on element ?

**Comment by reivilibre** [comment]
Sorry, you'll need to ask your client developer about that :), though be aware that internal options such as these may not make much sense in a client.

**Comment by richvdh** [comment]
sounds like this is resolved.
