### ISSUE TITLE
Clients were logged out with "InvalidMacaroonException"

### ISSUE THREAD

**Issue by TheJJ** [matrix-org/synapse#11337]
### Description

Many of our users were logged out during/after an upgrade procedure.
In the server log there were many error lines like this:

```
synapse.api.auth - 393 - WARNING - GET-0 - Invalid macaroon in auth: <class 'synapse.api.auth._InvalidMacaroonException'> 
```

### Steps to reproduce

Not sure how exactly this happened, maybe synapse was run with an empty database or a fresh config file without `macaroon_secret_key`?

Nevertheless, what should happen instead is that client do not log themselves out.
Instead, the client should either not do anything and just wait until the connectivity restores, or ask if one wants to log out.

A forced logout due to a temporary server config error should not happen.

### Version information

- **Version**: 1.46.0+bullseye1
- **Install method**: apt
- **Platform**: Debian

**Comment by richvdh** [comment]
> run synapse with macaroon

macaroons, like cookies, aren't something that you just have one of.

Please could you give more explicit reproduction steps?

**Comment by richvdh** [comment]
`macaroon_secret_key` is only used in access tokens for *guest* users. Is it correct that your users are logging in as guest users?

Generally, I'd say this is a client problem. All the server knows is that the client is presenting an invalid authentication token - it can't do much other than reject it. If you want your client to handle that more intelligently, that's up to the client.

**Comment by TheJJ** [comment]
No they are not logging in as guest, they are regular users.
I mean I'm not even sure what caused this, I just suspect the server ran with a different config.
But since macaroons are for guests only, the said exception is probably just raised since all the access tokens were not found  via `self.store.get_user_by_access_token`? So could it be that not the config was the problem, but rather the database was empty (since we had to migrate between psql versions)?

**Comment by reivilibre** [comment]
I agree that an empty database seems able to cause this error (that is, because the users' access token won't exist *and moreover* are not valid macaroons, this error is generated — misleading error message but it is what it is).

However I would have to agree with Rich that it's not clear what we could do better about this. Synapse can't really distinguish between an access token not existing because it's not valid (anymore or ever) and it not existing because the database is not fully present due to an ongoing migration.

Ideally your Postgres server should not be exposed to any live services whilst in the middle of maintenance like that. For example, you could stop Synapse (and other services using Postgres, since this problem is not just restricted to Synapse) or perhaps set [superuser_reserved_connections](https://postgresqlco.nf/doc/en/param/superuser_reserved_connections/) to the same value as your connection limit to prevent non-superuser Postgres accounts from connecting whilst performing maintenance (or you can set `hba_conf` to only allow one user to log in).

I coincidentally did a Postgres upgrade last night — I used Debian's `pg_upgradecluster` which (whilst doing the migration) starts the old and new database in a mode where only the maintenance user can log in (by changing `hba_conf`), so I didn't have this trouble. (If you're on Debian or Ubuntu, I would recommend it. There may be other alternatives which help you to do the same thing for other distros.)

**Comment by richvdh** [comment]
sounds like this is working as well as can be expected.
