### ISSUE TITLE
Is is possible to create chat system without register user?

### ISSUE THREAD

**Issue by sayalok** [matrix-org/synapse#11481]
Hi,
   I am trying to build a chat system where users can chat in a certain room without creating an account.
   
   What I want 
   User will give their Phone number and an OTP will be sent to their number they will insert it and then they will be able to start the chatting.
   
   I am trying to achieve it but so far I don't find any way to achieve this. Without registering a user I don't find a way to let the user get into the chat room.

  Please give me feedback if it is possible.
  
  I set up the server using docker and Nginx proxy manager.
  
  Thanks,

**Comment by squahtx** [comment]
Hi, we use GitHub issues for feature requests and bug reports only.
For help configuring Synapse, please use #synapse:matrix.org.

It is possible to register a user with a mobile number instead of an email - look for "msisdn" in the config.
However, the exact functionality you want does not exist. It may be possible to implement as a third party module - see https://github.com/matrix-org/synapse/blob/develop/docs/modules/password_auth_provider_callbacks.md

**Comment by squahtx** [comment]
see also: https://github.com/matrix-org/matrix-doc/issues/2740
