### ISSUE TITLE
python2 still?

### ISSUE THREAD

**Issue by ChrisFernandez** [matrix-org/synapse#1149]
I was going to try this.. but I hate the python split, and I am not installing old python2.* so saying this when are you guys going to finally use python3?  one of the reasons I never got into python is because all this fragmentation.. is silly

**Comment by ara4n** [comment]
synapse is ~50,000 lines of python/twisted.  porting it to python 3 is 
likely non-trivial, as twisted's support for python 3 is WIP, and 
switching networking framework would constitute a rewrite.

So: we'll switch synapse to python 3 once we have time to go through 
porting all the existing code and once twisted is known to be stable 
there.  I am not holding my breath.

If I were you, I'd use software based on how well it works rather than 
what language/framework it's written in...

**Comment by ChrisFernandez** [comment]
I agree with you for most part.. but the issue is prob something you guys have bring upon you...  Is not about how well it works.. fragmented software just is a pain for everyone to maintain, the people  who we build  GNU/Linux distributions can only support/test 1 language and can have both for some time but not 5 years... one will expect for fragmented developers to port their code in between 1-2 years max if not then the code is fragmented you can't expect for us to support fragmented code for 10-20 years.. in reality if developers do not make a priority to migrate when is still easy to do so, the problem just gets worse and worse.. I can't tell users to uninstall python3 that is well tested so they can run a piece of old not tested anymore software.. so is not about how well it runs.. is how well it runs on their linux distribution and support from the community in that linux distribution, to bad I like everything this is all about.. unfortunately  can't make packages of it if requires for me to appen support for python2.
