### ISSUE TITLE
Problem if too large server desynchronization

### ISSUE THREAD

**Issue by epannekoucke** [matrix-org/synapse#11510]
### Description

It seems that we have a problem with Synapse when the server that hosts it has suffered a too big desynchronization in terms of the time and date of the machine. (ex: year 2250)

### Steps to reproduce

- put the server in 2250
- 

### Version information

- gofast-comm.ceo-vision.com

- **Version**:
1.12.4
- **Install method**:
curl https://raw.githubusercontent.com/ma1uta/matrix-synapse-rest-password-provider/master/rest_auth_provider.py -o /opt/synapse/lib/python3.6/site-packages/rest_auth_provider.py

- **Platform**:
CentOS 7

**Comment by squahtx** [comment]
Can you re-test with a more recent version of Synapse and a date in 2022?  
Federation cannot work if your server clock is set to 2250 because everyone's SSL certificate expires before then.

If there are still problems with the latest Synapse version, please reopen the issue and describe the nature of the problem.
