### ISSUE TITLE
Get rid of / delete dead users in the database after using a mautrix bridge (auto-imported contacts)

### ISSUE THREAD

**Issue by KeenMaron** [matrix-org/synapse#11526]
Hi!

I just tried the mautrix-signal bridge with my matrix server. It works well, but i don't really use it and deleted it.

My actuall problem is (already posted in the mautrix-signal hub, but so far no reply):

I'm using https://github.com/Awesome-Technologies/synapse-admin to get a better overview of my groups, chats, users and so on.

I was a little bit shocked, after connecting with the bridge. My server has 6 real contacts before, after connecting with the signal account, the bridge imported all my signal contacts (and files!).
After that the Synapse-Admin Web-GUI shows over 80 contacts. Is there a way to clean this up after logging out / uninstalling the bridge? Because this are dead entries and files after uninstalling the bridge.

If the 6 real users on my server also start to use the bridge, then the user list will explode with "fake" contacts which contain the phone number and sent/received files of every signal user.

The first 6 in the table are real matrix user. The others are created by the bridge.
![image](https://user-images.githubusercontent.com/52194699/145022154-37296bbd-fbf5-46dc-888b-bc891127608a.png)

 There are serveral closed issues with a similar request to delete user completly + a script workaround which does not sound safe. It would be nice, if we can delete a user completely (after deactivation) with all related files. ( https://github.com/matrix-org/synapse/issues/1941 )

It would be awesome to delete user via "synapse-admin" webinterface.  The possibility to do maintenance and get a good overview of the matrix server with the webinterface, is a game changer for a growing diverse community which could participate on the whole project.

**Comment by squahtx** [comment]
Synapse offers a way for admins to deactivate users, delete rooms and delete all files uploaded by a user:
 * https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#deactivate-account
 * https://matrix-org.github.io/synapse/latest/admin_api/rooms.html#delete-room-api
 * https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#delete-media-uploaded-by-a-user
The deactivate user command additionally offers a GDPR erase mode, which scrubs their display name.

These commands, including the GDPR erase mode, should be available through synapse-admin; if not, you can file a feature request against that repository.

Once the above commands have been run against the signal users, they will only appear in synapse-admin when the "show deactivated users" option is selected. Their avatars and display names will not be kept. Only their user ID will remain.

It's very unlikely that Synapse will support complete removal of user IDs, since that would allow new users to impersonate deactivated ones and inherit their permissions and bans over federation.

**Comment by KeenMaron** [comment]
Hi @squahtx sorry for my post. I couldn't delte data of the singal users if files exist. I have to delete every single file to delete the user completelty. Thank you for your reply. I will send a feature request to synpase-admin :).
