### ISSUE TITLE
Useless pushes with no changes sent when reading rooms with no notifs enabled

### ISSUE THREAD

**Issue by MatMaul** [matrix-org/synapse#11704]
### Description

Duplicate pushes are sent whenever you read a room, even if notifications are disabled for this room and there is no change in the notifs count.

### Steps to reproduce

- read a room with no notifs (read receipt is sent)
- a push is sent, identical to the previous push, with no event_id/room_id and an unchanged `count`

This is annoying for big accounts that are also extensively used on a computer device, because the phone basically never sleeps.

**Comment by reivilibre** [comment]
I can see this being pretty bad because the excessive push traffic is bad for the app's 'reputation' essentially, on modern phone operating systems, resulting in pushes getting throttled.

A potential fix seems to be fairly simple:
* update `HttpPusher` to add a field to keep track of the last sent badge count
* in `HttpPusher._update_badge`, don't do anything if the count hasn't changed (and store the last-sent unread count)

**Comment by lukasdenk** [comment]
I'll work on it.

**Comment by lukasdenk** [comment]
@reivilibre Are you sure about your potential fix? 
I have set a  break point into the `HttpPusher_update_badge` and its callee, `on_new_receipts`. Everything worked but synapse never came to the breakpoints. 

I tried the following setting:
- setup a homeserver with default settings
- started two Element clients (both on ubuntu)
- created public rooms 1 and 2 with user A.
- Joined rooms 1 and 2 with user B.
- Send messages from user A to B and vice versa

**Comment by reivilibre** [comment]
@lukasdenk I suppose I can't say I'm sure until it's actually proven.
However I think your problem is that your Element Web/Desktop clients won't be using a push gateway — you'd have to use a mobile client like Element Android/iOS or FluffyChat etc.
(It might be possible to use Web Push with the Hydrogen client which runs in a browser, but I haven't been keeping track so I'm not certain.)

If I was doing this, I would say that it would probably be easiest to first write a failing test for this situation described by MatMaul.
Now you can use breakpoints as you please, and you don't have to test it all manually with a real push gateway.
When you fix the issue, you even get a test included to ensure it keeps working afterwards! :)
(`test_push_unread_count_message_count` in `tests.push.test_http` is probably one of the closest tests you can refer to, for inspiration when writing your own test.)

**Comment by himanshi-2602** [comment]
@lukasdenk are you still working on this issue?
@reivilibre can I work on this issue? 
I am a beginner but I am really interested in open source

**Comment by lukasdenk** [comment]
@himanshi-2602 Yes, I am
