### ISSUE TITLE
Admin can leave the room without assigning a new admin

### ISSUE THREAD

**Issue by avdb13** [matrix-org/synapse#11857]
### Description

One of my rooms is unmoderated since I disabled the account which I used to create the room and now there's no moderation anymore.

### Steps to reproduce

- Create new user
- Create new room
- Invite another user
- Leave the room with the admin account
- Find out that the other user doesn't have any roles

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information



<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: https://midov.pl

<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by clokep** [comment]
Being the last to manually leave a room seems like it would be better covered by the client (e.g. vector-im/element-web#2855).

Can you clarify what you mean when you said "I disabled the account" -- was this using the admin API to deactivate an account or something else?

**Comment by avdb13** [comment]
Sorry for the late reply.
>was this using the admin API to deactivate an account or something else?
Settings -> General -> Deactivate Account
So probably yes.

**Comment by reivilibre** [comment]
I think I'd have to agree with clokep here — the client would be in a better position to warn you.

Consider the alternative: if the homeserver blocks you from deactivating your account, it probably wouldn't comply with GDPR and such regulations anymore since you can't erase your account easily.

As such I think I will close this issue as I'm not sure it's up to Synapse to decide. However you may consider opening an issue on Element Web about this, if you're interested.
