### ISSUE TITLE
Synapse allows power levels bigger than 2^53 when they're string-encoded.

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/synapse#11873]
Related: https://github.com/matrix-org/matrix-doc/pull/3688

Synapse will check integer values in JSON by its canonical JSON max, but it won't do the same for powerlevels encoded in strings, these are allowed to become as big as they can (as synapse implicitly parses to bigint when doing `int()`)

I believe the ecosystem impact is minimal enough to add a simply canonical JSON integer check on this when encountering such an event, as the only rooms that would have done this are rooms that deliberately tried to stretch the limits of matrix, and no real user rooms.

**Comment by clokep** [comment]
> I believe the ecosystem impact is minimal enough to add a simply canonical JSON integer check on this when encountering such an event, as the only rooms that would have done this are rooms that deliberately tried to stretch the limits of matrix, and no real user rooms.

Pretty sure this means that you could easily split-brain a room's power-levels between Synapse versions. So, I'm not sure that's really a viable solution. 😢

**Comment by ShadowJonathan** [comment]
> Pretty sure this means that you could easily split-brain a room's power-levels between Synapse versions.

An alternative is that it split-brains betweens (currently, afaik) synapse and conduit, so indeed there doesn't seem to be a good solution.

**Comment by jplatte** [comment]
Why is it a problem to split-brain rooms that have **intentionally** been fudged with?

**Comment by turt2live** [comment]
> Why is it a problem to split-brain rooms that have intentionally been fudged with?

At the spec/matrix level we value the operation of rooms over malicious behaviour. Instead of intentionally causing problems on our side (artificial, backdated, limits) we'd rather try and work out a solution that keeps the room working while also repairing a past mistake. 

We've additionally increased the degree to which we value room operation since releasing Matrix v1.0 - that was a stable release where we were comfortable with other people building servers on top of the protocol (though were also a bit worried that we forgot some details, like stringy power levels). Now, the ecosystem is large enough where we can't make the same guarantee that we won't break something mission critical (to someone) by backdating a limitation onto the protocol, so have to consider both what Synapse was doing and is currently doing then balance that against our backwards compatibility desires.

**Comment by ShadowJonathan** [comment]
I think I'm starting to agree with jplatte here, the burden of implementation here is extremely high on other servers to replicate bigints, for little to no gain other than (realistically) superficial compatibility with rooms that should not exist in practice.

Stringy powerlevels was indeed a severe problem with many examples in many rooms, but I think this can't realistically be achieved with some extensive modification, and that real-world usecases won't go and edit initial powerlevels to put a value above 9 quadrillion *in string*, *in overrides*, just to address their use case.

Couples together with the comment I saw that this is a leftover from python2->3 conversion (as before you couldn't even represent bigints), I think that it's safe to say that the original intended maximum value is somewhere near 64-bit maximum value.

For the purposes of conversation, I consider the burden and the blame heavy on synapse here, because of the cost of implementation on other servers for something that should only exist, in practice, on heavily intentionally modified synapse homeservers, for which usage is soon phased out by MSC3667, and which was plenty illegal with the integer limits of canonical JSON anyways.

**Comment by turt2live** [comment]
I'm going to close this in favour of figuring it out on the spec side, instead of having this conversation in multiple places: https://github.com/matrix-org/matrix-doc/pull/3688

If synapse requires changes at the end of it, a new issue can be opened.
