### ISSUE TITLE
Database transaction `get_unread_event_push_actions_by_room` churns database CPU

### ISSUE THREAD

**Issue by jaywink** [matrix-org/synapse#11887]
### Description

We have a host in EMS with a room that is getting approx 2 events per second into it. A few users sitting in the room are churning the database CPU due to constant sync which is causing the synchrotron process to spend a large amount of transaction time in `get_unread_event_push_actions_by_room`.

![image](https://user-images.githubusercontent.com/1174866/152127739-d8a77443-a354-4c82-85a3-ea1295b166d0.png)

![image](https://user-images.githubusercontent.com/1174866/152127768-cd4895a0-fd46-4f44-9fd1-2d7998110a19.png)

The database query is:

> SELECT COUNT(CASE WHEN notif = ? THEN ? END), COUNT(CASE WHEN highlight = ? THEN ? END), COUNT(CASE WHEN unread = ? THEN ? END) FROM event_push_actions ea WHERE user_id = ? AND room_id = ? AND stream_ordering > ?

Two of the users in the room are causing an equal 50/50 of the database load.

Database metrics showing the query being mostly CPU time.

![image](https://user-images.githubusercontent.com/1174866/152127697-9e06e805-8520-4351-bba9-2b48d9ae8ff1.png)

More context in https://matrix.to/#/!ixSKkmjfDhyFWsKSEY:federator.dev/$ZFJ7IDlk0gt_l8ht9hEK3DZVg5mhucbaEtM4qCKPiQk?via=matrix.org&via=vector.modular.im 

### Version information

- **Homeserver**: EMS, customer in context link

- **Version**: v1.51.0

- **Install method**: Docker, official images

- **Platform**: EMS

**Comment by clokep** [comment]
We did some investigation into this today and it was due to a room with a high rate of events, but with users with very old read receipts. This caused them to query in `_get_unread_counts_by_pos_txn` (mentioned above) to do a table scan instead of using the indexes.

We pretty much did a:

```sql
SELECT count(stream_ordering), user_id FROM event_push_actions WHERE room_id = '...' GROUP by user_id;
```

This showed a few users with ~100k pending entries while most users were much smaller. This is due to those few users never reading that room (and thus never updating their read receipt).

A short term fix was to delete the rows for their users, which will cause incorrect unread message counts for those rooms.

A long term fix is probably to make the notification count calculation incremental instead of queuing all messages. This should make it robust against users not reading rooms.

**Comment by richvdh** [comment]
vaguely related: #5569

**Comment by erikjohnston** [comment]
Also looks like we will rotate at maximum ~3333 events/s (a limit of 10000 rows then a delay of 3s).

**Comment by richvdh** [comment]
> Next time this goes off we should figure out why the query takes ages to run, is there lots of push actions in the last 24 hours or are they highlights? Sounds like last time it was filled with push actions for the affected user and so the table got table scanned.

Just lots of regular unread messages. 
The query-plan looks like:

```
eexplain SELECT COUNT(CASE WHEN notif = 1 THEN 1 END), COUNT(CASE WHEN highlight = 1 THEN 1 END), COUNT(CASE WHEN unread = 1 THEN 1 END) FROM event_push_actions ea WHERE user_id = '@<user>' AND room_id = '!<room>' AND stream_ordering > 13329084;
                                                           QUERY PLAN                                                            
---------------------------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=22045.65..22045.66 rows=1 width=24)
   ->  Bitmap Heap Scan on event_push_actions ea  (cost=2043.15..21616.92 rows=28582 width=6)
         Recheck Cond: ((room_id = '!<room>'::text) AND (user_id = '@<user>'::text))
         Filter: (stream_ordering > 13329084)
         ->  Bitmap Index Scan on event_push_actions_room_id_user_id  (cost=0.00..2036.00 rows=28745 width=0)
               Index Cond: ((room_id = '!<room>'::text) AND (user_id = '@<user>'::text))
(6 rows)
```

**Comment by erikjohnston** [comment]
Sounds like we need to aggregate more aggressively then.

**Comment by erikjohnston** [comment]
This is where we'd need to add the additional rotation logic:

https://github.com/matrix-org/synapse/blob/0d17357fcdded3fa3f8a37db7b6b9aa0402a10ed/synapse/storage/databases/main/event_push_actions.py#L749-L756

Right now, it works by rotating all push actions that have a stream ordering that is older than one day, doing a max of 10000 rows per iteration. 

I think we can add a second loop where we check if there are lots of push actions for a given room, and rotate old rows until there is a max of e.g. 100 rows left in the `event_push_actions` table. This should be safe if we change the bounds of how we fetch unprocessed counts at:

https://github.com/matrix-org/synapse/blob/0d17357fcdded3fa3f8a37db7b6b9aa0402a10ed/synapse/storage/databases/main/event_push_actions.py#L821

to instead use the old stream ordering that we store in `event_push_summary`.

**Comment by erikjohnston** [comment]
Ok, so my suggestion in the previous comment doesn't work, as it results in table scanning `event_push_actions`, which is not tenable for larger hosts.

**Comment by erikjohnston** [comment]
New plan:

Have a new table called `event_push_counts`, which is like `event_push_summaries` but keeps track of the full count (rather than just up to one day ago). This will allow fetching the unread counts to be the same as today, except that the range we'll need to scan in `event_push_actions` is much smaller.

To keep it updated:

1. On a new event we:
    1. Fetch all rows from `event_push_actions` for the room/user from the `stream_ordering` in `event_push_counts` (or if a row there doesn't exist, from `event_push_summaries`).
    2. Add that count to `event_push_counts` and update the `stream_ordering`.
2. When we get a receipt from a user in a room we recalculate `event_push_counts` by counting remaining matching rows in `event_push_actions`.
3. On rotation of push actions into `event_push_summaries` no action needs to be taken, as it should be a no-op.
