### ISSUE TITLE
Why are the `deb` releases on Github put in a TAR file?

### ISSUE THREAD

**Issue by hiddeninthesand** [matrix-org/synapse#11982]
It's not strictly a feature request or a bug report, and I couldn't get any luck in the Matrix room, so I'm asking here. Releasing the files as a TAR seems very unnecessary, as it increases the amount of data that needs to be downloaded almost 50 fold. What's even more confusing is why the archive is then compressed, which saves nearly no storage but adds decompression time to extracting the required DEB. What's the reasoning behind this?

**Comment by babolivier** [comment]
The main reason is so that we can quickly download and extract the tarball when uploading the debs to packages.matrix.org. It isn't recommended for users to download and install debs from GitHub directly (and the tarball isn't intended for this use), instead users should use our repository. See https://matrix-org.github.io/synapse/latest/setup/installation.html#debianubuntu for instructions.

**Comment by hiddeninthesand** [comment]
Repository usage is actually the reason why I was asking, as I'd like to put synapse on [the MPR,](https://docs.makedeb.org/mpr/introduction/) but the strange state of affairs with the releases caught my eye.

**Comment by babolivier** [comment]
I see. Generally speaking, if your goal is to download packages independently, you should download them from https://packages.matrix.org/debian

**Comment by hiddeninthesand** [comment]
Wasn't even aware of it, thanks for the help!
