### ISSUE TITLE
have to restart server for messages to be sent

### ISSUE THREAD

**Issue by jahway603** [matrix-org/synapse#12308]
### Description

I am currently running the latest synapse version, 1.55.2. I have been experiencing this issue regarding messages not being sent out unless I reboot the whole server. Incoming messages are not affected and this only applies to outgoing messages. As soon as the server is rebooted, the stuck message(s) go out. When the issue occurs, I also notice that I'm not able to list public room directories, including the matrix.org one. This has been happening for a while and I have been unable to troubleshoot & root cause what is happening. It's been happening at least since the 1.53.0 release, but it could have been occurring before then.

I'd like to add that my Synapse server had been working from August 2021 (I believe Synapse version 1.40.0) up until this recent issue -- so it use to be working as expected.

### Steps to reproduce

- Send a message & it has a chance to "get stuck" and not send
- If it doesn't go thru, I can see it does not send on my clients on different servers. The clients on those other servers are able to send messages back, which are received on my homeserver client. I'm also able to see the typing indicator from those clients but not in the other direction.
- I do not have a good method of reproducing this issue but it appears to happen at least once a day if not more frequently which is frustrating.

### Version information

- **Homeserver**: meowchat.xyz
If not matrix.org:

- **Version**: 1.55.2 as seen on the [Matrix Federation Tester](https://federationtester.matrix.org/#meowchat.xyz)

- **Install method**: pip and upgrading via pip

- **Platform**: DietPi (Debian 11) "bare metal" on RPi 4

**Comment by anoadragon453** [comment]
Thank you for your report. We're going to need some logs from your homeserver in order to understand what's happening here. In order to help get useful logs, you'll need to:

1. Ensure you [logging level](https://matrix-org.github.io/synapse/latest/usage/configuration/logging_sample_config.html) is at least INFO (in your homeserver's logging config file: root -> level should be INFO).
2. Reproduce the behaviour on your clients.
3. Send a chunk of logs from before up until after the behaviour you're noticing, and ideally for a few minutes after that as well (in case we're waiting on timeouts, which may take up to a minute to expire).

Attaching them here as a file is easiest. You may want to give them a manual look over for any sensitive information as well, though tokens are already automatically scrubbed  at that INFO level. Note that DEBUG level logs may include sensitive data.

**Comment by MadLittleMods** [comment]
cc @alansikora who was seeing [something a bit similar](https://matrix.to/#/!bIONdorpQAHXPdfOvV:matrix.org/$x5TEjFFA2xcgrJCic2kLDZ3ge7baQ0Z-KUOXzHniHPs?via=matrix.org&via=lant.uk) in their Docker setup.
