### ISSUE TITLE
A problem about the users mail registration function

### ISSUE THREAD

**Issue by c7217** [matrix-org/synapse#12300]
I have a problem about mail registration such as an user can submit a new element's account by our custom server .
I trace the log and it shows an error message in the blow.

2022-03-25 09:38:38,238 - synapse.http.client - 455 - INFO - POST-18 - Error sending request to  POST https://mail.element.abc/_matrix/identity/api/v1/validate/email/requestToken: RequestTransmissionFailed [<twisted.python.failure.Failure service_identity.exceptions.VerificationError: VerificationError(errors=[DNSMismatch(mismatched_id=DNS_ID(hostname=b'mail.element.abc'))])>]

Whatever, I am not sure which problem cause by DNS , homeserver ,or mail setting.
But I just finish the matrix-synapse, nginx, and postfix installation.

The custom server is running well now and I hope to supply the mail registration. 
Therefore, all users can use this funtion to reset password when they forget their original pw.

**Comment by c7217** [comment]
I have completed its setting on the DNS server, and `mail.element.abc` can be resolved correctly. On my DNS server, i just add its `A`, `MX`, `TXT` record. 
When I try to use a new account to register an email address on my element server, it shows the `Internal Server Error` message.
I also follow the Synapse website `https://matrix-org.github.io/synapse/latest/setup/installation.html#email` and finish my `homeserver.yaml` settings. Should I additional configure the 3pid or another parameter?

**Comment by babolivier** [comment]
This sounds like an issue with your setup rather than a Synapse bug. We're using GitHub issues for bug tracking and feature requests exclusively, so please take your question to [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org) on Matrix, where you will receive better help than via GitHub issues.

I'm going to close this issue because I don't think using it will help you much (at least in a timely manner), but if it turns out to actually be a Synapse bug please feel free to open another one :slightly_smiling_face:
