### ISSUE TITLE
Remove code that updates `application_services_state.last_txn`

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#12352]
#12209 removed the code that reads `application_services_state.last_txn`.

In Synapse 1.58 or so, we should remove the code that writes to it.

**Comment by Fizzadar** [comment]
👍 I'll get a PR up for this.

**Comment by turt2live** [comment]
ftr I use `last_txn` to determine how many "unprocessed" transactions there are per appservice, in cases when the appservice falls over. I don't believe Synapse has metrics for this at present.

Current query: `select t.as_id, count(t.*) as unprocessed_txns from application_services_txns as t where t.txn_id >= (select s.last_txn from application_services_state as s where s.as_id = t.as_id) and t.as_id <> 'twitter' group by t.as_id;` 

*(twitter is excluded because it was turned off years ago, but still exists in the database)*

If we can get exposed metrics or similar, that'd be massively appreciated for monitoring reasons.

**Comment by Fizzadar** [comment]
I believe it should be safe just to count the number of txns per AS to get the same metric? The txns get deleted once they're sent successfully out to the AS so only live for a short period normally.
