### ISSUE TITLE
Log errors using `exc_info` - add traceback/stack trace

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/synapse#12662]
#### Description

While working on other features, I noticed that lots of (older) bits of synapse still do something like `logger.info("Error doing thing: %s", e)`, one such instance [here](https://github.com/matrix-org/synapse/blob/4337d33a73988763e27eb9450307084f8eab6f16/synapse/rest/media/v1/thumbnailer.py#L80).

All `logger` levels (including `info` and `debug`) allow providing `exc_info`, which prints the entire exception in the console as a traceback. However, if I understand sentry correctly, it will also give the exception in the correct format to sentry for ingest.

In that particular instance above, `%s` gave me no information about the error;
```
2022-05-06 20:31:40,552 - synapse.rest.media.v1.thumbnailer - 80 - INFO - GET-33 - Error parsing image EXIF information:
```

...with no lines before or after. I believe it would be a lot more debuggable with a traceback.

**Comment by anoadragon453** [comment]
This is a good point! For instance, one exception that's regularly triggered is:

https://github.com/matrix-org/synapse/blob/f96b85eca8cf14530f26b678dbb4900c54fb6a59/synapse/rest/media/v1/preview_url_resource.py#L431-L440

Picking a random example from matrix.org's logs, this results in:

```
2022-05-09 12:48:42,171 - synapse.rest.media.v1.preview_url_resource - 433 - WARNING - GET-13294456 - Error downloading https://[redacted]: ResponseFailed([<twisted.python.failure.Failure twisted.web.error.InfiniteRedirection: 302 Infinite redirection detected to https://[redacted]>])
```

The particular case that triggered this was an maximum number of redirects detected when trying to preview a URL resource. Because of the lack of handling certain edge cases (see the TODO) we are  regularly returning 500's to clients here.

Now this is fine in a broad sense, but what's not as great is that this mostly goes unnoticed - this code has not been touched in a fairly long time. If we were able to see hundreds of 500's going back to clients in sentry for this issue, it'd likely garner more attention - and clients would end up receiving less 500s.

---

With the above justification out of the way, in terms of fixing the issue, I believe we typically tend to use [`logger.exception`](https://docs.python.org/3/library/logging.html#logging.Logger.exception) instead these days, which logs at ERROR and will add available exception information to the log.

In some cases (like the one mentioned above) we may want to use `logger.warning("...", exc_info=True) instead of logging at the ERROR level.

It's also worth mentioning that this will undoubtedly spit out more exceptions in the logs, which can be scary for users - but all the more reason to ensure they don't happen?

**Comment by erikjohnston** [comment]
It's worth noting that we do *not* want to log stack traces for errors that are *expected*. Every strack trace that appears in the log should be an error that we then go and fix.

Specifically, we would not want to log stack traces for exceptions like "remote host is down" and the like.

**Comment by richvdh** [comment]
Note also that when a second exception is raised from the `except` block, as in the example given, then the exceptions will be automatically chained and, if the second exception is logged, the stacktrace will include the original exception.

I would be very surprised if any wholesale changes are appropriate here, though of course there may be individual cases that would benefit from improvement.

I vote for closing this issue.

**Comment by ShadowJonathan** [comment]
https://github.com/matrix-org/synapse/pull/12675 includes a boatload of those improvements that just need refinement and guidance, in most cases i encountered, the exceptions weren't re-raised.

**Comment by richvdh** [comment]
I'm going to close this, as it's not terribly actionable as it stands: as I said, I don''t think there is a pressing need to audit the whole codebase for places where a stacktrace would be useful. PRs improving individual areas are appreciated, however.
