### ISSUE TITLE
Implement per-room rate-limiting for remote joins

### ISSUE THREAD

**Issue by jimmackenzie** [matrix-org/synapse#12710]
**Description:**

Synapse includes a [few different levers](https://github.com/matrix-org/synapse/blob/master/synapse/config/ratelimiting.py#L147-L267) for controlling the flow of actions. We should add a new lever, and limit the number of joins to a room in a given time, including remote joins. I.e. if there has recently been lots of joins in a room (local or remote joins), then servers should ratelimit both local joins and remote attempts to join via `/make_join`.

By using the existing rate-limit infrastructure, we can tackle some of the issues set out in https://github.com/matrix-org/synapse/issues/12578 around disruptive mass-join events. Rate-limiting helps to prevent performance concerns from handling too many join events at once, and also gives time and space for room moderators to put in place further protections. 

Ideally, this limit could be adjusted on a room-by-room basis. Large public rooms would be able to adjust their individual rate-limits, while the default would protect the majority of rooms

**Comment by erikjohnston** [comment]
> Ideally, this limit could be adjusted on a room-by-room basis. Large public rooms would be able to adjust their individual rate-limits, while the default would protect the majority of rooms

This would probably need to be specced. Though I think even having quite a liberal rate limit would help against any join spam issues

**Comment by DMRobertson** [comment]
What is the proposal here? A per-room rate limit on `/make_join`, `/make_knock`, `/send_join` and `/send_knock`?

**Comment by DMRobertson** [comment]
WIP at https://github.com/matrix-org/synapse/tree/dmr/rate-limit-remote-joins

**Comment by DMRobertson** [comment]
Ideas:

- have each worker snoop on replication traffic so they can see all joins. When we see a join, record it in the rate limiter. Erik cites https://github.com/matrix-org/synapse/blob/bc9b0912cc147713c42e850fbfbb4ee396c8c839/synapse/storage/databases/main/cache.py#L174:L174 for example of snooping
- Don't track anything. Instead, make a DB query asking how many joins there were in the last $DURATION.
  -  Cache this so we don't hammer the DB if someone tries a join spam wave? Tricky since it's time-dependent.
  - Have to distinguish between profile changes (join -> join) and brand-new joins (invite -> join).
- Use redis to track joins across multiple workers. Have event persisters write that a join has taken place, and have the workers handling joins read from this.
  - Off the shelf example sounds promising: https://redis.com/redis-best-practices/basic-rate-limiting/ but isn't a 1:1 replacement for our existing limiter. Other examples:
    - https://www.infoworld.com/article/3230455/how-to-use-redis-for-real-time-metering-applications.html
    - https://engineering.classdojo.com/blog/2015/02/06/rolling-rate-limiter/
    - https://blog.callr.tech/rate-limiting-for-distributed-systems-with-redis-and-lua/
  - What about the monolith case?
