### ISSUE TITLE
No membership changes visible in log after OP on IRC set the room to 'voice only'

### ISSUE THREAD

**Issue by erciccione** [matrix-org/synapse#12915]
Hello, I was asked to move to ask here, since seem to be related to the server, not the UI. Originally opened at https://github.com/vector-im/element-web/issues/22388.

### Steps to reproduce

1. Be administrator in a room with IRC bridge (room v6)
2. An OP from IRC set the room as 'voice only'
3. See no membership changes in the log on both desktop and mobile (but membership changes appear for a matrix user on another server), but permissions actually changed.

#### What did you expect?

Membership changes for all users in the room visible in the room log

#### What happened instead?

Nothing. No messages at all about membership changes. Note that manual membership changes for single users appear in the log as expected.

### Homeserver

synapse 1.59.1

**Comment by squahtx** [comment]
For the record, issues to do with the IRC bridge should be filed against https://github.com/matrix-org/matrix-appservice-irc.

Toggling 'voice only' / `+m` will not cause the IRC bridge to set the power level of every bridged user, because that would be extremely inefficient.
Instead, the IRC bridge will set the room's `m.room.power_levels`'s `events_default` to `1`, to stop users without voice (`+v`) from sending messages. This is by design.

Clients might not necessarily show the change of `m.room.power_levels`, which is why nothing is shown.

**Comment by erciccione** [comment]
> For the record, issues to do with the IRC bridge should be filed against https://github.com/matrix-org/matrix-appservice-irc.

This is not an issue related to the bridge though, as there is nothing wrong happening on that side.

> Clients might not necessarily show the change of m.room.power_levels, which is why nothing is shown.

This is a problem. If i'm an administrator of a bridged room, i want to see changes coming from IRC that impact my matrix room. I'm in a situation when i'm not aware of the status of my own room and the fact that people (from both matrix and IRC) have no possibility to post in the room, unless i log in to IRC to manually check its status.

Admins should be told somehow that users cannot post in the room. Right now, from one moment to another, users find themselves unable to post without knowing. That's bad user experience and creates a number of problems.
