### ISSUE TITLE
Faster joins: support sending messages from clients during the half-joined state

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#12997]
This is theoretically simple. Currently we are blocking on calculating whether there are remote servers we need to send to, but we have a separate list of servers, so we just need to update the code to use it

# Subtasks

- [x] #14057
- [x] #14058
- [x] #14059

**Comment by squahtx** [comment]
We'll probably want to test that remote Synapses can accept the events sent out while half-joined too.

As [Erik notes](https://github.com/matrix-org/synapse/issues/13288#issuecomment-1199278522), we have to respond to `get_missing_events`, among other things. There are also paths where a Synapse will try to use `/state_ids` or `/state` (which the half-joined server cannot answer!) when receiving an event with unknown prev events.

**Comment by reivilibre** [comment]
As part of https://github.com/matrix-org/synapse/issues/13288#issuecomment-1238287290, I've suggested that we keep track of (or otherwise know how to find out) which servers we've sent some events to and then answer relevant `/get_missing_events` queries for the `prev_events` of the events that we send, otherwise the remote homeserver has reason to reject the event. I suggest that we then don't answer in other cases, as we don't definitively know the set of servers in the room and so we can't necessarily know if the server is allowed to fetch events from us.

**Comment by reivilibre** [comment]
(assigning self because I have been thinking of ideas with Rich about some of the subtleties of sending PDUs and have some things to write up at the very least)

**Comment by MatMaul** [comment]
This has been successfully tested.
