### ISSUE TITLE
Faster joins: fix race in calcuating "current state"

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#13007]
Once we finish un-partial-stating events, we update the `current_state_events` table to include the complete state of the room. However, that can race against the persistence of an event, which also updates this table - so we may end up with completely bogus "current state" data.

https://github.com/matrix-org/synapse/blob/7c6b2204d143550d81e5bf9612c4e69fe0866b4c/synapse/storage/controllers/persist_events.py#L384-L399

Related: https://github.com/matrix-org/synapse/issues/12988

**Comment by squahtx** [comment]
The easiest fix to reason about would be to move the entirety of `update_current_state` to the event persister queue on the correct worker. There's supposed to be only one event persist going on per room at a time.

I think this'll require a new replication endpoint plus modification of the queue so that it can hold two types of task.

**Comment by squahtx** [comment]
Note to self: we determine the correct worker to send replication requests to like so:
https://github.com/matrix-org/synapse/blob/92103cb2c8b8bff6b522a7bfa8a3a776b4821b11/synapse/handlers/message.py#L1345-L1349

where
```py
self._events_shard_config = self.config.worker.events_shard_config
```
and we assert that we are running on the correct worker like so:
```py
assert self._events_shard_config.should_handle(self._instance_name, event.room_id)`
```
