### ISSUE TITLE
Room retention parameter stopped working

### ISSUE THREAD

**Issue by FlanOfHarmony** [matrix-org/synapse#13101]
### Description

[My issue](https://github.com/vector-im/element-web/issues/22599) on the `element-web` repo got closed and I was told to post here. So here's a repost.
 I'm a simple user registered on the public servers of matrix.org, using Element as client (same for all the persons I talk to). 

In several rooms I'm in, I created room retention parameters with dev tools about ~a year ago. It seemed to work, after doing the tampering, messages older than the period I defined could not be loaded, only younger or cached ones remained. About 1-2 weeks ago, I was extremely disappointed to see that it was now possible to see all previouses messages, all the way back to at least ~6 months ago. I didn't go all the way back to the start because it's too much time consuming, but I guess that means no message has ever been deleted.

I know that room retention "isn't part of the Matrix specification yet", but I expected it to be implemented on matrix.org. By the way I saw that there has been [some developments](https://github.com/vector-im/element-web/issues/3800#issuecomment-1138270779)  room retention parameters. But if clients did not care about room retention before this, and messages never got deleted, why did it seem to work the way it was supposed to? I don't understand. 

When I do 'Open DevTools' -> 'Explore Room State' -> 'm.room.retention', my settings are still here (here it's configured for 1 week retention):
```
"content": {
    "enabled": true,
    "expire_on_clients": true,
    "max_allowed_lifetime": 31104000000,
    "max_lifetime": 604800000,
    "min_allowed_lifetime": 0,
    "min_lifetime": 0
  },
  ...
  ```
  As can be seen, I even sent the event again with `"expire_on_clients": true,` just in case, cleared the cache: no effect.

I'm using Fedora 36, my Element version is 1.9.8 Olm version: 3.2.8. I'm just a user of your official servers at matrix.org so I do not have some of the relevant informations below.

### Steps to reproduce

- Create retention parameters for encrypted rooms, a year ago
- It seems to work for a year
- Every message reappears / is now accessible indicating they actually never got deleted

### Homeserver

matrix.org

### Synapse Version

I don't know how to check this, but rooms are all version 6

### Platform

Don't know

### Relevant log output

```shell
Don't know
```

**Comment by FlanOfHarmony** [comment]
I just thought of it but this whole time maybe the server was preventing messages past their expiration date to load, never deleted a single one / never did any purge and then recently decided to even stop complying with the rule of preventing expired messages from loading.

**Comment by babolivier** [comment]
This sounds to me like you were experiencing the bug https://github.com/matrix-org/synapse/pull/12611 fixed in Synapse 1.60. Now that it has been fixed messages are no longer erroneously filtered out from clients' view.

Support for room retention is disabled by default on Synapse and needs to be enabled in the homeserver's configuration, as the feature is still unstable and needs to be stabilised in the Matrix spec (plus there are some bugs with its implementation in Synapse).

This feature is not enabled on matrix.org, which is why your messages haven't been purged.

This feature will eventually be enabled on matrix.org once [MSC1763](https://github.com/matrix-org/matrix-spec-proposals/pull/1763) is merged in the spec and said bugs are fixed. We don't plan to enable it before then.

I'm going to close this issue as it's not reporting an actual bug. Feel free to join [`#synapse:matrix.org`](https://matrix.to/#/#synapse:matrix.org) if you want to discuss this further.

**Comment by FlanOfHarmony** [comment]
Having believed for a year that messages were being deleted and suddenly finding that not a single one got deleted is a hard pill to swallow. There are some things I might have not discussed knowing it.
That + the fact that no official build of element for fedora are allowed because of non-free software in Electron (see [this](https://copr.fedorainfracloud.org/coprs/taw/element/)) is leaving a bad taste in my mouth...

**Comment by richvdh** [comment]
I'm sorry if you feel that you were misled. It wasn't intentional, but rather an oversight when the experimental support for retention was added to Synapse's development trunk. In general, it is not valid to assume that `matrix.org` implements all the proposed Matrix spec changes. 

As for taw's decision to stop maintaining Fedora packages for Element: I think the reasons are rather different to what you imply, but in any case, it's hard to see how that is relevant here. There are other ways to obtain Element, and other clients.
