### ISSUE TITLE
Respond with `soft_logout: true` when user doesn't exist

### ISSUE THREAD

**Issue by RyanGibb** [matrix-org/synapse#13203]
From https://github.com/vector-im/element-web/issues/22728:

> I recently updated my server machine, which changed the postgres server from version 13 to 14. This created a new database which removed my user account. On failing to authenticate, all my element clients logged out. When restoring the postgres v13 database, I had to reauthenticate all my clients. Luckily one was offline for the duration of this disaster, so I could recover the encryption keys without the security key.

I believe changing synapse to use `soft_logout: true` by default in cases where the user doesn't exist would solve this.

**Comment by reivilibre** [comment]
Can you explain a bit more how upgrading Postgres wound up causing this?
What does your deployment look like?

If I upgraded Postgres and had a new Postgres cluster created as a result, then there wouldn't be a database or role for Synapse in Postgres and Synapse wouldn't start up in the first place. What went differently here?


I also note that a server that has a blank database has no way of knowing what user that access token is for, so wouldn't be able to know that it's for a user that doesn't exist. I think detecting this case in general is pretty tricky...

**Comment by RyanGibb** [comment]
Thanks for the reply @reivilibre 

> What does your deployment look like?

My deployment configuration is [here](https://github.com/RyanGibb/nixos/blob/master/modules/services/matrix.nix) in [nix](nixos.org).

> Can you explain a bit more how upgrading Postgres wound up causing this?

I upgraded to Nixpkgs 22.05 from 21.11, which upgraded the default Postgres instance to [14 from 13](https://github.com/NixOS/nixpkgs/blob/316b762afdb9e142a803f29c49a88b4a47db80ee/nixos/modules/services/databases/postgresql.nix#L298).

By default, PGDATA is `/var/lib/postgresql/VERSION` in NixOS. So upgrading the package caused a new database to be created. Pinning the Postgres version fixed this, and so would presumably changing the data directory to be consistent (as long as Postgres supports this).

While I realize the above is quite Nix-specific, I do think the situation of someone messing up their database config and/or data directory is more general.

> If I upgraded Postgres and had a new Postgres cluster created as a result, then there wouldn't be a database or role for Synapse in Postgres and Synapse wouldn't start up in the first place. What went differently here?

[Nix magic](https://github.com/RyanGibb/nixos/blob/0d626d3259d906d420269e85d6d07b2577c99433/modules/services/matrix.nix#L10) automatically sets up the user for my in a reproducible way.

> I also note that a server that has a blank database has no way of knowing what user that access token is for, so wouldn't be able to know that it's for a user that doesn't exist.

Sorry, I'm not sure what you mean by this. Would using a soft logout on failure to authenticate an access token not work for this case?

Thanks for your help!

**Comment by t3chguy** [comment]
@reivilibre diskfill can also cause this - see https://github.com/vector-im/element-web/issues/22859

**Comment by pedro-nonfree** [comment]
finally, after some debugging ( https://github.com/matrix-org/synapse/issues/13305 ) diskfill is unrelated to this

**Comment by reivilibre** [comment]
@RyanGibb 

> My [nix config](https://github.com/RyanGibb/nixos/blob/0d626d3259d906d420269e85d6d07b2577c99433/modules/services/matrix.nix#L10) automatically sets up the user for my in a reproducible way.

I believe this is the root cause of the problem. You essentially have code that automatically creates a blank database and user for Synapse instead of upgrading your existing one.


> > I also note that a server that has a blank database has no way of knowing what user that access token is for, so wouldn't be able to know that it's for a user that doesn't exist.
> 
> Sorry, I'm not sure what you mean by this. Would using a soft logout on failure to authenticate an access token not work for this case?

I was going to say: The access token doesn't say who it is for, so we can't distinguish between 'access token missing because the database has been reset for some accidental maintenance reason' and 'access token is missing because the user wanted to log out that device, e.g. if they lost their phone and want to log it out remotely'.
We absolutely don't want soft logout for the latter case (since it's been done on purpose, e.g. to prevent keys from being extracted from a stolen device, if possible).

That said, `syt_xyz_xyz` tokens **do** contain the base64 of the user ID's localpart, so we *could* know which user is being talked about (not sure if this will interact well with virtual hosting, since we'd have to assume the server name or extract it from the HTTP request...).

Or an easier way: we can detect the empty database failure mode quite easily: just see if there are no users in the users table. That probably points to a maintenance fault. (A partial backup being restored is not something we can detect, but you really shouldn't run Synapse under that condition anyway as I'm pretty sure other things would already explode...)

**Comment by reivilibre** [comment]
If Synapse can't connect to the database (because you didn't create a blank one), I think you'd just get a 500 error (if Synapse starts up at all). It might be interesting to try it out though for sure.

**Comment by RyanGibb** [comment]
I'll try and get round to that, but for now I'll close this as we can't distinguish between a user not existing (due to a maintenance error) and a device having it's access revoked (due to the user logging that device out).

The solution to avoid loosing encryption keys is using a security key backup.
