### ISSUE TITLE
Faster joins: incoming federation requests during resync may be incorrectly rejected

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#13288]
If a remote server sends us a federation request (such as `get_missing_events`, or requesting a space summary) during a state resync, we may well reject that request due to not thinking the remote server is in the room. 

Possibly we need to define some return code to say "sorry, can't auth you right now".

**Comment by richvdh** [comment]
> Possibly we need to define some return code to say "sorry, can't auth you right now".

(or just rely on the list of servers we get during the join dance)

**Comment by erikjohnston** [comment]
Note that if we send out an event we *must* respond to `get_missing_events` correctly or we risk having our event rejected (due to the remote server not being able to get the prev events)

**Comment by reivilibre** [comment]
> Note that if we send out an event (as per #12997) we _must_ respond to `get_missing_events` correctly or we risk having our event rejected (due to the remote server not being able to get the prev events)

This is a very valid point. (I also think this is an interoperability landmine; it would be good for the spec to be very clear about what exactly a homeserver needs to be able to answer when sending an event! — I don't see anywhere where it says the sending homeserver has to be able to produce the `prev_events` of an event it is sending..).

We could track which events are `prev_events` of the events that we have sent out during the partial join and allow these to be returned to `get_missing_events`. This supposes that this is sufficient for getting the other server to accept our event, but it would be nice if this was rigorously defined in specification!

> Possibly we need to define some return code to say "sorry, can't auth you right now".

This sounds like it might be nasty, because we can't retroactively create an error code that non-MSC2706-implementing homeservers will understand. Maybe this is OK anyway though, because other homeservers have to treat us as potentially malicious and they need to be equipped to handle strange error responses from us by falling back to other servers as appropriate.

> (or just rely on the list of servers we get during the join dance)

Note that this can fall out of sync with reality. This is probably still OK 

If a new server joins the room and we receive the event, we can handle that.
But we can't handle a server leaving the room, because we may see a leave event for one of the server's users, but we need to know whether it's the last user from that server (and by implication, we need to know all of that server's users, at least in the current model).

**Comment by reivilibre** [comment]
Here's a thought: can we modify partial-state joins so that we **can** keep track of which servers are in the room?

How about changing

> servers_in_room: A new field of type [string], listing the servers active in the room (ie, those with joined members) before the join.

to

> servers_in_room: A new field of type {string: integer}, listing the servers active in the room (ie, those with joined members) before the join and giving the number of joined members from that server.

Both of these are abstract interpretations of the set of users in the room — in the sense that they tell you something useful about the set of users in the room, but only the latter is updatable (or at least it seems that way to me):
Assuming that we, as a partial-stated homeserver, can correctly witness join→leave and leave→join transitions, we can keep updated with the list of servers in the room, whilst withstanding membership changes, just by keeping a tally of the number of users per server. If the server drops down to zero, they're out. New users joining from unknown servers start the count as zero.

**Comment by reivilibre** [comment]
> Here's a thought: can we modify partial-state joins so that we can keep track of which servers are in the room?

**Comment by richvdh** [comment]
> Note that if we send out an event (as per #12997) we _must_ respond to `get_missing_events` correctly or we risk having our event rejected (due to the remote server not being able to get the prev events)

but... in that particular case, we know the list of servers we sent the event to, so can't we just use the same list to decide whether they are allowed to `get_missing_events`?

**Comment by richvdh** [comment]
> > Note that if we send out an event (as per #12997) we _must_ respond to `get_missing_events` correctly or we risk having our event rejected (due to the remote server not being able to get the prev events)
> 
> but... in that particular case, we know the list of servers we sent the event to, so can't we just use the same list to decide whether they are allowed to `get_missing_events`?

@reivilibre points out that this runs the risk of us divulging room content to a server that has since left the room, but also makes a good suggestion for how to avoid this: ensure that all events that we create during the room resync are maintained in a fork of the DAG starting at our join.
