### ISSUE TITLE
ModuleAPI: provide method to resolve room_alias to room_id

### ISSUE THREAD

**Issue by uriesk** [matrix-org/synapse#13359]
I am writing a pluggable module that joins rooms on login,
and i resolve room alias to id with:

```python
    async def translate_room_aliases_to_ids(
        self,
        room_aliases: List[str],
    ) -> List[str]:
        room_ids = []
        logger.info('Translating room_aliases to ids')
        for alias in room_aliases:
            aliasObject = RoomAlias.from_string(alias)
            room = await self.api._store.get_association_from_room_alias(aliasObject)
            if room is not None:
                logger.info('Map alias %s to room %s', alias, room.room_id)
                room_ids.append(room.room_id)
        return room_ids;
```

Which isn't great, because i go through api._store.
Would be nice to have such a functionality in the api itself.

**Comment by uriesk** [comment]
also a method to set email / threepids would be nice, this is what i am using now:

```python
    async def set_email(
        self,
        user_id: str,
        email: str
    ) -> bool:
        threepid_dict_list = await self.api.get_threepids_for_user(user_id)
        for threepid_dict in threepid_dict_list:
            if threepid_dict['address'] == email:
                logger.info('User %s has same email as in ppfun. Nice', user_id)
                return False
        logger.info('User %s did not have email %s set, adding it', user_id, email)
        current_time = self.api._hs.get_clock().time_msec()
        threepid_dict = {
            "medium": "email",
            "address": email,
            "validated_at": current_time,
        }
        registration_handler = self.api._hs.get_registration_handler()
        await registration_handler._register_email_threepid(user_id, threepid_dict, None)
        return True
```

**Comment by babolivier** [comment]
> also a method to set email / threepids would be nice, this is what i am using now

This method will probably be implemented separately to the one you're initially requesting, could you make a separate issue about it so it's better tracked please?

**Comment by uriesk** [comment]
of course, #13402

**Comment by buffless-matt** [comment]
@uriesk

I coincidentally have a present need for this as well :smile:

I'm not sure [DirectoryWorkerStore.get_association_from_room_alias](https://github.com/matrix-org/synapse/blob/583f22780f44157c50bc2dc5c242e88cc18c7886/synapse/storage/databases/main/directory.py#L34-L66) would be appropriate to use for this new module API method and instead I think [RoomMemberHandler.lookup_room_alias](https://github.com/matrix-org/synapse/blob/583f22780f44157c50bc2dc5c242e88cc18c7886/synapse/handlers/room_member.py#L1334-L1363) would be more appropriate because:

- It handles both local and non-local/federated rooms.
- It also queries appservices to try and do the translation.

The method could be accessed (in this new module API method) via `self._hs.get_room_member_handler()`.

**Comment by buffless-matt** [comment]
This was completed in #13428, so this issue can be closed.
