### ISSUE TITLE
Power Level

### ISSUE THREAD

**Issue by Erko21** [matrix-org/synapse#13457]
Is there a possible way to change power level of admin by another admin?

**Comment by reivilibre** [comment]
If they have equal power levels, no, sorry.

A **server admin** on that admin's homeserver can potentially use the Admin API to make them demote themselves, but otherwise there's no way to do what you want to do.

A potential workaround in some cases is to create a new room where that admin doesn't have the power level and then post a 'tombstone' event into the old room to the new one (that is the way of marking that the room has been replaced).
