### ISSUE TITLE
High CPU/DB usage from `ReplicationUserDevicesResyncRestServlet`

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#13518]
Sometimes our main process sees high CPU and DB usage due to thousands of requests to `ReplicationUserDevicesResyncRestServlet`:

![image](https://user-images.githubusercontent.com/1389908/184367570-14428f26-0348-4f2d-9b71-69205dfbf59e.png)

We should find out what is calling this, and stop it doing so.

**Comment by richvdh** [comment]
(this is enough CPU and DB usage to stop synapse responding to other requests, which is problematic)

**Comment by squahtx** [comment]
May possibly have the same cause as #12890, where we saw a client endlessly retry `POST /_matrix/client/v3/keys/query` (which calls `ReplicationUserDevicesResyncRestServlet`) because it kept timing out. Each request went into a linearizer queue, behind previous requests, which guaranteed another timeout.

**Comment by richvdh** [comment]
Yes, that looks right. I'll close this in favour of #12890.
