### ISSUE TITLE
Automatically sync avatars

### ISSUE THREAD

**Issue by MomentQYC** [matrix-org/synapse#13532]
**Description:**
The avatar will be automatically synchronized each time a dialog window is opened to avoid the avatar cannot display after being mistakenly cleaned.

**Comment by DMRobertson** [comment]
Unfortunately I don't understand what you're asking for. Could you give an example?

**Comment by MomentQYC** [comment]
> Unfortunately I don't understand what you're asking for. Could you give an example?

For example, if I delete the "remote_thumbnail" folder when cleaning up the server (after all, synapse occupies an astonishing storage space), synapse will not be able to display the corresponding user's avatar.
Of course, another solution is to directly reference the avatar from the remote server.

**Comment by anoadragon453** [comment]
I believe what's being asked is for Synapse to gracefully handle the case of media on disk being removed without the corresponding entry in the media store database being cleared as well.

And I'm not sure if I agree with that, at least for the remote media use case. If the media on disk has disappeared (perhaps you've forgotten to mount a filesystem), should that not be painfully obvious to you and your users such that you can fix it? Rather than falling back to re-downloading the media from the remote server each time.

> mistakenly cleaned

This isn't a supported use case. In your specific case, assuming you delete all remote media thumbnails on disk, you can clear the corresponding database entries in order to get Synapse to resync them:

```
TRUNCATE remote_media_repository_thumbnails;
```

and then restart Synapse to clear out any in-memory caches.

**Comment by richvdh** [comment]
note that the [purge remote media api](https://matrix-org.github.io/synapse/latest/admin_api/media_admin_api.html#purge-remote-media-api) is the correct way to clear disk soace used by remote media.

**Comment by MomentQYC** [comment]
> note that the [purge remote media api](https://matrix-org.github.io/synapse/latest/admin_api/media_admin_api.html#purge-remote-media-api) is the correct way to clear disk space used by remote media.
```
curl --header "Authorization:A B" -X GET 127.0.0.1:8008/_synapse/admin/v1/purge_media_cache?before_ts=C
```
An error has occurred.
```
{"errcode":"M_UNRECOGNIZED","error":"Unrecognized request"}
```

**Comment by anoadragon453** [comment]
The endpoint requires the `POST` method, but you've specified `-X GET`.
