### ISSUE TITLE
 Derive the `m.server` of `.well-known/matrix/server` from public_baseurl instead of server_name

### ISSUE THREAD

**Issue by hrenard** [matrix-org/synapse#13539]
**Context**
As a hosting provider, I prefer to use the well-known delegation and ask of my customers only a proxy of `<server_name>/.well-known/matrix/*` to `<delegate_name>/.well-known/matrix/*`.

**Description:**
Synapse derives the `m.server` of `.well-known/matrix/server` from server_name which is bad when using delegation.
Wouldn't be better to use public_baseurl instead ?
When not delegating, it uses the server_name anyway :
https://github.com/matrix-org/synapse/blob/c3516e9decc355b75a297d72a13b98a43d312e66/synapse/config/server.py#L280-L288
But maybe there are other scenarios I don't know about.

I'm willing to make a PR if you think it's the way to go :smile:.

**Comment by anoadragon453** [comment]
> As a hosting provider, I prefer to use the well-known delegation and ask of my customers only a proxy of `<server_name>/.well-known/matrix/*` to `<delegate_name>/.well-known/matrix/*`.

To me this is a slightly odd use case. Having Synapse generate a `.well-known/matrix/server` file is somewhat incompatible with delegation, for if you're already reaching the delegated URL that Synapse is running on, there's no need to have an `m.server` entry.

There becomes a need if you're proxying your well-known server file but not any other federation traffic, as you are currently, but in this case we recommend people write their own .well-known/matrix/server file, instead of having Synapse generate it.

Synapse's support for generating well-known server files is limited by design; it's only purpose is to redirect incoming federation traffic from port 8448 to 443. [The documentation](https://matrix-org.github.io/synapse/latest/delegate.html#serving-a-well-knownmatrixserver-file-with-synapse) has some further words to that effect.

**Comment by hrenard** [comment]
Okay, got it. This isn't the role of the homeserver. Just reaching for the simplest setup :smile:.

Anyway I'm using [Ananace's chart](https://gitlab.com/ananace/charts/-/tree/master/charts/matrix-synapse) which deploy a lighttpd server for that.
