### ISSUE TITLE
`/account/deactivate` is 500ing

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#13560]
### Description

Almost all requests to /_matrix/client/r0/account/deactivate on matrix.org failing with 500.

### Steps to reproduce

deactivate an account (might need to be social login); watch 500.

### Homeserver

matrix.org

### Synapse Version

1.65.0 (b=matrix-org-hotfixes,d20c92d2c2)

### Platform

debian

### Relevant log output

```shell
File "/home/synapse/src/synapse/http/server.py", line 368, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/home/synapse/src/synapse/http/server.py", line 574, in _async_render
    callback_return = await raw_callback_return
  File "/home/synapse/src/synapse/rest/client/_base.py", line 99, in wrapped
    return await orig(*args, **kwargs)
  File "/home/synapse/src/synapse/rest/client/account.py", line 316, in on_POST
    await self.auth_handler.validate_user_via_ui_auth(
  File "/home/synapse/src/synapse/handlers/auth.py", line 344, in validate_user_via_ui_auth
    result, params, session_id = await self.check_ui_auth(
  File "/home/synapse/src/synapse/handlers/auth.py", line 470, in check_ui_auth
    if "session" in authdict:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by ara4n** [comment]
Looks like this broke on Wedesday morning; the first failing req was at 2022-08-17 09:57:26,485Z

**Comment by DMRobertson** [comment]
Suspect my pydantic changes in #13188.

**Comment by reivilibre** [comment]
Ah. This should illustrate the root cause of the problem:

```python
>>> body = DeactivateAccountRestServlet.PostBody.parse_obj({})
>>> body.dict()
{'auth': None, 'id_server': None, 'erase': False}
```

This then causes the following line a problem:
```
authdict = clientdict.pop("auth", {})
```

If `clientdict` were an empty dict here, as it was before, then `authdict = {}`. But since Pydantic 'fills in' the missing fields with their default values (`None` here), then it will get `None` instead.
The real thing to blame is that the UI auth code is still using type unsafe `Dict[str, Any]`s everywhere, so this would never have been caught statically.

**Comment by reivilibre** [comment]
- [ ] Need to make sure that Complement will catch this in the future.
