### ISSUE TITLE
Cache autotuning not working: memory under-reported from jemalloc

### ISSUE THREAD

**Issue by Fizzadar** [matrix-org/synapse#13571]
Allocated memory reported from jemalloc appears to be significantly under-reported in our install, preventing cache autotuning from working at all.  The actual process memory usage and tracked cache memory usage appear correct but the jemalloc stats, although growing roughly the same, appear totally out of sync; jemalloc allocated memory:

<img width="2201" alt="Screenshot 2022-08-19 at 16 06 40" src="https://user-images.githubusercontent.com/1026154/185650741-7ed2f11e-6304-406b-8bbe-a04519445872.png">

And per-cache(+total) memory reported by synapse:
<img width="2128" alt="Screenshot 2022-08-19 at 16 06 33" src="https://user-images.githubusercontent.com/1026154/185650815-998108b4-2d49-48a8-9780-0787bbe1f3fc.png">

Actual process memory:

<img width="1230" alt="Screenshot 2022-08-19 at 16 10 50" src="https://user-images.githubusercontent.com/1026154/185650844-67ba1a34-ba94-421e-84f1-f2af436ae21f.png">

---

Unsure if this is an environment or code related issue or perhaps something in jemalloc (seems unlikely).

**Comment by Fizzadar** [comment]
One thought on this: what about using psutil or similar to get process memory to support environments not using jemalloc?

**Comment by anoadragon453** [comment]
Where is your build of Python coming from? Do you know whether it has been built with a statically linked copy of `malloc`, rather than attempting to load one dynamically? `LD_PRELOAD` will only work in the latter case.

When we switched matrix.org's Synapse to Pyston, we noticed that jemalloc was only being used for a small subset of malloc operations. Except from an internal ticket:

> We noted that Pyston wasn't making use of jemalloc for most memory allocations, even though we're running with:
> 
> ```
> LD_PRELOAD=libjemalloc.so.2 PYTHONMALLOC=malloc ...
> ```
> 
> [jemalloc's wiki](https://github.com/jemalloc/jemalloc/wiki/Getting-Started) notes that the `LD_PRELOAD` method may not work if your application statically links a malloc implementation. So the next step is to try building a copy of Pyston (rather than grabbing one off [their releases page](https://github.com/pyston/pyston/releases/tag/pyston_2.3.3)) with the `--without-pymalloc` configure flag.
> 
> Pyston prevents you from running CPython's configure directly however, as it actually does so itself (multiple times). There is a provided env var for adding additional configure flags however. So to build Pyston, we should do:
> 
> ```
> CONFIGURE_EXTRA_FLAGS="--without-pymalloc" make
> ```

The above ended up producing a build of Python (or Pyston in this case) that relied on dynamically-linked malloc for all memory operations. The `LD_PRELOAD` trick then worked, and we saw our jemalloc stats now closely following the total memory usage, whereas beforehand it was very far behind.

**Comment by Fizzadar** [comment]
> Where is your build of Python coming from?

Aha! We're basing off pyston's docker images which I assume come straight out of their releases. Will build our own base and see where that gets us, thank you!

**Comment by H-Shay** [comment]
Just curious if this is still an issue or if the suggestion remedied the issue?
