### ISSUE TITLE
Existing user account on synapse not known when connecting via Single Sign On ( SSO ), new account creation needed.

### ISSUE THREAD

**Issue by nono-lqdn** [matrix-org/synapse#13757]
### Description

Hello everyone,

We've setup a Matrix server via the [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy) playbook. We also have a Keycloak server running our Single Sign On software. 

We had created our accounts on Synapse by connecting to the SSO, and it worked great.

Recently, we've updated our Keycloak server ( which we had done before ), and when we login via Element, with the SSO, we are now prompted to create a new account. The weird part is that the existing sessions, with our existing accounts, still work. 

As such, we now have several matrix accounts linked to the same SSO account. But we can only access the last one created, and not the previous ones. 

We were wondering what kind of bug could that be ? 

### Steps to reproduce

- Install a Matrix server with Element via the matrix-docker-ansible-deploy playbook.
- Configure OpenID connect login as described in https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/5c0c0d5af07c8daf502ed84059ccf6dbbaf634c5/docs/configuring-playbook-synapse.md#synapse--openid-connect-for-single-sign-on with a Keycloak server.
- Update your Keycloak server.
- Try to login with Keycloak. 

### Homeserver

Our own homeserver

### Synapse Version

Homeserver version: Synapse 1.61.0

### Installation Method

Docker (matrixdotorg/synapse)

### Platform

Debian 11 server

### Relevant log output

```shell
The logs where lost in a synapse reboot. Sorry :(

They contained no errors tho, just the creation of the new user.
```

**Comment by babolivier** [comment]
It sounds to me like the user IDs on Keycloak's side changed, or the way it presents them to Synapse did. I find it unlikely that this would be a Synapse issue if this was triggered by a Keycloak update. I would suggest looking into it from Keycloak's side, and possibly using [this admin API](https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#create-or-modify-account) to update the bindings between Matrix users and Keycloak IDs if necessary.

For further help, I would recommend asking in [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org), which is our preferred way for support requests and will get more eyes on your issue. Feel free to open a new issue if it turns out to actually be a Synapse bug (though please include logs, even if they don't contain any error, INFO logs can help us understand what Synapse is doing and what might be going wrong).

**Comment by MatMaul** [comment]
Hi there, it's highly probable something changed regarding the content of one of the field provided by keycloak, and used to map the user.

Can you provide us with the generated usernames on Matrix of the different accounts before and after the upgrade ? Just the pattern is enough, no need for personal info, firstname.lastname for example, or else.

Please also give us the content of `user_mapping_provider` of the oidc config part of your homeserver.yaml.

Last but not least, Keycloak versions before and after the upgrade could also be useful.

**Comment by MatMaul** [comment]
Providing those infos ☝️ in synapse room as suggested by Brendan should help you get a fast answer there.

**Comment by nono-lqdn** [comment]
Indeed, the issue was with Keycloak changing the user's UUID. Thanks everyone. For future reference, I changed theses ID via Synapse-Admin.
