### ISSUE TITLE
Add aarch64 wheels to build workflow

### ISSUE THREAD

**Issue by MichaIng** [matrix-org/synapse#13938]
**Description:**

Would it be feasible to add aarch64 wheels to the build workflow to be uploaded to PyPI? ARM play an increasing role among servers and pre-compiled wheels save users a lot of compile time and build dependencies, since Rust is required now with v1.68.0.

**Comment by DMRobertson** [comment]
IIRC we produce aarch64 docker images, so I don't see why we wouldn't also produce wheels for that platform.

cibuildwheel apparently supports aarch64, judging by the table at https://cibuildwheel.readthedocs.io/en/stable/#what-does-it-do

I wonder why `manylinux musllinux aarch64` doesn't show up in the binaries [we upload](https://pypi.org/project/matrix-synapse/1.68.0/#files). Tests are being skipped here due to `*musl*` but I don't think that should prevent builds?

https://github.com/matrix-org/synapse/blob/c9b7e9735508bb148c6ad59c433d71e5b8b360ad/.github/workflows/release-artifacts.yml#L120-L125

@erikjohnston any ideas here?

**Comment by DMRobertson** [comment]
I guess cibuildwheel only builds what it can on a given platform. Would probably have to add a matrix entry to 

https://github.com/matrix-org/synapse/blob/c9b7e9735508bb148c6ad59c433d71e5b8b360ad/.github/workflows/release-artifacts.yml#L92-L104

and a step below that conditionally runs the rest under QEMU, like here:

https://github.com/matrix-org/synapse/blob/b8fa24b022df366495147b5ddce73c06ec9cbc3a/.github/workflows/docker.yml#L18-L22

**Comment by MichaIng** [comment]
Finally: #14212

That was a hassle with https://github.com/rust-lang/cargo/issues/10583.
- First I tried to pass `CARGO_NET_GIT_FETCH_WITH_CLI` it via [CIBW_ENVIRONMENT](https://cibuildwheel.readthedocs.io/en/stable/options/#environment) and was wondering why suddenly within the CIBW container the Rust compiler couldn't be found, event that Rust was definitely installed.
- In attempt to fix this, I tried to set [CIBW_BEFORE_ALL_LINUX](https://cibuildwheel.readthedocs.io/en/stable/options/#before-all) and wondered why since then really no Rust was installed anymore.
- Finally I recognised that these both variables, if not set, are internally set to install Rust (via `CIBW_BEFORE_ALL`) and to add Rust to `PATH` (via `CIBW_ENVIRONMENT`). Setting any of both overrides the default completely, there is no way to only append to the default (AFAIK).
- So the only way to pass `CARGO_NET_GIT_FETCH_WITH_CLI` without breaking or needing to manually add Rust related steps and variables, is `CIBW_ENVIRONMENT_PASS_LINUX`, which has no internal default.
