### ISSUE TITLE
Complement `can_paginate_after_getting_remote_event_from_timestamp_to_event_endpoint` is flakey(?)

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#13944]
https://github.com/matrix-org/synapse/actions/runs/3149623842/jobs/5121449357#step:5:5805

```
❌ TestJumpToDateEndpoint (14.08s)
❌ TestJumpToDateEndpoint/parallel (4.03s)
❌ TestJumpToDateEndpoint/parallel/federation (0s)
❌ TestJumpToDateEndpoint/parallel/federation/can_paginate_after_getting_remote_event_from_timestamp_to_event_endpoint (1.54s)
      msc3030_test.go:195: SendEventSynced waiting for event ID $aEEhbyDijeJ586WpiJCNmpxF41yCQ5Sw0Hd2-0HkpRw
      msc3030_test.go:195: SendEventSynced waiting for event ID $NP6-oU7mIFVyhtKfGvfrEQX949hQX-T-gvuauG6eurU
      msc3030_test.go:200: CSAPI.MustDoFunc response return non-2xx code: 403 Forbidden - body: {"errcode":"M_FORBIDDEN","error":"You don't have permission to access that event."}
```

Not sure if this is related to @MadLittleMods' work?

**Comment by MadLittleMods** [comment]
It looks like this might be related to https://github.com/matrix-org/synapse/issues/13444 given we're seeing this log line `Unexpectedly did not have cached prev group for $aEEhbyDijeJ586WpiJCNmpxF41yCQ5Sw0Hd2-0HkpRw` for the event that `/context` is failing to get.

```
2022-09-29T08:23:25.7599143Z synapse_main | 2022-09-29 08:21:08,284 - synapse.federation.sender - 453 - INFO - process_event_queue_for_federation-3 - Unexpectedly did not have cached prev group for $aEEhbyDijeJ586WpiJCNmpxF41yCQ5Sw0Hd2-0HkpRw
```

**Comment by MadLittleMods** [comment]
Sleuthing the server logs on the CI failure, it looks like `hs2:/timestamp_to_event` found `$NP6-oU7mIFVyhtKfGvfrEQX949hQX-T-gvuauG6eurU` as an `outlier` event locally. Then when we went and asked for it via `/context`, since it's an `outlier`, it was filtered out of the results -> `You don't have permission to access that event.`

This is reproducible when `sync_partial_state` races and persists `$NP6-oU7mIFVyhtKfGvfrEQX949hQX-T-gvuauG6eurU` as an `outlier` before we evaluate `get_event_for_timestamp(...)`. To consistently reproduce locally, just add a delay at the [start of `get_event_for_timestamp(...)`](https://github.com/matrix-org/synapse/blob/cb20b885cb4bd1648581dd043a184d86fc8c7a00/synapse/handlers/room.py#L1470-L1496) so it always runs after `sync_partial_state` completes.

```py
# TODO: Make sure to assign `self.hs = hs` above
from twisted.internet import task as twisted_task
d = twisted_task.deferLater(self.hs.get_reactor(), 3.5)
await d
```

In a run where it passes, on `hs2`, `get_event_for_timestamp(...)` finds a different event locally which is next to a gap and we request from a closer one from `hs1` which gets backfilled. And since the backfilled event is not an `outlier`, it's returned as expected during `/context`.

---

It looks like we also need to backfill the locally found event if it's an `outlier`.
