### ISSUE TITLE
Make Admin Room

### ISSUE THREAD

**Issue by belascoain** [matrix-org/synapse#13946]
Hi

In some rooms, the user admin was deleted. Now I want to add a new admin in these rooms. I my Matrix server isn't enable API and I want to do this in synapse database.

Do you know in what table can I do these changes?

Thanks

Regards

**Comment by DMRobertson** [comment]
A few things here.

It's not possible to make a user in a room an admin from the database alone. (The homeserver has to create an "event" and cryptographically sign it, then distribute the event to other homeservers.)

It is not possible (at the protocol level) to give a user in a room a power level bigger than your own. E.g. if all the room admins have left or been deleted, moderators can only create other moderators).

In general you should **not** be manually making edits to the Synapse database at all. Doing so without knowing what you're doing is highly unsafe and we cannot support anyone who has done so without our guidance.

With that said, it may be possible to do something depending on a few things. Can you answer the following?

- Is the admin who got deleted a user on your homeserver?
- How were they deleted?
- What are the current `m.room.power_levels` events in your room? If you're using Element-web as a client, you can find this by typing `/devtools` in the room.

**Comment by belascoain** [comment]
Good morning.

We do a few changes over synapse database in our own server (create users, change password, deactivated users, ...). The admin user in this room was deactivated laste year. I've could change the creator of this rooms but it isn't enough.

I've thought that I could activated the admin user in this room again, change the password, enter in the room, and make admin to another user. Is it possible?

Regards

**Comment by DMRobertson** [comment]
To repeat:

> you should **not** be manually making edits to the Synapse database at all.

Synapse maintains in-application caches of DB queries which need to be invalidated when the corresponding database entries change. This is particularly important for worker deployments, but affects even a monolith deployment.

### **Please** use the [Admin API](https://matrix-org.github.io/synapse/latest/usage/administration/admin_api/index.html) instead of editing the database.

> I've thought that I could activated the admin user in this room again, change the password, enter in the room, and make admin to another user. Is it possible?

- To reactivate the admin user, you need to use [Create or modify account](https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#create-or-modify-account) with `"enabled": true` in order to log in as that user. You can also set a new password with that API.
- If the admin user is not a member of the room, you will need someone in the room to reinvite them.
- They should still have their old power level (it sounds like there is no-one who could have demoted them anyway).

<details>
<summary>Aside</summary>
> I've could change the creator of this rooms but it isn't enough.

This is not possible, not least because the creator of the room is defined in an [`m.room.create`](https://spec.matrix.org/v1.4/client-server-api/#mroomcreate) event whose contents are cryptograpically signed.
</details>

**Comment by DMRobertson** [comment]
The above comment should get you going. If you have trouble using the admin API, please ask in the [Synapse Admins room](https://matrix.to/#/#synapse:matrix.org) for assistance. You might also be able to use the community project https://github.com/Awesome-Technologies/synapse-admin to help, but this is not an official part of the Synapse project.
