### ISSUE TITLE
how to config adfs in synapse home server version 1.67

### ISSUE THREAD

**Issue by RoninAngle1** [matrix-org/synapse#14005]
Hi , I have problem with single sign on method.

we use local "ADFS" as single sign on server which every service should be connected to.

how should I config my home server with it ? should I use oidc or saml2 .etc ?

please let me know. thank you

**Comment by DMRobertson** [comment]
We're using Github's issue tracker for bug reports and feature requests. For this kind of support request, please ask in the [Synapse Admins](https://matrix.to/#/#synapse:matrix.org) room. If your homeserver is inoperable at the moment, you can sign up for an account on the Matrix.org homeserver in order to reach the support room.

**Comment by richvdh** [comment]
(apparently ADFS is **not** the [advanced disk filing system](https://en.wikipedia.org/wiki/Advanced_Disc_Filing_System))

https://github.com/matrix-org/synapse/issues/5130#issuecomment-514999595 has some notes which may be helpful, though if ADFS supports oauth2 I would strongly recommend using it rather than saml2.

But as @DMRobertson says we cannot provide support here.

**Comment by RoninAngle1** [comment]
@richvdh @DMRobertson thank you for your response I really appreciate it. 
@richvdh I should say that our ADFS (Active Directory Federation Service) supports oauth2 , I have tested it myself and I have joined the synapse admins channel and asked the exact same question there too, BUT NO ONE (and by the word "NO ONE" I mean it) ANSWERS ME. I have been stuck in it for a week and I need help.
I thank you a lot, at least you answered me.
