### ISSUE TITLE
Add Admin API endpoint that allows server admins to set the power level of a user in a room

### ISSUE THREAD

**Issue by Arnei** [matrix-org/synapse#14388]
The [Make room admin](https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/rooms.md#make-room-admin-api) API allows a server admin to grant another user in the room the highest power level in that room. Unfortunately, this does not help if the server admin tries to salvage a room where no user has an admin power level anymore. For these situations, it would be nice to either change the "Make room admin" endpoint or create a new endpoint that allows the server admin to:
- Set the power level of a user in in a room to an arbitrary value. The idea here is that the server admin can figure out the appropriate power level themselves and then grant them to the user.
- Set the power level of a user to 100. As this is the highest power level, it should grant the user all permissions. Easier to use than the above suggestion (don't need to know about power levels), at the expense of making the user possibly more powerful than other room admins.

I do not know if this is technically possible or feasible, I just think it would be nice to provide server admins with a straightforward way to salvage rooms that somehow lost all of their admins.

Related issue: https://github.com/matrix-org/synapse/issues/2372

Adressing some of the comments in the related issue:
- It is claimed that this is a `Matrix Protocol` issue. The linked matrix spec issue however seems to focus on room owners/creators and what they should be able to do, not on an endpoint for server admins, so I don't quite see how it relates.
- Other possible solutions for salvaging adminless rooms are suggested. However, to me they don't seem straightforward.

**Comment by squahtx** [comment]
related: #14387

As mentioned in #14387, this isn't possible with the way Matrix is designed for federation. The homeserver that created a room doesn't have any special ownership over it and can't promote users at a whim, because other homeservers in the room would reject the promotions. To allow a room to be recovered, we have to update the Matrix protocol so that other homeservers will accept the new admin.

There's discussion about this in https://github.com/matrix-org/matrix-spec/issues/67 and https://github.com/matrix-org/matrix-spec/issues/165.
