### ISSUE TITLE
matrix web manage

### ISSUE THREAD

**Issue by Ran-Xing** [matrix-org/synapse#14457]
Does matrix have a web visualization page to configure some parameters?

May I ask whether matrix can delete/register users and delete messages through web visualization

Is it supported? Burn after reading

**Comment by DMRobertson** [comment]
> Does matrix have a web visualization page to configure some parameters?
> May I ask whether matrix can delete/register users and delete messages through web visualization

Depends on your choice of server. Synapse does not provide this, but there is a community project https://github.com/Awesome-Technologies/synapse-admin which might be what you want.

> Is it supported? Burn after reading

Not currently.

----

We're using Github's issue tracker for bug reports and feature requests. For other questions like this, please ask in the [Synapse Admins](https://matrix.to/#/#synapse:matrix.org) room. If your homeserver is inoperable at the moment, you can sign up for an account on the Matrix.org homeserver in order to reach the support room.
