### ISSUE TITLE
Allow GDPR compliance in push notifications

### ISSUE THREAD

**Issue by Luzifer** [matrix-org/synapse#14569]
> As a server administrator running a Synapse instance in the EU I need to comply to EU regulations which for example includes GDPR. Therefore sending the name of my users to - for example - Apple or Google servers is not acceptable as it transmits personal data.

In order to solve this a push notification flag would be useful to prevent **any** information (message content, user-id (`@firstname:my.server`), user name (`Firstname Lastname`)) to other servers. Purely sending IDs not being able to be connected to users or identity information without having a login to `my.server` **should** allow full compliance to regulations.

**Comment by babolivier** [comment]
Hi @Luzifer, and thanks for your interest in Matrix!

This is more of a client issue than a server one. When registering a pusher (which is the term Matrix uses to refer to the process sending the push notification to the push gateway), the client can set the `format` to be `event_id_only` (see [the documentation for creating pushers](https://spec.matrix.org/v1.5/client-server-api/#post_matrixclientv3pushersset)). When this is done, the only data that is sent to the push provider (e.g. Apple or Google) is:

* the ID of the event that triggered the notification
* the ID of the room that event was sent in

No further information about this event (or who sent it) is included in the payload.

I can understand if you argue that not doing so is a confusing default. I believe the reason this was chosen was because defaulting to `event_id_only` requires extra work on the client which then needs to pull additional data about the user from the server, which might be expensive. Regardless, this should be a discussion for https://github.com/matrix-org/matrix-spec (or [#matrix-spec](https://matrix.to/#/#matrix-spec:matrix.org)), since Synapse implements the Matrix specification but does not define it.

If your client does not already set the `format` of pushers to `event_id_only`, I suggest opening an issue to the repository for said client.

**Comment by Luzifer** [comment]
IMHO this is not a client issue. As an administrator I cannot expect all users to set this setting and especially I cannot control they are doing so. As soon as one user is not setting this themselves for whatever reason, my server - not that user or their client - will be sending personal data to third-parties which is a GDPR violation.

Therefore to prevent this I need a way to enforce no personal data to be sent which is only possible on server side.

As we already do have the option to enforce the body not to be sent it would be a good fit to add `push.no_personal_data` and therefore force the notification not to contain personal data.

**Comment by babolivier** [comment]
In this case, again, this is a conversation you want to have around the Matrix spec and not one specific implementation of it (Synapse). The reason any change in this behaviour needs to happen in the Matrix specification is that a server sending push data that is different from what clients expect can lead to undefined behaviours and bugs in said clients - and the spec specifically exists to provide a common ground of understanding between clients and servers.
