### ISSUE TITLE
`ip_range_blacklist` documentation conflict

### ISSUE THREAD

**Issue by sdfg2** [matrix-org/synapse#14709]
### Description

Configured synapse using the config_sample.yml documentation, `ip_range_blacklist` was *not* set in my homeserver.yaml, as I didn't want to restrict access to local ranged. 

https://github.com/matrix-org/synapse/blob/f4deee7d8461c14fc4dbdab6a76ee1b85c64e54f/docs/sample_config.yaml#L645-L647

```
# Prevent outgoing requests from being sent to the following blacklisted IP address
# CIDR ranges. If this option is not specified, or specified with an empty list,
# no IP range blacklist will be enforced.
```

However, I still had problems getting through to my push server on a private address.

After many hours of troubleshooting this, and people kindly going through double checking my configuration, someone suggested adding the private address to `ip_range_whitelist` and linked me to the official documentation website.  That worked, and looking through the documentation I found:

https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#ip_range_blacklist

```
This option prevents outgoing requests from being sent to the specified blacklisted IP address CIDR ranges. If this option is not specified then it defaults to private IP address ranges (see the example below).
```

This is in conflict with the documentation in the sample file.

### Steps to reproduce

- go https://github.com/matrix-org/synapse/blob/f4deee7d8461c14fc4dbdab6a76ee1b85c64e54f/docs/sample_config.yaml#L645-L647
- read the documentation
- go https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#ip_range_blacklist
- read the documentation
- see that the documentation conflicts

### Homeserver

n/a

### Synapse Version

n/a

### Installation Method

Other (please mention below)

### Database

n/a

### Workers

I don't know

### Platform

n/a

### Relevant log output

```shell
n/a
```

**Comment by clokep** [comment]
The [given link](https://github.com/matrix-org/synapse/blob/f4deee7d8461c14fc4dbdab6a76ee1b85c64e54f/docs/sample_config.yaml#L645-L647) is from a commit from ~2 years ago, but the [documentation is up-to-date](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#ip_range_blacklist). This sounds to me like we already found and corrected this mistake?

I'm unsure where you found the link to the sample config, but it likely references configuration that isn't even possible anymore (and is missing many new configurable options).

I'm going to close this since the official documentation is up-to-date with the implementation.
