### ISSUE TITLE
Messages in world_readable rooms are not visible to parted users from initialSync

### ISSUE THREAD

**Issue by progval** [matrix-org/synapse#14737]
### Description

I joined+left `#forgejo-chat:matrix.org` twice from my account `@pinkie:matrix.org`, then sent two messages from a remote account, `@val:e2e.zone`.

The second message appeared in Element, but not the first. After reloading the page, neither was visible. However, both messages are visible on https://view.matrix.org/room/!qjPHwFPdxhpLkXMkyP:matrix.org/ (event ids: `$Fr8Iuzs2L5c17B5jk-_Hrup1Jzq52_SZ9TqM000dvZM` and `$yJevqQixexqD7KlJrj8ObiRScOrfcfhzpGyY9cdgnpo`)

I see Element queried `https://matrix-client.matrix.org/_matrix/client/r0/rooms/!qjPHwFPdxhpLkXMkyP%3Amatrix.org/initialSync?limit=20` twice, which returned everything up to my last `leave` event.

### Steps to reproduce

Untested, but I assume:

1. join+leave a room from Element (possibly twice)
2. have someone send a message (possibly from another homeserver)
3. check the message is indeed displayed
4. reload Element

### Homeserver

matrix.org

### Synapse Version

1.74.0 (b=matrix-org-hotfixes,5a1b56b9b0)

### Installation Method

I don't know

### Database

postgresql

### Workers

I don't know

### Platform

n/a

### Relevant log output

```shell
n/a
```

**Comment by DMRobertson** [comment]
Note that this endpoint is deprecated: https://spec.matrix.org/v1.5/client-server-api/#get_matrixclientv3roomsroomidinitialsync

> 3. check the message is indeed displayed

From which user: that in step 1? If so, why would they want to see messages in a room they've left? I don't understand the use-case here.

This seems to be intentional behaviour of a per-room initialSync, per the docstring here: https://github.com/matrix-org/synapse/blob/126a15794c95002560709283640ad412636b29b8/synapse/handlers/initial_sync.py#L282-L284

I think we consider this a WONTFIX.

**Comment by progval** [comment]
> From which user: that in step 1? If so, why would they want to see messages in a room they've left?

Yes

> I don't understand the use-case here.

The same use-cases as viewing the history of a room they never joined at all.

> This seems to be intentional behaviour of a per-room initialSync, per the docstring here: 

What was the rationale for this? It seems surprising to me that joining and immediately leaving (which can happen if someone joined by accident) would remove access to new history
