### ISSUE TITLE
Add `Synapse-Trace-Id` to `access-control-allow-headers` header

### ISSUE THREAD

**Issue by bwindels** [matrix-org/synapse#14951]
### Description

The `Synapse-Trace-Id` response header added in https://github.com/matrix-org/synapse/issues/9480 needs to be [whitelisted](https://github.com/matrix-org/synapse/blob/v1.75.0/synapse/http/server.py#L903) as well so web clients using CORS can read it.

### Steps to reproduce

one a jaeger enabled synapse, make a request that is traced by jaeger.

### Homeserver

matrix.org

### Synapse Version

1.76.0rc1

### Installation Method

I don't know

### Database

don't know

### Workers

I don't know

### Platform

don't know

### Relevant log output

```shell
don't have any
```

**Comment by H-Shay** [comment]
cross-posting from #14974 for visibility:

@bwindels We're a bit confused about which header Synapse-Trace-Id needs to be added to. Surely it's [Access-Control-Expose-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers), so that clients can read the trace id?
