### ISSUE TITLE
SMS support

### ISSUE THREAD

**Issue by MomentQYC** [matrix-org/synapse#15056]
**Description:**

What are the available alternatives after the cancellation of the Matix official SMS support?

**Comment by MatMaul** [comment]
I guess you are talking about validating your phone number when trying to associate a phone number to your Matrix ID.

This is unfortunately disabled in our config of [sydent](https://github.com/matrix-org/sydent) for now, because of some abuse of it.

There is unfortunately no way around that for now, and we can't really commit to a date about when we will be able to open that again.

**Comment by MomentQYC** [comment]
> I guess you are talking about validating your phone number when trying to associate a phone number to your Matrix ID.
> 
> This is unfortunately disabled in our config of sydent for now, because of some abuse of it.
> 
> There is unfortunately no way around that for now, and we can't really commit to a date about when we will be able to open that again.

If possible, I think the developers can improve the SMS-related features of open source Sydent to support more providers, etc.

**Comment by MatMaul** [comment]
That could be done, but doesn't solve the underlying issue of abuse in our deployment. I am going to close this issue, feel free to subscribe to https://github.com/matrix-org/sydent/issues/49 which is the Sydent issue regarding SMS providers.

**Comment by richvdh** [comment]
Related: https://github.com/vector-im/element-meta/issues/478, https://github.com/matrix-org/synapse/issues/5881
