### ISSUE TITLE
Porting from SQLITE3 to postgres

### ISSUE THREAD

**Issue by dr-roshyara** [matrix-org/synapse#15066]
Everytime I start synapse_port_db command, I got the following error! 
```
Pending background updates exist in the SQLite3 database. 
Please start Synapse again and wait until every update has finished before running this script.

```
Environment  
- sqlite3 
- psql 13.5 
-homeserver.yaml set for postgres 
-Matrix
Is it a bug issue or my problem . Could you please write ?

**Comment by DMRobertson** [comment]
You need to

- start Synapse,
- let it finish processing any background updates,
- then stop Synapse,
- then run the synapse_port_db script.

To see the status of background updates, you should
- search through Synapse's logs,
- and/or use the [Admin API](https://matrix-org.github.io/synapse/latest/usage/administration/admin_api/background_updates.html#status) to query the status of background updates.

For any other questions, please ask in the [Synapse Admins](https://matrix.to/#/#synapse:matrix.org) room. If your homeserver is inoperable at the moment, you can sign up for an account on the Matrix.org homeserver in order to reach the support room.

**Comment by DMRobertson** [comment]
Run Synapse with SQLite to complete the background updates in the SQLite database. Once the `synapse_port_db` completes you should change Synapse to run against postgres.

If you have not already done so, you should read https://matrix-org.github.io/synapse/latest/postgres.html#porting-from-sqlite for more details.
