### ISSUE TITLE
Remove Room admin from database

### ISSUE THREAD

**Issue by sae13** [matrix-org/synapse#15132]
hey hi 
I need to remove some admin from a room 
how i can do that from database? my db is PostgreSQL
in which table we save users role in room

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/issues/11601 is a similar issue.

If the admin does not belong to your homeserver, it is impossible to demote them due to the design of Matrix. See https://github.com/matrix-org/matrix-spec/issues/67
If the admin _does_ belong to your homeserver, you can:

- use the [admin API](https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html?highlight=access%20token#login-as-a-user) to generate an access token with which to impersonate them
- then manually make a CSAPI request to lower their power level using that access token

at which point a different admin can kick or ban the unwanted admin from the room.

Note that we're using Github's issue tracker for bug reports and feature requests. For this kind of support request, please ask in the [Synapse Admins](https://matrix.to/#/#synapse:matrix.org) room. If your homeserver is inoperable at the moment, you can sign up for an account on the Matrix.org homeserver in order to reach the support room.

Additionally, a disclaimer: you should **NOT** manually make edits to the Synapse database at all. Doing so without knowing what you're doing is _highly unsafe_ and we cannot support anyone who has done so without our guidance.

**Comment by noriakisana** [comment]
Hi @DMRobertson unfortunally i cant find the required CSAPI request to demote theirself in the docs. where can i find it? :D

**Comment by DMRobertson** [comment]
You want to PUT new power levels using https://spec.matrix.org/v1.7/client-server-api/#put_matrixclientv3roomsroomidstateeventtypestatekey

To see the existing power levels, use the same endpoint with GET: https://spec.matrix.org/v1.7/client-server-api/#get_matrixclientv3roomsroomidstateeventtypestatekey

**Comment by noriakisana** [comment]
Thanks :D
