### ISSUE TITLE
push service

### ISSUE THREAD

**Issue by ldm0330** [matrix-org/synapse#15399]
Please tell me how to configure Google push service in homeserver.yaml. Can you provide some examples, I tried to use the official document configuration, but I can't push the app when it is switched to the background

Instead, please join [`#synapse:matrix.org`](https://matrix.to/#/#synapse:matrix.org)
(from a matrix.org account if necessary), and ask there.

**Comment by DMRobertson** [comment]
We're using Github's issue tracker for bug reports and feature requests. For support requests relating to Synapse itself, please ask in the [Synapse Admins](https://matrix.to/#/#synapse:matrix.org) room. If your homeserver is inoperable at the moment, you can sign up for an account on the Matrix.org homeserver in order to reach the support room.

> I can't push the app when it is switched to the background

You should also ask for support from the app itself; Synapse doesn't know when your app is backgrounded.
