### ISSUE TITLE
Login API presents `m.login.application_service` if no application service is configured

### ISSUE THREAD

**Issue by dklimpel** [matrix-org/synapse#15401]
### Description

Login API `https://matrix-client.matrix.org/_matrix/client/v3/login` presents login via `m.login.application_service` also if no [`app_service_config_files`](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#app_service_config_files) is configured.

### Steps to reproduce

- setup a new homeserver
- request `/_matrix/client/v3/login`

```json
{
   "flows":[
      {
         "type":"m.login.password"
      },
      {
         "type":"m.login.application_service"
      }
   ]
}
```

### Homeserver

another

### Synapse Version

1.78.0

### Installation Method

Docker (matrixdotorg/synapse)

### Database

PostgreSQL

### Workers

Multiple workers

### Platform

K8s

### Relevant log output

```shell
None
```

### Anything else that would be useful to know?

Probably there could be a check here for app services:

https://github.com/matrix-org/synapse/blob/98fd558382226b347d78e5f6e6782c6e74c25e69/synapse/rest/client/login.py#L170

**Comment by erikjohnston** [comment]
If we change this then we'll leak whether the HS has any ASes enabled, and I don't know if we care about that.

Certainly I don't think this causes any issues?

**Comment by dklimpel** [comment]
I guess it's a leftover from the time when AS didn't have to be configured explicitly in homeserver.yaml.
If removing `"type":"m.login.application_service"` "leak" something, that is IMHO a bit of security by obsurity.

And wouldn't the argumentation be suitable for all login methods? Shouldn't all methods be included there?
That is actually the purpose of the request from [`GET _matrix/client/v3/login`](https://spec.matrix.org/v1.6/client-server-api/#get_matrixclientv3login).

> Gets the homeserver’s supported login types to authenticate users. Clients should pick one of these and supply it as the type when logging in.

**Comment by clokep** [comment]
> I guess it's a leftover from the time when AS didn't have to be configured explicitly in homeserver.yaml.

It is fairly new: #11335

**Comment by reivilibre** [comment]
I think I'd be in favour of keeping it there, the same as how you wouldn't expect the password login method to disappear if there were no users registered with a password.

Since the `/login` API can be probed by any unauthenticated party, it seems like it would be better not to divulge the presence of an AS or not — sure it's only 'one bit of information' but it's one bit more than needed to be divulged. (As an extreme case, you might imagine that some homeservers start blocking other homeservers if they have application services configured.)
The login method is not user-interactive anyway so I can't see any UI/user-facing harm in leaving it there. (This is the main reason I would expect options to be added/removed from this response normally — you don't want to show a password box in the UI if you have to use SSO to log in, for example.)

**Comment by dklimpel** [comment]
> As an extreme case, you might imagine that some homeservers start blocking other homeservers if they have application services configured.

Wouldn't that be a legitimate decision of every server operator? For this there are various methods such as moderation tools, ban lists, firewalls, etc.. There are also other reasons for such decision: (spam) bots, open registration, geo IP, etc.

**Comment by dklimpel** [comment]
I'm closing it because we don't have a common opinion and that's not a big issue.
