### ISSUE TITLE
User Admin API: Ability to exclude user types

### ISSUE THREAD

**Issue by weeman1337** [matrix-org/synapse#15720]
**Story**

As an admin I want to be able to exclude user types when fetching [the user list from the admin API](https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#list-accounts),
so that I can exclude bot or service users.

**Proposal**

Add a new query param  `not_user_types` to [`GET /_synapse/admin/v2/users`](https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#list-accounts): user type to exclude. Can be provided multiple times. Returns only users, that do not match any of them. "empty string" should be possible to exclude users without a type.

The design is similar to https://spec.matrix.org/v1.7/client-server-api/#get_matrixclientv3useruseridfilterfilterid

**Comment by weeman1337** [comment]
I am happy to contribute a pull request.

**Comment by erikjohnston** [comment]
I think this would be fine, so long as we ensure:

1. This matches how we do filtering elsewhere in the (admin) API
2. Check what the performance of such APIs are like, i.e. we might need to add an index.

**Comment by Bhupi2508** [comment]
Hi @weeman1337 , @erikjohnston , @H-Shay.

#### I'm interested in contributing to the repository. Could you provide more details about the issue, specifically :

1. How does the current user list fetching work?
2. What is the expected behavior with the new query parameters, 'user_types' and 'without_user_types'?
3. Are there any specific implementation guidelines or considerations?

**Comment by weeman1337** [comment]
@Bhupi2508 thank you for your offer. Unfortunately I am already working on it.
