### ISSUE TITLE
sending message issue with a java client

### ISSUE THREAD

**Issue by crazysvn** [matrix-org/synapse#16086]
I'm trying to use a java client named matrix-communication-client to send message, but always get an 403, any ideas? looks like it login successfully, the roomId is also correct, I think.
![image](https://github.com/matrix-org/synapse/assets/26742593/500226ea-230b-4a2c-aebe-cd18a9ad93ae)

**Comment by DMRobertson** [comment]
We're using Github's issue tracker for bug reports and feature requests. For this kind of support request, please ask in the [Synapse Admins](https://matrix.to/#/#synapse:matrix.org) room. If your homeserver is inoperable at the moment, you can sign up for an account on the Matrix.org homeserver in order to reach the support room.

(At the very least you should look at the response body and the server logs to see why there is a 403.)
