### ISSUE TITLE
reverse proxy in external host

### ISSUE THREAD

**Issue by oliverbs2381** [matrix-org/synapse#16163]
I have synapse and Element set up on the same server on an internal LAN and was trying to set up a reverse proxy on another  host with real ip.
The problem I have is that I can authenticate with a user but when I go to write messages to other users it gives me a sending error.
Doing an inspection of the page I have multiple errors with the following message:
Error sending room key request; will retry later. ConnectionError: fetch failed: NetworkError when attempting to fetch resource.

so my question is if it is possible configure a reverse proxy for synapse and element on another host, and How would I do it to avoid errors?

**Comment by DMRobertson** [comment]
We're using Github's issue tracker for bug reports and feature requests. For this kind of support request, please ask in the [Synapse Admins](https://matrix.to/#/#synapse:matrix.org) room. If your homeserver is inoperable at the moment, you can sign up for an account on the Matrix.org homeserver in order to reach the support room.

With that said, here are some brief tips for your situation:

> configure a reverse proxy for synapse and element on another host

This should be possible. See https://matrix-org.github.io/synapse/latest/reverse_proxy.html for advice.

One thing to check is that https://federationtester.matrix.org/ is able to reach your homeserver; you will also need to ensure that Synapse is able to reach other homeservers. 

> Doing an inspection of the page I have multiple errors with the following message:

Either Synapse's logs or your reverse proxy's logs will have more specific information to debug the problem.
