### ISSUE TITLE
Kill User Connections

### ISSUE THREAD

**Issue by belascoain** [matrix-org/synapse#16305]
Hi

I have one matrix's user that is a bot. Each time that somebody invokes it, bot create a new connection. Now, if I check database for this user I can see more than three hundred connections

How can I kill old connections?

Thanks

**Comment by DMRobertson** [comment]
> Each time that somebody invokes it, bot create a new connection.

The bot should either
- remember its access token between invocations, or
- logout after it has been invoked.

---

We're using Github's issue tracker for bug reports and feature requests. For additional support request, please ask in the [Synapse Admins](https://matrix.to/#/#synapse:matrix.org) room. If your homeserver is inoperable at the moment, you can sign up for an account on the Matrix.org homeserver in order to reach the support room.

**Comment by DMRobertson** [comment]
> How can I kill old connections?

Try using the admin API to [change its password](https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#create-or-modify-account) with `logout_devices=True`.
