### ISSUE TITLE
Email add error

### ISSUE THREAD

**Issue by Kitanit** [matrix-org/synapse#16407]
![image](https://github.com/matrix-org/synapse/assets/65107731/413e7756-0c87-4082-be0c-63d3334aea3e)

**Comment by Kitanit** [comment]
![image](https://github.com/matrix-org/synapse/assets/65107731/f49a0221-93b6-4bba-ac54-c0cefad37036)

**Comment by DMRobertson** [comment]
It looks like you need some kind of additional [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) configuration to allow web pages hosted by element.securetown.in.ua to make requests to matrix.fediland.in.ua.

Synapse should allow this by default:

https://github.com/matrix-org/synapse/blob/62a1a9be52f4bc79b112f9841ddb3d03b8efccba/synapse/http/server.py#L902

so I'm not sure what is going on here. Could your reverse proxy be removing this header? I suggest looking at the HTTP responses in your browser's debug tools for more hints.

----

Having said that: we're using Github's issue tracker for bug reports and feature requests. For this kind of support request, please ask in the [Synapse Admins](https://matrix.to/#/#synapse:matrix.org) room. If your homeserver is inoperable at the moment, you can sign up for an account on the Matrix.org homeserver in order to reach the support room.

Additionally:

* When filing issues, please include a sentence or two describing the problem, how to trigger it and what you've done to try and solve the problem so far. This context is very helpful for anyone trying to help.
* Please copy-and-paste configuration and logs as text so that people can search for it using e.g. `ctrl-f` and web search engines.
