### ISSUE TITLE
large file upload

### ISSUE THREAD

**Issue by guojinlong1** [matrix-org/synapse#16470]
"I am using Docker to run a local Synapse service, but I encounter errors when uploading files larger than 50MB. How should I configure it?"

**Comment by dklimpel** [comment]
Did you see the configuration guide?
https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#max_upload_size

**Comment by DMRobertson** [comment]
Dirk has pointed out the right config option.

We're using Github's issue tracker for bug reports and feature requests. For this kind of support request, please ask in the [Synapse Admins](https://matrix.to/#/#synapse:matrix.org) room. If your homeserver is inoperable at the moment, you can sign up for an account on the Matrix.org homeserver in order to reach the support room.
