### ISSUE TITLE
Matrix keeps restarting after changing to Postgresql

### ISSUE THREAD

**Issue by ParmacT** [matrix-org/synapse#16731]
I tried changing to postgresql to use bridges and after that matrix keeps restarting with this error message 
Dec 06 09:37:03 laptops python3[183534]:  Error in configuration:
Dec 06 09:37:03 laptops python3[183534]:   Unsupported database type 'postgresql'

My configuration for the database is
database:
  name: "psycopg2"
  args:
    user: "user"
    password: "pass"
    database: "matrix_db"
    host: "localhost"
    cp_min: 1
    cp_max: 5

What is wrong or what should i change?

**Comment by DMRobertson** [comment]
> Unsupported database type 'postgresql'

This suggests you have `name: postgresql` somewhere in your database config, but that doesn't match the config you provided. Please double check the configuration is being loaded correctly.

----

We're using Github's issue tracker for bug reports and feature requests. For this kind of support request, please ask in the [Synapse Admins](https://matrix.to/#/#synapse:matrix.org) room. If your homeserver is inoperable at the moment, you can sign up for an account on the Matrix.org homeserver in order to reach the support room.
