### ISSUE TITLE
add self-certificate on homeserver

### ISSUE THREAD

**Issue by SiNaPsEr0x** [matrix-org/synapse#1719]
riot client:

can I fix??? 

Can't connect to homeserver - please check your connectivity and ensure your homeserver's SSL certificate is trusted.

**Comment by jacklund** [comment]
I've got the same issue - running on OSX, tried importing the cert into the system keychain, still no luck.

**Comment by SiNaPsEr0x** [comment]
Yes in OS X this problem ... solutions???

**Comment by jacklund** [comment]
Okay, I figured it out.

The problem was twofold: 1) I didn't set up the certificate for trust, and 2) I didn't access the site using the domain in the certificate (I really think the docs should be updated on this point, when it tells you to access the home server as `localhost`).

To fix 1: `sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain my.domain.name.tls.crt` where `my.domain.name` is the domain name that you created the cert with when setting up configuration [here](https://github.com/matrix-org/synapse#configuring-synapse).

To fix 2: You'll need to add your domain name in `/etc/hosts` to point to localhost, with a line that looks like this: `127.0.0.1 localhost my.domain.name`. You'll probably want to remove `my.domain.name` from this entry after testing.

**Comment by SiNaPsEr0x** [comment]
Ok thanks but server is on debian ... and client connect to ssl port ... problem fix?

**Comment by SiNaPsEr0x** [comment]
the problem is that inside the Riot application you can not enter a local certified so if one creates a locally there is no way to authenticate it permanently

**Comment by jacklund** [comment]
If you're running Riot on OSX, you should be able to add the certificate using `add-trusted-cert` after copying it over from Debian to your OSX box.

**Comment by SiNaPsEr0x** [comment]
Is added!!!

**Comment by richvdh** [comment]
I don't really know what this bug means.
