### ISSUE TITLE
logging should put all errors in homeserver.log

### ISSUE THREAD

**Issue by sbts** [matrix-org/synapse#1781]
If the client can't be found synapse fails and reports 
> Could not find webclient

on the console.
However nothing is reported in homeserver.log except info messages, and they all appear to be normal and expected.

Specifically this occurs on the debian package 0.18.5-1 but I'd expect it to be a general issue.

The same problem also occurs if twisted can't listen on a port (eg: 443)
> twisted.internet.error.CannotListenError: Couldn't listen on any:443: [Errno 13] Permission denied.

Appears on the console, but nothing in the logs

**Comment by sbts** [comment]
When run from systemd it is possible to retrieve the console output from a service by running
```bash
journalctl -u matrix-synapse -b -e
```

**Comment by richvdh** [comment]
There are a few errors that happen while we're reading the configuration, which happens before we set up the logging. The solution to that is probably to configure the logger to send all logs to stdout and have journald manage the logs.

Related: https://github.com/matrix-org/synapse/issues/1539#issuecomment-435084421

**Comment by richvdh** [comment]
It's worth noting that both the cases in the original report are now fixed:
 * synapse does not expose a web client by default, but if it is enabled and the webclient cannot be found, a warning is written to the logs (fixed in #4290)
 * if we cannot bind to a port, we write an error to the logs *and* the console (fixed in #9059), before exiting.

There still remains a class of warnings that are written before the logging is set up - typically these are deprecation warnings etc. We *could* stack these up until the logging is configured, and write copies to the logs as well/instead, but I'm not entirely sure this is necessary.

**Comment by richvdh** [comment]
I think this is probably as fixed as it's going to be. Logging errors that happen before the logger is set up is hard.
