### ISSUE TITLE
Fix backtrace logging

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#1805]
#1778 explains that we're not logging full backtraces properly due to not using the twisted logger

**Comment by richvdh** [comment]
Turns out it's not necessary to use the twisted logger to fix backtraces; instead we can recover the original Failure in the same way that the twisted logger does (which is by calling argless `failure.Failure()`, which fishes the old failure out of the stack) and then use that to log a stacktrace.

PR #2705 does this in the place we most frequently get bitten by it. There will be others, but we can probably address them as we find them.
