### ISSUE TITLE
Extend purge APIs to support forward-looking and range requests instead of just history

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#2144]
It would be nice to be able to delete all media after X instead of just before X. An extension to this would be all media between X and Y. Currently the documentation claims to only accept before X.

Extending this same request to the history purge API would be appreciated, although slightly less useful.

An example case where this would be useful is when a remote server has intentionally removed some media due to whatever circumstances, and as an administrator you'd like to remove that media from your server as well. You may not know all of the affected MXC URLs, but may have an estimated timespan for which you can selectively delete media from all sources.

**Comment by reivilibre** [comment]
This could be done with external tools using the admin API, but it's not immediately obvious that this would be a worthwhile addition to the admin API as a dedicated function given these additions don't seem to make much sense from a general-purpose data clean-up (the reason 'earlier than ...' may be useful is because old media is generally not accessed).

Will close this; if someone feels strongly about needing this then it could be reopened but I expect we would only take this feature if a PR was sent in.

**Comment by turt2live** [comment]
This would count as T&S tooling these days, ftr. It may happen in a few years naturally, but there's zero plan I'm aware of to fight for it soon.

I would suggest reopening so others can be made aware of the feature still being wanted.
