### ISSUE TITLE
Missing state events on the rooms I create

### ISSUE THREAD

**Issue by mujx** [matrix-org/synapse#2152]
I use the following query to sync with matrix.org

```json
sync?full_state=true&set_presence=online&filter={"presence":{"limit":0},"room":{"ephemeral":{"limit":0},"timeline":{"limit":70}}}
```
but I receive an empty `state` array on the rooms which I am the creator. 

If I remove the timeline filter like so

```json
sync?full_state=true&set_presence=online&filter={"presence":{"limit":0},"room":{"ephemeral":{"limit":0}}}
```
I receive all the `state` arrays as expected. 

Is this the expected behavior? The spec states that if `full_state: true` all the state events will be returned. Also it seems really unintuitive that a timeline filter will affected the state.

**Comment by mujx** [comment]
I think I found the problem here. Now that the room has more than `70` events (which is the number used in the filter) the state array is showing up properly even if I use the timeline filter. 

This can probably be resolved by including events up to the limit when there aren't enough events.

**Comment by erikjohnston** [comment]
The `state` section describes the the state at the start of the timeline range, i.e. it will be empty the vast majority of the time except:

- on an initial sync, where the state doesn't appear in the timeline section
- when a timeline section has been limited and there were state updates since the previous sync

**Comment by ara4n** [comment]
ftr, the reason that state describes the state at the beginning of the timeline segment rather than the end is to make it easier for client implementers to forwards-propagate state (member names, avatars etc) as they calculate the timeline to be shown.  Otherwise you have to do a weird backwards-and-then-forwards again traverse through the timeline in order to populate it up; so to make it easier we get the server to do the backwards-traverse for you.

https://matrix.org/jira/browse/SPEC-254 has the gory details.

**Comment by ara4n** [comment]
@mujx btw input on https://github.com/matrix-org/matrix-doc/issues/642 would be appreciated if we can avoid further generations of matrix client developers being bitten by this :)

**Comment by erikjohnston** [comment]
> ftr, the reason that state describes the state at the beginning of the timeline segment rather than the end is to make it easier for client implementers to forwards-propagate state (member names, avatars etc) as they calculate the timeline to be shown. Otherwise you have to do a weird backwards-and-then-forwards again traverse through the timeline in order to populate it up; so to make it easier we get the server to do the backwards-traverse for you.

Though you still need to have this logic for when you paginate  backwards

**Comment by mujx** [comment]
Thanks for your comments, things are clear now. I should have read the spec more carefully tho, as it clearly explains my situtation.
