### ISSUE TITLE
Can't login to rooms not on my server

### ISSUE THREAD

**Issue by mray** [matrix-org/synapse#2169]
Synapse running on [freedombox](https://github.com/freedombox/) gives me this error:

 `#matrix:matrix.org is not accessible at this time`

whenever trying to join a room that is not on my server. 
What could be the problem?

**Comment by richvdh** [comment]
Have you set up federation correctly (see https://github.com/matrix-org/synapse/blob/master/README.rst#id6) ?

otherwise look for errors in your homeserver log

**Comment by richvdh** [comment]
As per https://github.com/freedombox/Plinth/issues/822, it sounds like the underlying problem here is a failure to configure federation. Nevertheless it reflects the importance of making setting up federation less cryptic (https://github.com/matrix-org/synapse/issues/1576).

Also, there seems to be a bug in synapse in that it isn't sending the right thing back when there's a timeout talking to the remote server (https://github.com/matrix-org/synapse/issues/2179).

**Comment by mray** [comment]
Seems like the proper port forwarding was the culprit.
