### ISSUE TITLE
unit tests fail with TypeError (frozendict is not JSON serializable) in Fedora Rawhide

### ISSUE THREAD

**Issue by jeremycline** [matrix-org/synapse#2351]
Hey all,

I'm the package maintainer for Synapse in Fedora. When trying to update to the latest version in Rawhide, I encountered some test failures. From the [full build log](https://kojipkgs.fedoraproject.org//work/tasks/1337/20441337/build.log):
```
[ERROR]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1185, in _inlineCallbacks
    result = g.send(result)
  File "/builddir/build/BUILD/synapse-0.22.1/synapse/handlers/message.py", line 506, in handle_new_client_event
    dump = ujson.dumps(event.content)
exceptions.TypeError: <frozendict {'creator': '@some_other_guy:red'}> is not JSON serializable
tests.rest.client.v1.test_rooms.RoomsMemberListTestCase.test_get_member_list_mixed_memberships
tests.rest.client.v1.test_rooms.RoomsMemberListTestCase.test_get_member_list_no_permission
```

All the tests are failing from the same spot. It looks like https://github.com/matrix-org/synapse/commit/fcf01dd88e738e5745c17c7740e0d72b8bbbcb66 introduced the change.

**Comment by ignatenkobrain** [comment]
We've had conversation on IRC with @jeremycline and it turns out that in Fedora we have ujson of snapshot 2.0... And it seems commit https://github.com/esnme/ultrajson/commit/53f85b1bd6e4f27a3e4cdc605518c48a6c7e7e9e breaks thing... So just casting frozendict to dict should do the trick when serializing / deserializing.
