### ISSUE TITLE
Recover room admin where it has been lost

### ISSUE THREAD

**Issue by bobobo1618** [matrix-org/synapse#2372]
So I got in an incredibly annoying situation:

- I'm admin or moderator of a room (I forget)
- I add a moderator to a room
- The moderator kicks and bans me by accident, then unbans me and reinvites me
- Now nobody in the room has the permissions necessary to add/remove moderators

How can I resolve this?

**Comment by bobobo1618** [comment]
I eventually figured out an (extremely hacky) workaround:
- Open `synapse/event_auth.py`
- Add `return True` on the line after `def _can_send_event`
- Add `return True` on the line after `def _check_power_levels`
- Restart
- Change permissions
- Remove code changes
- Restart

Clearly this is not the best choice. I think in production `return True` should be replaced with `if is_server_admin: return True`.

**Comment by dreamflasher** [comment]
How does one set the power level in the postgres database?

**Comment by Half-Shot** [comment]
This issue should probably be closed. The advice above should not be followed as it messes with event authorization which will not work over federation.

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-doc/issues/652

**Comment by richvdh** [comment]
> I'm admin or moderator of a room (I forget)
> I add a moderator to a room
> The moderator kicks and bans me by accident, then unbans me and reinvites me
> Now nobody in the room has the permissions necessary to add/remove moderators

This doesn't sound right, incidentally. You should end up with the same power-level after ban/rejoin as you had before it.

**Comment by tanius** [comment]
> How does one set the power level in the postgres database?

I tried to figure that out today, but it did not work. Tried about five different routes, but things don't behave as in [the API documentation](https://matrix.org/docs/spec/client_server/latest#m-room-power-levels). Namely, even when I there are no m.room.power-levels messages left for the room and I am entered as the creator as the room in table `rooms` and have restarted the Matrix server and reloaded the , I am still not admin in that room. There's probably something going on with caching that I don't see. But it's not client-side local storage, because it also happens in Firefox Private Mode.

So doing things in the database is not a solution (for now). On top of that, the [Matrix Admin API](https://github.com/matrix-org/synapse/tree/master/docs/admin_api) does not contain a function to modify room membership or permissions. So being a "server admin" user does not help here, either.

I propose to re-open this issue and implement changing power levels and room membership in the admin API.

**Comment by rettichschnidi** [comment]
This prblem seems to have a nice solution by now: https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/rooms.md#make-room-admin-api

**Comment by Exagone313** [comment]
Is it possible to reopen this issue? I'm trying to use the *make room admin api* linked above, but I get a Bad Request error:
```json
{"errcode":"M_UNKNOWN","error":"No local admin user in room"}
```
My user was set to admin (in users table) and I use the access token given in Element client.

**Comment by richvdh** [comment]
This issue is closed because it is a known problem in the *matrix protocol*, rather than Synapse, which is tracked at https://github.com/matrix-org/matrix-spec/issues/165.

**Comment by Exagone313** [comment]
The specification issue seems a bit different than the general problem titled by this issue. Maybe I could open a different issue, though, since my issue is different than OP's. I could also be an issue to be filled in specs.

**Comment by richvdh** [comment]
@Exagone313: it sounds like you're misunderstanding what the "make room admin" API does. As the documentation says, it will give the calling user "the highest power available to a local user *who is in the room*". If there is no admin in the room, then clearly that doesn't help you.

If you administer the server for the departed user, then you might be able to use the [room_membership admin API](https://matrix-org.github.io/synapse/latest/admin_api/room_membership.html) to rejoin them to the room, or the [login as user API](https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#login-as-a-user) to get an access token, and then call the "join" API on their behalf. And then use the make-room-admin API.
