### ISSUE TITLE
cannot leave room

### ISSUE THREAD

**Issue by joreg** [matrix-org/synapse#2401]
helos, 

i've got a room that i cannot leave anymore. trying to do so gives me: "failed to leave room. not a known room." 
the room's internal ID is !CYbWHsGAMVBpzDDonk:matrix.org

it wouldn't bother me much if it wouldn't periodically send me a notification from that room, when nothing has changed in it. anything i can do to get rid of it?

**Comment by hieronymousch** [comment]
same issue here, running private server, updated to 1.15.1. Room that hangs is #matrix: matrix.org

**Comment by richvdh** [comment]
after three years, almost certainly a different problem. @hieronymousch: please can you open a new issue, and include logs from your server showing what happens when you try to leave. Also try flushing your client-side cache, if you haven't already.

@joreg: sorry for not doing anything about this sooner. I'm going  to assume the problem has solved itself, but if not, we can reopen.
