### ISSUE TITLE
How to sync if I have about 150 rooms and reach server timeout?

### ISSUE THREAD

**Issue by unclechu** [matrix-org/synapse#2409]
Consider this:
```
$ curl -XGET "https://matrix.org/_matrix/client/r0/sync?access_token=$authtoken" | tee sync.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    92    0    92    0     0      1      0 --:--:--  0:01:30 --:--:--    22
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```
It always reaches timeout and never could be done, so, what should I do in this case?

**Comment by unclechu** [comment]
Now I can't do it in Riot too, got this in browser log:
```
/sync error ORG.MATRIX.JSSDK_TIMEOUT: Locally timed out waiting for a response
bundle.js:35:13042
Object { errcode: "ORG.MATRIX.JSSDK_TIMEOUT", name: "ORG.MATRIX.JSSDK_TIMEOUT", message: "Locally timed out waiting for a response", data: {…}, stack: "" }
bundle.js:35:13042
```

**Comment by ara4n** [comment]
if you keep calling /sync it will eventually return. synapse keeps the process running in the background so that once it's calculated the result you'll eventually be able to receive it. It's ugly, but it works. The right solution is of course to make initial /sync much smaller and lazy-load info on demand (and to make the homeserver much faster)
