### ISSUE TITLE
Enable compression for federation by default in config

### ISSUE THREAD

**Issue by lehmanju** [matrix-org/synapse#2434]
I think compression should be enabled by default for both, client and federation, because it reduces traffic. My own server does not seem to have higher cpu loads than normal and because it is enabled for clients by default i can't think of any reason not to enable it for federation.

**Comment by MacLemon** [comment]
Since most of the c2s and s2s communication is text, it would greatly benefit in performance from the common gzip compression. I might even go as far as suggesting that there would be even more benefit in adding brotli compression which is supported by most browsers these days and certainly by Chrome/Electron which Riot is based upon.

It might be possible to add compression when `synapsed` is behind a reverse proxy like `nginx`, but of course not for outgoing requests.

**Comment by lehmanju** [comment]
Compression is already implemented but not enabled by default -> nginx/proxy is not strictly necessary

**Comment by ZerataX** [comment]
is there any reason not to enable this?

**Comment by richvdh** [comment]
http://breachattack.com/ possibly, but I don't *think* it applies here

**Comment by reivilibre** [comment]
BREACH and CRIME seem like suitable enough reasons not to use compression; after all, we are combining compressible data from different users together in the same compressed stream and the length of the compressed payload is therefore a possibly exploitable side channel.
I would hesitate to enable, particularly by default, without a serious cryptographer's study of the impact.

**Comment by DMRobertson** [comment]
Related: https://github.com/matrix-org/synapse/issues/13415 and https://github.com/matrix-org/synapse/pull/13537
