### ISSUE TITLE
Feedback on the repository-based installation of matrix-synapse on Debian 9/Stretch (Spoiler: It sucks.)

### ISSUE THREAD

**Issue by EvilRenegade** [matrix-org/synapse#2455]
### Description

Since you provide a Debian repository and [there are no other platform instructions than the implicit form of "use the repository"](https://github.com/matrix-org/synapse#debian), I figured synapse would install cleanly through it.
Instead, the configuration is utterly incomplete, with issues like server_name not being set (#1630), the configured tls_dh_params_path not being generated, no signing key being generated, etc.

When I tried to fix all of that manually, there was no documentation to be found.
I have yet to find something as simple as a configuration file reference.

All I found over and over was "run `generate-config`".
The problem with that? Most sources continue that with "in your virtual environment".
No documentation = no idea which virtualenv your package generated.

I found no sign of one, so I just straight up ran `generate-config` in the system-wide Python.

It did generate a config, deviating wildly from what your Debian package had (incompletely) created.

I customized a few settings like pid etc. back to the Debian configuration values, under the assumption that they would be geared towards the rest of the package installation.
iow: The Debian package knows how it installed itself, so if it set the paths like that, it probably had a reason.

I also changed the TLS certificate and key back from the self-signed one to a proper Let's Encrypt generated one.

New error: 

> File /etc/letsencrypt/live/[SERVER]/fullchain.pem config for tls_certificate doesn't exist. Try running again with --generate-config

Again: No useful documentation, no idea what its issue is. The cert is fine. It's right there where I said it is. It's being used by the webserver from right there.

Soooo I assumed massive shittiness in the implementation, in that synapse can't follow symlinks.
Nope.

> File /etc/letsencrypt/archive/[SERVER]/fullchain1.pem config for tls_certificate doesn't exist. Try running again with --generate-config

Hm? Maybe a bug? Maybe it can't take a certificate chain after all?

> File /etc/letsencrypt/archive/[SERVER]/cert1.pem config for tls_certificate doesn't exist. Try running again with --generate-config

It cannot be a misunderstanding of what the option expects, for the autogenerated file is exactly the same: A text file with a PEM-encoded certificate.
Oh well.

So I switched it back to the autogenerated self-signed certificates.
New error: 

> "Could not find a webclient."

`web_client` was False in the debconf-generated configuration, but is True in the `generate-config`-generated one.
This is exactly what I meant earlier: The Debian package probably knows how it set up the system, so overwriting the package-provided configuration with a randomly generated one is an utterly stupid process.
Too bad it's the only one that kinda-sorta-maybe works.

Supposedly the server is running now. Can't test it yet, because now Riot is complaining about rejected CORS requests.
I guess I'm gonna have to investigate *that* now.

Quite frankly: I have installed a number of programs from source before and even the least automated source compilations were less complicated and frustrating than this.
**This is the shittiest apt-based installation I have ever encountered.**

### Steps to reproduce

- Install matrix-synapse from the Debian repository
- Configure server name and reporting through the debconf part of the process, as with all other apt packages

### Expectation

Generating a configuration through the package's provided configuration steps should generate an actually functioning configuration.
A wide array of other server softwares shows that this is possible and *can* be expected, *especially* if there is a debconf step in the installation.

If issues are encountered, there should be an easily discoverable documentation of what configuration options are valid, what they do and how to generate a legal value for them.
Ideally, the installation documentation would also include a section regarding common installation issues and how to fix them, as well as documentation as to how the individual platform default configurations differ from the autogenerated one (e.g. pid location), and what the reasoning behind the difference is (e.g. Debian platform convention).

Error messages should be helpful.

### Reality

Not even the one thing that *is* being gathered by debconf, the server name, is properly written to the configuration. The server fails to start, it's missing practically all configuration.
Generating a configuration through the synapse configuration generation mechanism results in a configuration that differs wildly from the Debian-native one, including incompatible differences like expecting a web client even though the package didn't install one.

I have yet to find installation or configuration file documentation beyond README.md.
matrix-synapse doesn't even seem to have a man page.

The error messages don't even seem to make sense on a technical level, let alone help the user/admin.

### Version information

- **Homeserver**: own installation

If not matrix.org:
- **Version**:        Package version 0.22.1-1 from Matrix-provided apt repository
- **Install method**: package
- **Platform**:       Debian 9

**Comment by EvilRenegade** [comment]
Addendum: Obviously the certificate issues could be a user access problem.

Too bad there is no documentation what user matrix will run under and no documentation of how to make matrix compatible with platform conventions regarding TLS certificates.
Or a configuration documentation to see where the running user would be set.

**Comment by spaetz** [comment]
@EvilRenegade the shared certificate problem might be an read permission problem. I found that the package creates and runs the server under the "matrix-synapse" user, but not any group. I added a "matrix-synapse" group to the systemd script (would be nifty to do that in any case) and made my certificate group-readable by that group.

I agree that deinstalling and reinstalling e.g. the angular web client was very unreliable in the sense that the default config files were not always put back in place and I was unsure which "WebClient" setting would override which. (the one in homeserver.yaml or the one in webclient.yaml?)

**Comment by richvdh** [comment]
@EvilRenegade: I'm sorry you had a bad experience installing synapse.

Before I go any further: please remember we're doing our best with the time and resources we have. That does mean there are going to rough edges sometimes. I understand you found it frustrating, but telling us that the thing you got for free is "shitty" isn't helpful. Constructive feedback is appreciated; pull requests to fix problems are even more appreciated.

Anyway, It sounds like you ran into a lot of different issues. I don't use the debian package myself, but I'll try to give some answers which may be helpful:

* I don't know why you would end up with no server_name; note that #1630 specifically mentions that the installation was done non-interactively under ansible, so I think it's a separate problem.
* I also don't know why you would find the tls_dh_params and signing key files weren't generated. They should be generated by the service start script: https://github.com/matrix-org/package-synapse-debian/blob/debian/debian/matrix-synapse.service#L9. The output from `journalctl -u matrix-synapse` might give more clues.
* running `generate-config` might help with the above problems, but will end up in conflict with the debian packaging, and as you discovered will lead to other problems. I wouldn't recommend it on a debian install.
* Your "File /etc/letsencrypt/live/[SERVER]/fullchain.pem config for tls_certificate doesn't exist" is almost certainly because the `matrix-synapse` user didn't have read access to the `/etc/letsencrypt/live/[SERVER]/` directory.
* The debian package doesn't install the angular web client, so `web_client` should be False.

So in short we have:
1. the initial install didn't work properly, for reasons we don't understand and would need more information on to investigate.
2. then you used generate-config, which led to lots of other problems down the line.
3. there was a separate problem with permissions on your TLS certs, which isn't really a synapse bug.

I'd recommend that you seek help online (try [#matrix-dev](https://matrix.to/#/#matrix-dev:matrix.org)) if you encounter further problems, so that we can give you guidance rather than you following a path that will lead to more problems.

I'm going to close this issue now, because I don't think it gives any actionable improvements; we'll need more information on what went wrong with the first steps that made you try to use `generate-config`.
You're welcome to open further issues, but please try to keep them specific rather than a general vent of your frustration so that we have some hope of dealing with them.

**Comment by richvdh** [comment]
I hope #2551 will help with some of the unhelpful errors here.

**Comment by EvilRenegade** [comment]
@richvdh I don't subscribe to the "you have to be Leonardo da Vinci to criticize the Mona Lisa" school of criticism.
A shitty thing is shitty, no matter how much I paid for it or whether I could recreate it myself.

In fact, I find your assertion that I "got [it] for free" a tad offensive and insensitive. 'cause that's kind of the point: The Debian installation instructions for matrix-synapse are essentially one item: "We have packages". There's an implicit promise there that installation will be standardized and hassle-free. No compilation, no manual copying of stuff, just add the repository and let apt do the rest.

Instead, rather than being a one-minute-installation like hundreds of other open source projects with custom apt repositories, this completely nonfunctional "installation" burned through hours of my time.

By asserting that I "got [it] for free", you are essentially saying that my time is worthless, and no harm is done by wasting it.

I resent that remark.

I also resent the suggestion that my post was not constructive. I have taken the time to give you the exact scenario that occurred, what I tried, what happened, which of my expectations as a user of the product were not matched, possible sources of error, etc.

In fact, I openly stated that the certificate access problem might be a rights issue, and noted that I couldn't debug it because of lacking error messages. So no, that may not be a synapse bug - but the fact that the issue is almost completely unresolvable to me as a user because there's not the slightest hint of what's wrong very much _is_. So the information that it happened very much has its place in a this bug report (or the addendum).

All of that very factual, very product-centric information is far off from a plain "this is shit".

Where I come from, we have a saying - "jammern auf hohem Niveau". Roughly translated "whining at a high level".
If the bug reports you get are consistently of such high quality and high information density that what I gave you is a terrible report, then, as a developer, I envy you.
Compared to the bug reports I get, that was a fucking all you can eat buffet.


So, since you've shown an affinity to sum things up in short:
1. There is no real documentation regarding the installation on Debian through your repository. Just the general information ["Matrix provides official Debian packages"](https://github.com/matrix-org/synapse#debian). That's not my fault, but yours.
2. The implication is that the package will install a usable application, as is the case with pretty much every other open source project providing installation through package management. That is not the case. You are offering these packages as an official installation method. Therefore, that's not my fault, but yours.
3. The one thing that can be configured through debconf doesn't actually properly end up in the synapse configuration. That's not my fault, but yours.
4. There is no documentation on what to do if the Debian configuration isn't generated or doesn't function. That's not my fault, but yours.
5. The official configuration documentation tool is incompatible with the official Debian installation method. That's not my fault, but yours.
6. There is no documentation on the execution parameters of the apt-based installation, like user, python environment, etc. That's not my fault, but yours.
7. There is no documentation on what of the configuration the package actually *did* set was set that way for a reason and must remain that way, and what can be changed without damage to the installation. That's not my fault, but yours.

With that many faults on your side, I find your summary of 

> 1. _we don't understand our own official installation methods_
> 2. _our own software is incompatible with our own software, but we still consistently push you to use it anyway_
> 3. _we give you jack shit to debug additional issues_
> 
> _but it's your fault anyway!_

to be quite unsatisfactory.

There's boatloads of actionable improvements here. Seven different issues that you could fix, plus the additional implicit issues of actually understanding how your own installer works and improving your communication towards the community.
Because believe it or not: Putting down a bug report that gives you that much information about everything that happened and all the different user expectations that weren't met as "a general vent of your frustration", pretty much ensures that the user considers talking to you a waste of time and will not be of help investigating the issue.

Or, to put it in actionable items: Improve your software, improve your documentation, and improve your interaction with your users.

**Comment by ara4n** [comment]
@EvilRenegade: @richvdh has been fixing the error handling to improve the failure modes you hit in #2551, and all you can do is to whine about being criticised for namecalling. With the effort you have put into your original bug report and subsequent ranting you could have done something useful like help contribute a fix to the .deb. Right now the team is comically undermanned (if you haven't spotted the huge text on matrix.org); nobody is in position to maintain the debian packaging; and we are relying on the community to assist.

It looks like this bug is now covered by other sub-issues in matrix-org/package-synapse-debian so I'm locking it.
