### ISSUE TITLE
[Feature Request] Sticker Pack Support

### ISSUE THREAD

**Issue by subins2000** [matrix-org/synapse#2467]
### Description

It'll be great if there's sticker support in matrix. Client apps can make the stickers and include it. But instead of sending the sticker image each time, it'll be better if the homeserver stores it once.

Does the matrix homeserver already skips saving image files if there are duplicates ? If there isn't it'll be better and will be highly useful if a client implements sticker support.

**Comment by uhoreg** [comment]
Stickers don't really need server support, since the server already has everything needed.  This is more of a client issue: https://github.com/vector-im/riot-web/issues/2950

Synapse doesn't automatically deduplicate, but you can reference already-uploaded files, so you don't have to re-upload stickers all the time.

**Comment by ara4n** [comment]
dendrite does deduplicate, fwiw. closing this one in favour of riot-web bug

**Comment by subins2000** [comment]
Referencing already-uploaded files is the best way. Thanks.

Deduplicating should be fixed. Will be useful for dendrite.
