### ISSUE TITLE
Inviting a user to a group twice breaks the group

### ISSUE THREAD

**Issue by vurpo** [matrix-org/synapse#2633]
### Description

After the same user joined a group twice, all requests for group information now return a 500 Internal Server Error

### Steps to reproduce

- Invite a user to a group (using the `/groups/:group_id/admin/users/invite/:user_id` API)
- Have the user accept the invitation
- Repeat steps 1 and 2
- Now Riot only says "Failed to load *group ID*" (and looking at the debug console in Riot reveals that all the requests are returning a 500 Internal Server Error)

I just realized I had a broken log config for this HS, so I have no homeserver.log to look in. I can fix that and then look at the logs though, if that's necessary

### Version information

- **Homeserver**: godotengine.org
- **Version**: Synapse 0.24.1
- **Install method**: git clone
- **Platform**: Regular Fedora installation (no VM/container)

**Comment by vurpo** [comment]
I found this line in the homeserver.log, which makes the issue seem pretty self-explanatory:

`2017-11-03 02:15:18,094 - synapse.http.server - 123 - INFO - GET-10- <SynapseRequest at 0x7fc8ac1cfb00 method=GET uri=/_matrix/client/r0/groups/%2Bgodot%3Agodotengine.org/users?access_token=<redacted> clientproto=HTTP/1.1 site=8449> SynapseError: 500 - More than one row matched`

**Comment by Valodim** [comment]
This just happened to me. A user joined a group but got an error (don't have an exact error msg, "Couldn't join group" or something like that), so I invited them again. Now the group can't be listed anymore in Riot.

Checking the database, there are two entries for this user in group_users, and also in attestations_remote. There is no unique index on group_users or the attestation tables, is that intentional? Either way, something is definitely up here..

The user in this case is on matrix.org (do you have the duplicate entry too, now?), the group is on stratum0.org.

**Comment by vurpo** [comment]
@Valodim I had to fix this by manually deleting the duplicate rows in the database

**Comment by necessary129** [comment]
Got hit with this bug a couple of time now. :disappointed:

**Comment by Cadair** [comment]
I have also got hit with this twice in the last two days. The last person to trigger it claims that he only pressed the join community button once!

**Comment by turt2live** [comment]
fwiw I saw this when the user tried to accept their second invite, not when the invite was issued.

**Comment by clokep** [comment]
Communities/groups are being removed, see #11584.
