### ISSUE TITLE
The group server should be completely independent of the homeserver

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#2691]
The group server should be a completely independent server from the homeserver or any other component in a matrix system. Having this separation allows for third party group servers and enhanced functionality, above and beyond what synapse may provide. 

The current situation is that group information comes down /sync, which effectively prevents the group server from being ripped away from synapse. The third party server could do some mitm handling of /sync, however that feels silly.

Further, the group server should get it's own series of endpoints (like the media repo). Instead of being under the client namespace, it should be under the `groups` namespace or similar (`/_matrix/groups/r0/whatever`).

I've filed this issue here for visibility, and the lack of spec. It would be greatly appreciated if the group server can be handled outside of synapse.

**Comment by erikjohnston** [comment]
This is supported today. A group server just needs to implement the group APIs in the federation side and thats it. All API calls from the client get mitm'd on the local HS anyway─which deals with sending stuff down sync─and forwarded to remote servers if the group isn't local.

The only cheeky thing that synapse group server implementation does is to use its local knowledge of rooms to fill out the room profile when the group server returns the list of rooms.

(I have cunning plans to implement a GS in rust as a PoC, but I haven't had the time...)

Obviously this needs to be specced.

**Comment by erikjohnston** [comment]
(Oh, unless you're asking for the implementation in synapse to be splitout-able?

**Comment by turt2live** [comment]
If a third party group server were to be implemented, then synapse wouldn't have any knowledge of the groups existing, therefore it couldn't send them down /sync. 

That's more of the issue here (ignoring the lack of spec).

**Comment by turt2live** [comment]
Having a dedicated worker for groups would be nice, but probably a different issue.

**Comment by ara4n** [comment]
(https://docs.google.com/document/d/1ZnAuA_zti-K2-RnheXII1F1-oyVziT4tJffdw1-SHrE/edit is a scenario where it'd be undesirable to split GS from HS (unless a GS was basically a HS that happened to specialise in the GS API...))

**Comment by turt2live** [comment]
Having groups as rooms would be an implementation detail in my eyes. I'd rather see the group server be independent from the homeserver (and client spec fwiw), ideally with rich endpoints to mimic rooms (state events, etc).

**Comment by erikjohnston** [comment]
> If a third party group server were to be implemented, then synapse wouldn't have any knowledge of the groups existing, therefore it couldn't send them down /sync.

That's not true, which is my point. The local users HS is responsible for handling /sync calls, not the group server. This is how joining remote groups work still.

The synapse implementation is fairly isolated, and it wouldn't be difficult to make synapse use a different group server implementation for local groups.

**Comment by ara4n** [comment]
"Rooms as groups" isn't really an implementation detail, as you'd by definition need a full homeserver (capable of federating & synchronising rooms) in order to host them if this was the case.

I'm very worried about the fact that we've sprouted completely different APIs for doing the same operations to groups as we do to rooms (i.e. manage associated state, manage associated users, etc), and forcing clients and servers into forever implementing a whole new set of endpoints just to put them in a different namespace to make splitting out a GS feels dubious.

I totally agree that it should be possible to run a node which just exposes the Group Server API (just as you should be able to run one which just does CS API, or Directory Server API), but this isn't a good reason to have entirely different API shapes - rather than the GS 'mimicking' the CS API, 

Instead, a better architecture might be to let the thing which actually provides the group information be replaceable.  In the "rooms as groups" thought experiment, perhaps one way to think of that could be an AS-style API to bridge to 3rd party sources of group information.  But saying "to support extensible group behaviour we should have a whole separate namespace of APIs to the existing CS API" seems to be putting the horse before the cart a bit...

**Comment by freelock** [comment]
Just noodling over user stories for this, and have hit upon a real one. I'm part of the LedgerSMB core team, an open source project. We have a few rooms, and it would be useful for core members to have flair. So I was thinking about setting up a group. But where? +ledgersmb:matrix.freelock.com seems a bit inappropriate, and +ledgersmb:matrix.org is not ideal.

However, +core:ledgersmb.org would be perfect. We have no (current) need for a ledgersmb.org homeserver, (although there are some thoughts about possibly baking in a support system with such a thing) but a light-weight group server with its own domain name would be great.

**Comment by freelock** [comment]
... of course, we would want to be able to add a full HS on that domain at some later point...

**Comment by turt2live** [comment]
There's quite a few of my issues that contradict each other as part of my attempts at trying to figure out what kind of use cases I wanted to solve. I'll take a look at this and my other group issues over the next couple days to figure out what I was going for.

**Comment by ara4n** [comment]
thanks. the reason for asking is that as we revisit the group API (to ensure it doesn't take 3 weeks to add a single configuration bit to a group like 'make group joinable) it'd be good to understand clearly what folks want out of it - especially when it comes to overlap between the HS and GS aspects of the CS API.

**Comment by turt2live** [comment]
I'm not convinced this issue is providing value anymore - the arguments have been had over the years.
