### ISSUE TITLE
No previews of sites with secp256r1 disabled

### ISSUE THREAD

**Issue by rkfg** [matrix-org/synapse#2890]
### Description

There's no preview at all for any urls from keytown.me, for example, neither title nor image. The issue title might be misleading, that's only an assumption.

### Steps to reproduce

- post an url like https://keytown.me/
- no preview appears as if it's not even an url

Log reads:

```
2018-02-20 09:48:09,012 - synapse.http.server - 124 - INFO - GET-6- <SynapseRequest at 0x7faf78407518 method=GET uri=/_matrix/media/r0/preview_url?url=https%3A%2F%2Fkeytown.me%2F&ts=1519109288279&access_token=<redacted> clientproto=HTTP/1.0 site=8008> SynapseError: 500 - Failed to download content: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]
```
From what I found this happens if the site disabled SSLv3 on their end or if cipher suites don't match (see #2350). Some advice downgrading python-cryptography but it didn't help in my case.

### Version information

- **Homeserver**: own homeserver
- **Version**:  Synapse/0.26.0
- **Install method**: package manager
- **Platform**: set up on Debian 9.3 amd64.

**Comment by richvdh** [comment]
SSLv3 is very old - it would be a worry if we required that, and indeed we do not.

The problem is basically the same as #2350: a bug in twisted (or at least, an incompatibility with some openssl/pyopenssl versions) means that synapse only presents one elliptic curve (secp256r1), and keybase.me apparently rejects the connection because of it.

The twisted bug is https://twistedmatrix.com/trac/ticket/9210.

**Comment by rkfg** [comment]
Fixed on the Twisted side now.
