### ISSUE TITLE
"Failed to get displayname" "Failed to get avatar_url" when I try to communicate two synapses between them

### ISSUE THREAD

**Issue by bzhfloriane** [matrix-org/synapse#3014]

**Comment by silkeh** [comment]
Because you have configured `nexus_chat{1,2}.nexus` [in /etc/hosts](https://matrix.to/#/!XqBunHwQIXUiqCaoxq:matrix.org/$15215578853264540kjrDb:matrix.org), it is possible that Synapse attempts to connect to the resolved address (127.0.53.53).

This is probably hard to see because you use and existing TLD (`.nexus`). Don't do this.
Also note that `_` is not a valid character in a hostname.

**Comment by reivilibre** [comment]
no details
