### ISSUE TITLE
Messages are not flagged as not delivered when not delivered due to errors on the server

### ISSUE THREAD

**Issue by emdete** [matrix-org/synapse#3394]
### Description

If the server has problems delivering a message (see #3387 ) the client does not reflect this. This is (for me) the worst case scenario, when you believe to talk to people but you dont (for example if you put questions and get no answer). technic should never stand in the way for communication like this.

### Steps to reproduce

- Get the server in a state to not accept the federation server key (see #3387 )
- Be in a room hosted on the other, unaccepted server
- Read the people talking (your server still gets the messages as the sig is accepted)
- Write a message and assume it went through as all GUI behaviour indicates so

The message does not make it to the other server and thus not into the room and wont be read.

### Version information

homeserver Synapse/0.31.1 with all riot clients.

**Comment by richvdh** [comment]
that's what read receipts are for?

**Comment by richvdh** [comment]
(in general, I'm not sure how you would reflect this in a room with hundreds of homeservers, some of which may be offline)

**Comment by Half-Shot** [comment]
I think read receipts solve this case as they cover both homeserver flakeyness and people not checking their phones. There was an issue hanging around for a much worse case where events can be sent to an offline homeserver and they aren't retried until some other action happens in the room that causes the events to be backfilled.

**Comment by Half-Shot** [comment]
>homeserver silently, agree?

I don't think we *ever* silently throw away messages without informing the user locally. Over federation it's a different issue and falls into dispute territory, and I'm not sure how that is resolved.

But from a certain perspective if your local homeserver accepts the event then it exists in the network from your point of view and was sent successfully, it's up to the other homeservers to adopt it.

If there is a case where a message is being sent from one homeserver and not being received by the other then it would be best to fix the **cause** rather than trying to spec a flagging system that tells us if one or a few (of potentially thousands) of servers didn't receive it.

**Comment by neilisfragile** [comment]
Closing, unless there is a counter example to "I don't think we ever silently throw away messages without informing the user locally."
