### ISSUE TITLE
If a synchrotron falls behind, replication starts chewing 100% cpu on master in repl.get_stream_updates

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#3412]
the same behaviour happens if you restart master without restarting the synchrotrons

**Comment by neilisfragile** [comment]
cc @hawkowl

**Comment by hawkowl** [comment]
One of these bugs -- when you restart master and not the synchotrons -- is fixed by https://github.com/matrix-org/synapse/pull/4127 .

**Comment by richvdh** [comment]
FTR, I restarted the master without restarting the synchrotrons this morning, and nothing exploded.

We're not entirely sure if the the whole of the original bug has been entirely fixed, but we haven't seen the described behaviour for a while, and in any case the issue was confused by having two related but different problems in the same issue.

We're closing this for now and will open a new issue with more details if we discover there are still problems.
