### ISSUE TITLE
Stuck invites after trying to reinvite a user after banning them.

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#3593]
@Tyuoli reports:

* A and B are on different servers
* A creates a private room and invites B to it
* B joins it
* A bans B
* A unbans B
* A re-invites B
* B has a stuck invite they cannot either accept or reject?

**Comment by giomfo** [comment]
@ara4n I think this issue is related to https://github.com/matrix-org/synapse/issues/3515

In both cases the server of the user B does not update correctly the room history (and state) while the user B is out of the room.
I think the server of user B ignores all the new events of the room because none of its users belong to this room.

**Comment by richvdh** [comment]
dup https://github.com/matrix-org/synapse/issues/1563
