### ISSUE TITLE
Broken GET/_matrix/client/r0/rooms/{roomId}/state/{eventType} 

### ISSUE THREAD

**Issue by slipeer** [matrix-org/synapse#3675]
Seems like queryng room state with `eventType` specified but without `state_key` is broken.
For example for #matrix:matrix.org:
```bash
> curl -X GET --header 'Accept: application/json' 'https://matrix.org/_matrix/client/r0/rooms/&#33;QtykxKocfZaZOUrTwp%3Amatrix.org/state/m.room.aliases?access_token=XXX'
```
always returns
```json
{
  "errcode": "M_NOT_FOUND",
  "error": "Event not found."
}
```
and with stake_key (
GET /_matrix/client/r0/rooms/{roomId}/state/{eventType}/{stateKey} ) all work fine
```bash
> curl -X GET --header 'Accept: application/json' 'https://matrix.org/_matrix/client/r0/rooms/&#33;QtykxKocfZaZOUrTwp%3Amatrix.org/state/m.room.aliases/m.12o.nl?access_token=XXX'
```
returns
```json
{
  "aliases": [
    "#matrix:m.12o.nl"
  ]
}
```

`GET /_matrix/client/r0/rooms/{roomId}/state/` work fine too.

P.S. It is also probably necessary to implement tests.

**Comment by Half-Shot** [comment]
This is intentional. https://matrix.org/docs/spec/client_server/r0.3.0.html#get-matrix-client-r0-rooms-roomid-state-eventtype. Calling this endpoint without a ``state_key`` is equivalent of fetching state events with an empty string ``state_key``. This is NOT fetching all state_events of that type.

Aliases do not generally have empty key entries since they are keyed off the homeserver's domain

**Comment by ulope** [comment]
This should be documented more clearly.
"defaults to the empty string" can easily be read as the state key being optional.

**Comment by Half-Shot** [comment]
This is an issue for https://github.com/matrix-org/matrix-doc/issues
