### ISSUE TITLE
add channel instead of room

### ISSUE THREAD

**Issue by sepidehnaghdi** [matrix-org/synapse#3745]
I need to create channel like telegram channel. Can I create channel in synapse (not room or group)?

**Comment by Cadair** [comment]
Matrix doesn't have anything named 'channels' what does a telegram channel do that a normal matrix room does not?

**Comment by sepidehnaghdi** [comment]
channel can have one or multiple admins to send messages to it but in room all members can send message. I know that with permissions we can have semi channel in matrix. but in matrix when number of room members increase, system resources like RAM increase a lot and I think it's because of number of connections between all members in room. channel in telegram support unlimited number of members because of that I need channel in matrix.

**Comment by Cadair** [comment]
The synapse resource usage is AFAIK related to the number of servers in a room and the number of users on your server. There is a lot of work ongoing to make the resource usage better. 

As for the only admins can post thing, you can already do that as you mention. So I am a little confused by what this issue is actually asking now.

**Comment by t3chguy** [comment]
@sepidehnaghdi Matrix Rooms can have the "Minimum Power Level to send messages" set and you could set it so only admins can talk, e.g `#news:matrix.org`

**Comment by MurzNN** [comment]
Here is an issue, related to the implementation Telegram Channels like feature: https://github.com/matrix-org/matrix-spec/issues/367
