### ISSUE TITLE
Split fed worker & sender config means destination retry sched doesn't invalidate when you receive traffic

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#3798]

**Comment by ara4n** [comment]
For the federation mess surely we just put a TTL on the cache for now - 5 mins or whatever rather than having the federation blackholed indefinitely?

**Comment by ara4n** [comment]
(LISTEN/NOTIFY could be fun as a future adventure tho)

**Comment by erikjohnston** [comment]
Possibly, but like I said I'm disinclined to continue putting footguns in our code given that this sort of hacky solution is *exactly* what has led to this mess. As a stop gap measure it may be the best thing to do right now but I'm not comfortable sticking a band aid on this and moving on.

**Comment by hawkowl** [comment]
Related to cache backing: https://github.com/matrix-org/synapse/issues/2123

**Comment by richvdh** [comment]
any reason not to communicate the cache invalidation from worker to master via the existing replication channels.

[fwiw if we do end up deciding to build something new, I'd much rather we use something like memcached than postgres pubsub, for many of the reasons mentioned in #2123, but really just because we shouldn't be building our own wheel]

**Comment by erikjohnston** [comment]
> any reason not to communicate the cache invalidation from worker to master via the existing replication channels?

The worker -> master communication is done via HTTP, which is actually probably fine if we batch it up for `get_destination_retry_timings` though I wouldn't necessarily want to rely on it for other caches

> [fwiw if we do end up deciding to build something new, I'd much rather we use something like memcached than postgres pubsub, for many of the reasons mentioned in #2123, but really just because we shouldn't be building our own wheel]

Historically the problem is that external cache services just don't match the use cases of our caches, in particular CPU usage and latency (I believe there are places that assume that things are probably going to be quick due to things being in cache). While I agree that we shouldn't be reinventing the wheel, requiring memcached/redis/etc just for a communication layer feels a bit overkill.

OTOH, it might be useful for the different problem of reducing DB load.

**Comment by erikjohnston** [comment]
After some discussion, the conclusion was that (for now) we'll just remove the cache for `get_destination_retry_timings`, since on matrix.org they're only hit ~50-100Hz
