### ISSUE TITLE
synapse/python_dependencies.py crashes on startup with TypeError

### ISSUE THREAD

**Issue by mbakhoff** [matrix-org/synapse#4311]
### Description

Synapse crashes on startup with debian sid.

### Steps to reproduce

- Use debian sid
- Upgrade to 0.34.0~rc2-1
- systemctl restart matrix-synapse

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3/dist-packages/synapse/app/__init__.py", line 
    python_dependencies.check_requirements()
  File "/usr/lib/python3/dist-packages/synapse/python_dependencies.py"
    if LooseVersion(version) < LooseVersion(required_version):
  File "/usr/lib/python3.7/distutils/version.py", line 304, in __init_
    self.parse(vstring)
  File "/usr/lib/python3.7/distutils/version.py", line 312, in parse
    components = [x for x in self.component_re.split(vstring)
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by mbakhoff** [comment]
this happens when checking the version of module_name='treq'. 

adding this hack fixes the startup:
```
  version = getattr(module, "__version__", None)
+ if type(version) is bytes:
+     version = version.decode('utf-8')
```

**Comment by richvdh** [comment]
thanks. Any chance you could make your patch into a Pull Request?

**Comment by hawkowl** [comment]
I just merged a rewrite for this code, could you see if current develop has the same problem?

**Comment by mbakhoff** [comment]
@richvdh i have `python3-treq 15.1.0-1` installed, it was pulled in by the synapse deb package. `python-treq` is not installed. 

@hawkowl i tried to patch the rewrite changes into my matrix-synapse_0.34.0~rc2-1_all.deb based installation. now the startup fails with `Missing Requirements: "frozendict>=1", "pymacaroons-pynacl>=0.9.3", "msgpack-python>=0.4.2"`. no sign of the original TypeError. the error is a bit strange because apt says i have `python3-msgpack 0.5.6-1+b1` and `python3-pymacaroons 0.13.0-1` installed.

**Comment by mbakhoff** [comment]
i managed to reproduce the issue using the following Dockerfile:
```
FROM debian:sid
RUN apt update && apt upgrade -y && apt install -y matrix-synapse
RUN /usr/bin/python3 -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config-path=/etc/matrix-synapse/conf.d/ --generate-keys
```

**Comment by richvdh** [comment]
Oh right, you're using the package from debian rather than ours. You'll need to take this up with Debian.

**Comment by mbakhoff** [comment]
huh, ok. i didn't know these are different. thanks for all your help :) 
(i would move to your repo if it supported aarch64)

**Comment by andrewshadura** [comment]
@richvdh, apparently it did.

https://salsa.debian.org/python-team/modules/python-treq/blob/master/setup.py#L18

**Comment by andrewshadura** [comment]
@richvdh, besides, [`synapse/python_dependencies.py`](https://github.com/matrix-org/synapse/blob/master/synapse/python_dependencies.py#L43) has this:
```python
"treq>=15.1": ["treq>=15.1"],
```

**Comment by hawkowl** [comment]
@andrewshadura `python_dependencies` has this, because Debian only shipped 15.1 -- that's the constraining factor, not "what we think it should be". We haven't gone through and tested what happens if you have old versions on Py3, the expectation so far has been that you'd be using a venv or some mechanism of having recently released versions. For Python 3, we'd need 17.x+ or so, I'd think.

When we drop Python 2 support, and therefore support for Debian packages that are not yours and in stable-backports or constructed using a venv, all these version numbers will have to be pulled up quite forward, since even by 2017 not everything was finished porting in a bug-free manner (hell, Twisted still had corner cases we're fixing on Py3 in 2018).

**Comment by andrewshadura** [comment]
Wait, why? In your Python packages, you’re supposed to say what your actual dependencies are. If the distro can satisfy your actual requirements with a different version, as it often happens, they would patch the file.

Could you please check all dependencies and verify they are up to date and are your *actual* dependencies?

**Comment by andrewshadura** [comment]
Please pretty please, pull the versions *now* so that we at least know how much is missing there. Patch them back to the minimum working versions just for the packages.

**Comment by andrewshadura** [comment]
This is the consequence of you trying to do the distributions’ work. This is exactly why I was (and Oleg too, if I’m not mistaken) saying on the chat that you should not provide any packages except distro-agnostic and leave that job to the distributions. You’re trying to be both upstream and downstream, but that cannot sensibly work since you constrain your upstream work by concerning too much about packages.

**Comment by richvdh** [comment]
@andrewshadura I'm sorry if you feel frustrated.

To pick the versions that are in `python_dependencies`, I see three options:

* Pin to the latest version of every library. It might save us from this sort of problem, but surely it would mean a lot of pointless work for downstream packagers. It is, of course, more-or-less equivalent to what we have done in the virtualenv packages.
* Look at what's readily available in stable distributions (including, as @hawkowl mentions, Debian), and check that a Synapse installation using those versions passes our test suite.
* Find the *absolute minimum* version that synapse will work with. This would be very time-consuming when multiplied across tens of libraries, and it's hard to see what the advantage would be if nobody is using those old versions.

We've gone with the second option. We actually have a CI step which checks that a Synapse installation using the minimum requirements works - however, it cannot possibly cover all potential combinations of libraries and environments.

What `python_dependencies` is *absolutely not*, is a guarantee from us that the minimum library versions are completely free from bugs and will work perfectly in all environments, but that seems to be what you are asking for here.

In this particular case, in treq 15.1, `treq.__version__` is a `bytes` rather than a `str`. In my opinion (and apparently that of the treq maintainers, since it later got fixed) that was a bug in treq, not in Synapse. I'm afraid I do not agree that the Synapse development team are responsible for that bug.

I see that you have uploaded an updated version of python-treq to fix the problem reported here. Thank you for doing so.

Incidentally, I think this problem could have been caught earlier if you ran the unit test suite during packaging. The following is a quick-and-dirty addition to the `rules` file to do so:

```
override_dh_auto_test:
        PYTHONPATH=. trial tests
```

**Comment by andrewshadura** [comment]
Actually, there is autopkgtest for this package, and it seems it never passed: https://ci.debian.net/packages/p/python-treq/testing/amd64/
