### ISSUE TITLE
TLS Parameter misleading

### ISSUE THREAD

**Issue by KPKoch** [matrix-org/synapse#4624]
SYNAPSE_NO_TLS behavior unexpected. SYNAPSE_NO_TLS=1 and SYNAPSE_NO_TLS=0 didn't work for federation behind a proxy-

Expected behavior: 
SYNAPSE_NO_TLS=1 works behind a proxy and is also able to support federation connections.
SYNAPSE_NO_TLS=0 works with certs in /data/homeservername.tls.key/crt with direct forwared port 8448.

Details:
I setup a new server recently and decided to try this docker file.
As I like the idea of having everything behind a proxy (with it's on cert manager), I struggled with the installation as I chosed: SYNAPSE_NO_TLS= 1.

As stated more than once, the documentation of Synapse regarding the (federation)ports, the docker config  suggests that we can disable TLS and use 8008 instead for both (second -names: entry in homerserver.yaml).

This didn't work for me from federation perspective. So I set SYNAPSE_NO_TLS=0, using the valid proxy certs also on matrix host. Also, no incoming connect.

Solution:
After removing the env variable completely it seems to work (still with some regular timeouts in the logs).

Wish:
Improved documentation about deployments behind proxies and better documentation regardings ports & tls in general. 
Let's encrypt can't be the answer for everything, as it doesn't fit in every environment.

**Comment by richvdh** [comment]
so what actually went wrong?

**Comment by KPKoch** [comment]
I had to remove the parameter at whole to get it working. Neither 0 or 1 helped me.

IMHO, I assume 2 reasons: 
clarity of information the documentation is misleading or at least doesn't clarify enough - may depend on the 0.99 <-> 1.0 changes. There are some posts clarifying it ( https://matrix.org/blog/2019/02/05/synapse-0-99-0/ ), which helped me a lot. Also this seems to me opposite to the docker homeserver.yaml, which states that 8008 can also be used for federation communication. 

Second, I simply wasn't able to get it to work with the parameter- sending meassages and getting locally was possible, but not receiving from external. I first routed 8448 AND 8008 to the 8008 container port  with SYNAPSE_NO_TLS = 1. (assuming the config will skip the 8448 port)
My next steps where to take the valid (let's encrypt)  cert, copied it to /data, renamed it accordingly, set SYNAPSE_NO_TLS = 0. Changed the routing to route 8448 directly to the restarted container, but still, no incoming messages.
After removing the env var completely and a restart later everything worked as expected.

So in the end: it works. But the time used to get to this solution and the effort of getting more information to make an informed choice was way more than expected and more than the first time I needed for another synapse image in my installation months ago).

As also stated here: https://github.com/matrix-org/synapse/issues/2438 (which was my reference in the OP), it is very confusing if 8448 is mandatory or 8008 can also be used (if either routed or made public via dns records) or not.
My current assumption, according to my information is, that it IS needed to have a federation port AND a client port.  If this is correct, the homeserver.yaml given by the container will skip the 8448 when SYNAPSE_NO_TLS is set. But even now, I am very unsure with this. The only thing I think I know for sure is, that v1 will need the same and valid cert for server use and client connection.

Still, there's always a chance of local problems - but even the lack of clearance alone is enough to make unclear descisions.

**Comment by Zerwin** [comment]
Hey, sorry if this is off-topic, but I am currently in a similar situation as you were apparently. I heard of Matrix and tried to setup a server, but I can't get it to work.

I used Docker for my installation and followed this guide (https://jonnev.se/matrix-homeserver-with-docker/), but I am currently stuck in a loop. I have configured port 8448 with type http and tls true, and 8008 also with http, but with tls false. When I tried to start synapse, the log says I must specify tls_certificate_path if TLS is enabled. I quickly found out, that this is because Synapse now requires TLS certificates other than the self signed ones. That wasn't much of a problem, as I already have a wildcard certificate I use for most of my subdomains. Trying to change the path to where my certificates are stored, results in an error of "No such file or directory", which I first thought means maybe he can't access the directory, but after some searching I found this (https://github.com/matrix-org/synapse/blob/master/docker/README.md) and from there on then your post. Trying SYNAPSE_NO_TLS = 1 makesmy log says some (for me) not understandable error (short extract)

File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
synapse_1   |     "__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
synapse_1   |     exec code in run_globals
synapse_1   |   File "/usr/local/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 659, in <module>
synapse_1   |     main()
synapse_1   |   File "/usr/local/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 654, in main
synapse_1   |     hs = setup(sys.argv[1:])

I am also a bit overwhelmed by everything, I tried to read up on the different ports (Client, Federation) but am still not sure what does what, and which port is allowed to be behind an reverse proxy, etc.

**Comment by richvdh** [comment]
> Also this seems to me opposite to the docker homeserver.yaml, which states that 8008 can also be used for federation communication.

There is no homeserver.yaml in our docker image. You can use whichever port you like for federation, but note that the default is 8448 so if you want to use port 8008, you will have to override the default via a SRV record or a .well-known file. Note also that federation requires HTTPS.

I'm afraid I'm still failing to understand what the actual problem is here. Please can you give a link to the documentation you believe is incorrect or misleading.

@Zerwin best place to get support is [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org)

**Comment by richvdh** [comment]
> My current assumption, according to my information is, that it IS needed to have a federation port AND a client port.

It is not necessary to have separate federation and client ports.

> The only thing I think I know for sure is, that v1 will need the same and valid cert for server use and client connection.

It is not necessary to use the same cert for servers and clients. But yes, you need valid certificates for both servers and clients and it may well be easier to use the same one.

**Comment by richvdh** [comment]
don't think there is an actual bug here
