### ISSUE TITLE
Auto invite to rooms on accepted invite to community

### ISSUE THREAD

**Issue by jaywink** [matrix-org/synapse#4762]
**Description:**

Synapse already allows configuring auto join to a list of rooms after signup.

It would be neat for communities to have the possibility of adding auto-join rooms for a community. So when an invite to a community is accepted by a user, the user would automatically be joined (or invited?) to a selected list of rooms.

**Comment by Kosyne** [comment]
Seconding this. As it is right now, the communities feature serves little function because for these other rooms to be used, every single user would need to manually join every single room. For many, the process is just 'abrasive' enough for them to ignore the feature entirely.

I'd really like to see it be an autojoin over an autoinvite (possibly with a warning, possibly with an option to set which of the two), as it would be the most frictionless way to add users to a community/group a la other chat software.

**Comment by caglar1** [comment]
is there any good news about the feature
autojoin communities feature is really needed

**Comment by paulRbr** [comment]
It seems this issue will be solved by https://github.com/vector-im/element-web/issues/15930 (implementing the spec [MSC1772](https://github.com/matrix-org/matrix-doc/pull/1772))

**Comment by babolivier** [comment]
@jaywink Is this still needed, now that communities aren't a thing anymore? Do we want the same for spaces, or is the "suggested rooms" feature of spaces enough?

**Comment by jaywink** [comment]
Yeah, I think join rules and suggested rooms solve this nicely :tada: , so happy to close from my side. If anyone feels strongly differently, feel free to shout.
