### ISSUE TITLE
Workers fail to start without a listener

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#4783]
People keep trying to set up workers without a listener (not even a metrics one), and this causes a configuration error on startup. Should probably still work, even if running blind is not the best choice

**Comment by evilham** [comment]
For context: https://matrix.to/#/!HsxjoYRFsDtWBgDQPh:matrix.org/$15515594544gbcvx:unchat.cat?via=matrix.org&via=chat.weho.st&via=disroot.org

My issue turned out not to be exactly this, still there is room for improvement. I'd be happy to add a PR with better documentation if this is expected behaviour.

If OTOH cases like the `appservice` and `pusher` workers, not having `worker_listeners` defined in the configuration is OK, this would require defaulting to an empty list and some code changes which I could also take a look into.

**Comment by evilham** [comment]
Adding some more information: setting `worker_listeners: []` also works for, e.g. `appservice` and `pusher`.

**Comment by erikjohnston** [comment]
Hopefully #4853 fixes this

**Comment by evilham** [comment]
Inded, @turt2live can close this now :)
