### ISSUE TITLE
userdir processes the 100 largest rooms without a pause

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#4940]
... which may cause issues (says erik)

**Comment by neilisfragile** [comment]
Most background update tasks use number of rows as a proxy of work, this doesn't work for user dir because different rooms (rows) have multiple order of magnitude differences in the complexity to process.

The temp table does however include the state event number, so instead of using the total row count, instead sum the state events which is then a much closer proxy to complexity.

**Comment by hawkowl** [comment]
Fixed in https://github.com/matrix-org/synapse/pull/4944
