### ISSUE TITLE
The default federation ratecontrol limits may be too low for busy servers, and break badly.

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#4971]
/dev/ponies just reminded me that their server broke horribly a few months back with cryptic 4xx errors until we realised it was just ratelimiting traffic due to the federation RC limits being too low in the config.

Apparently their config is now:

> federation_rc_concurrent is up to 50 now and rc_reject_limit is up to 150, sleep delay decreased to 200, slimit limit upped to 50,

fwiw.

Is this also what's breaking OE?  Eitherway, we should presumably pick higher defaults, and/or fail more gracefully.

**Comment by ara4n** [comment]
(yes, it was what was breaking OE)

**Comment by turt2live** [comment]
(actually it was https://github.com/matrix-org/synapse/issues/3951, although this issue probably didn't help)

**Comment by DMRobertson** [comment]
The source code uses these defaults:

https://github.com/matrix-org/synapse/blob/b9778673587941277e15b067ad39cdf084f7dde5/synapse/config/ratelimiting.py#L36-L42

Matrix.org has a larger window size (10000 instead of 1000), but otherwise we are using the defaults.

> Is this also what's breaking OE?

No idea what OE stands for.



I suppose there's more we could do here:
- better admin visibility of when ratelimits are dropping requests (though I would hope there are 429 in the logs at least)
- some kind of backoff if a server responds with 429

But, lacking any specifics or further complaints, I'm inclined to close this issue. Happy to reopen if this is actively causing people pain.

**Comment by DMRobertson** [comment]
> some kind of backoff if a server responds with 429

better-covered by #5442, #8917 and probably others
