### ISSUE TITLE
If you redact a tombstone you can't join the room any more.

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#5003]
says linda

**Comment by anoadragon453** [comment]
So from investigation I've found that redacting a tombstone in an upgraded room:

* Still allows people who were in the old room to go back and look at it
* In Riot web, removes the link in the "This room is no longer active" dialogue:

![image](https://user-images.githubusercontent.com/1342360/55946514-c38f7100-5c44-11e9-882f-f20447731cec.png)

* Riot can't even show the new room for users who aren't in the old room. You click it in the room list and it highlights, but nothing else happens. Console logs:

![image](https://user-images.githubusercontent.com/1342360/55946992-97c0bb00-5c45-11e9-9a57-f463a9a6d7ac.png)

* If you invite the user to the old room they can join just fine, but they also have a broken upgrade message (no link to the new room)
* Once the user is in the old room, they can switch to the new room just fine.

So looks like we're looking at a few things here:

* A bug in Riot web that allows the option to redact tombstone events
* A bug in Synapse that allows you to redact tombstone events
* A bug in Riot web that breaks it if the user joins a room with a predecessor room ID, but the referenced room does not have a tombstone event.

The link to the new room disappearing makes sense since that uses information stored in the tombstone.

**Comment by richvdh** [comment]
I don't quite understand what the problem is here. What is the expected behaviour when redacting tombstone events?

**Comment by richvdh** [comment]
if anyone can clarify, we can reopen.

**Comment by altsalt** [comment]
I am currently seeking a way to revert a tombstone event and this was the closest issue I've yet found.

For background, I tried to upgrade a space by sending a post request to Synapse, however, it seems as though I can't join the new space and all matrix.to links re-direct to the old one.

I'm planning on deleting the space which was generated and resetting everything about the old space, but I don't want to do any of that until I can be sure that the tombstone event can be removed.

An empty m.room.tombstone event can't be sent, since tombstones require content. Also, the tombstone address can not be the same as the the room it is being sent to.

So to return to the question about "what is the expected behaviour" I'd expect the tombstone to be removed. However, to some of @anoadragon453 's points, is the ability to remove tombstones something that should be added to the spec or is it a bug to be able to do that at all?

Any direction towards fixes for my particular case would of course be appreciated as well!

**Comment by babolivier** [comment]
@altsalt It sounds to me like a good first step would be asking in [`#synapse:matrix.org`](https://matrix.to/#/#synapse:matrix.org) and see if the folks in there can't help you figure out if there's an easy way to fix your issue.

**Comment by altsalt** [comment]
Thanks @babolivier it appears that my particular issue comes down to poor handling of tombstones in spaces, which I can deal with rather than revert. That said, the larger question posed in this issue continues to seem relevant.

**Comment by anoadragon453** [comment]
related: https://github.com/matrix-org/matrix-doc/issues/1937
