### ISSUE TITLE
Self-signed TLS Warning even if no_tls: True

### ISSUE THREAD

**Issue by zwieberl** [matrix-org/synapse#5055]
### Description

Not sure if this is a bug or not.
I switched to a reverse proxy setup for the federation port and thus deactivated TLS completely in homeserver.yaml (`no_tls: True`).
On Startup of 0.99.3 I get the following warning:
```
twisted - 242 - WARNING -  - /home/matrix/synapse/env3/lib/python3.5/site-packages/synapse/config/tls.py:305: builtins.UserWarning: Self-signed TLS certificates will not be accepted by Synapse 1.0. Please either provide a valid certificate, or use Synapse's ACME support to provision one.
```

### Steps to reproduce

- Deactivate TLS in homeserver.yaml (`no_tls: True`)
- Startup synapse
- Check logs

### Expected
If no certs are being used, no warning about self-signed certs should be printed, I think.
<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: Self-hosted

If not matrix.org:

<!--
What version of Synapse is running?
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Version**: 0.99.3

- **Install method**: pip
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Raspbian
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment]
You'll only get this warning if you configure synapse to read the certificate file with a `tls_certificate_path` setting. If you don't want synapse to use TLS, you should leave this option unset.

It's also worth mentioning that, while `no_tls` will still work, it's somewhat deprecated. Just make sure that there are no `listeners` configured with `tls` enabled. The sample config contains more documentation: https://github.com/matrix-org/synapse/blob/v0.99.3/docs/sample_config.yaml#L165.

Closing this because AFAICT behaviour is as expected.
