### ISSUE TITLE
In iOS and using Librem One Chat images/files cannot be picked. 

### ISSUE THREAD

**Issue by CaptainKhan** [matrix-org/synapse#5143]
**Please add image and cloud store file picker function or API to Matrix if not already supported.**

**Comment by Half-Shot** [comment]
Hi there, this is the wrong repo for this bug. 
Purism maintain their own fork of Riot iOS, which can be found at https://source.puri.sm/liberty/chat/ios which I assume is where they also accept issues, but you should probably check with them to see where they want issues to be filed. Changes made to Rio
Synapse is a Matrix homesever and not related to Riot, or to Purism.

Separately, adding features to matrix should be suggested in https://github.com/matrix-org/matrix-doc/issues rather than in the synapse repo. The feature doesn't sound unreasonable, but this is the wrong place to request it :)
