### ISSUE TITLE
How to configure email settings in matrix server

### ISSUE THREAD

**Issue by AyoubGhaddab** [matrix-org/synapse#5172]
Hi,
I am new in matrix server and chat applications.
I am hosting a matrix server and a riot application on a server and i'am still getting riot branded emails, 
how can I configure to send mail via my homeserver smtp server,
Thank you.

**Comment by ukcb** [comment]
Look at the example https://github.com/matrix-org/synapse/blob/master/docs/sample_config.yaml#L894

**Comment by leprasmurf** [comment]
The example is a great starting point.  Are there any other configuration options?  Can I, for example, set an interval for emails?

e.g., "send a missed message email if user is offline for 15 minutes" vs "send a summary once a day"

**Comment by neilisfragile** [comment]
@leprasmurf I'm afraid that's your lot config wise as of right now. 

@AyoubGhaddab I think @ukcb answered your question (so will close) but the best place for support is #synapse:matrix.org

**Comment by vanovarderesyan** [comment]
Hi. I want to authenticate the registration process with email in order for users to get confirmation emails. Currently, I added the email field in the registration form, however, when the email is sent, It is not actually delivered. It shows Not Found error. Please, let me know what should  I setup in setting in order to solve this issue. Or if there is such an example, please, send me for checking. Thanks in advance.

**Comment by DMRobertson** [comment]
Hi @vanovarderesyan. Can you please open a new issue which includes the full "Not Found error"? Many thanks.
