### ISSUE TITLE
为什么以前执行生成配置文件的命令默认是开启8448端口的现在却只有8008端口默认开启，还有就是现在的配置文件内容与以前有很大差别

### ISSUE THREAD

**Issue by yang202** [matrix-org/synapse#5246]
### Steps to reproduce

- list the steps
- that reproduce the bug
- using hyphens as bullet points

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: 

If not matrix.org:

<!--
What version of Synapse is running?
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Version**: 

- **Install method**: 
<!-- examples: package manager/git clone/pip  -->

- **Platform**: 
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by uhoreg** [comment]
Google Translate says:

> Why did the previous command to generate the configuration file open the port 8448 by default, but only the port 8008 is enabled by default, and the content of the current configuration file is very different from the previous one.

**Comment by aaronraimist** [comment]
请参阅https://github.com/matrix-org/synapse/blob/master/INSTALL.md#tls-certificates。它以这种方式设置，因此您可以使用反向代理服务端口8448，因为您可能已经拥有TLS证书和Web服务器。另一种方法是让Synapse处理端口8448和TLS证书。你应该在`#synapse：matrix.org`而不是GitHub中提问。

See https://github.com/matrix-org/synapse/blob/master/INSTALL.md#tls-certificates. It is setup this way so you can use a reverse proxy to serve port 8448 since you probably already have TLS certificates and a web server. The alternative is to let Synapse handle port 8448 and the TLS certificates. You should ask questions in `#synapse:matrix.org` instead of GitHub.
