### ISSUE TITLE
Hi everyone: please use http://matrix.org/jira to file issues rather than here. Thanks!

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#54]

**Comment by thijstriemstra** [comment]
Here's the link you can click on: http://matrix.org/jira

**Comment by Osndok** [comment]
I hope you will reconsider. I know that filing report in JIRA might help your in-place workflow, but consider what it is like from "our side". For a github user that contributes to 100's of different projects, the cost difference between "zero" (if people use github to track issues) and "every project has their own mechanism and account credentials to store and recall"... is huge.

I have routinely passed on opportunities to contribute code, bug reports, and bug-fixes to various projects (even big-name projects) because the fix was easier than the increased and persistent overhead of adding one more account to keep track of, and the registration and dissemination associated therewith, or the subornation that might ensue.

IMO, the greatest feature of github is lowering the barrier to entry; in theory, I can fix a typo here... a missing null-pointer check there... an unforeseen edge-case over there... but when compared to this "social coding" paradigm of zero overhead ... a per-project registration might as well be a brick wall.

And I'm not alone... I believe it was on Coder Radio where the hosts agreed that even the initial registration overhead for ABRT ... which is supposed to make a vast array of bug reports possible with a single click .... is enough to keep them out. If even 1% of github users are similarly effected, you are literally missing out on hundreds of thousands of potential contributors.

I think that the "society" has a far greater inertia than you realize. It may be driven by human laziness, but how great is that laziness!

Thankfully, it seems that you have not disabled issue tracking in github, or you would not have received even this grand-and-important communication! :-)

Anyway... I hope that you might still consider github pull requests, as I had a few features in might that might integrate RetroShare ... which I think would be awesome... but I'll avoid filing a github feature tracker for it, to be in alignment with your wishes.

Best wishes!

**Comment by richvdh** [comment]
To be clear: we have nothing against github pull requests - they are very welcome! The request to file issues in Jira just concerns bug reports and feature requests.

So if you would like to contribute with a PR, that would be great!

**Comment by ara4n** [comment]
That said, we're also regretting using JIRA here rather than GH, and the plan is to migrate as many projects over to GH issues as possible as soon as possible.

**Comment by ara4n** [comment]
@Osndok - we considered; JIRA is dead; all the bugs live on Github forever more.  Closing this one up!
