### ISSUE TITLE
List all users on the same server

### ISSUE THREAD

**Issue by ChristianPauly** [matrix-org/synapse#5457]
**Description:**

The user may want to request a list of **all** users on a server. It looks like the path:
https://matrix.org/docs/spec/client_server/r0.5.0#post-matrix-client-r0-user-directory-search
requires a search_term and will never request all users. Can we make the search_term optional?

@jcgruenhage

**Comment by jcgruenhage** [comment]
To be a bit more specific, @ChristianPauly and me suggest that you can make the search term optional by modifying the config. There certainly are servers where listing all users is a privacy issue, but for company internal servers, this would be very useful.

**Comment by richvdh** [comment]
If you want a comprehensive list, then I'm not sure a search API (which will be backed by a search index) is the right way to go about it, not least because the search API is already a bit of a rat's nest of options.

I think a separate API would be better.

**Comment by neilisfragile** [comment]
Agreed on a separate API, we're currently working on improving our admin APIs for this sort of use case - I don't have an issue to point to yet but would expect some movement in the coming month (famous last words...)

**Comment by jcgruenhage** [comment]
This is not necessarily an admin API, in our usecase this is intended for regular users too.

**Comment by OloBo-MSK** [comment]
Any news?

**Comment by richvdh** [comment]
An admin user can list all users with registered accounts via the admin api, https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/user_admin_api.rst#list-accounts. 

The remainder of this issue seems to be asking for a way for regular users to be able to access a complete user list. I'm not sure what the usecase for this is, but it would need to be part of the spec. I suggest opening an issue at https://github.com/matrix-org/matrix-doc/issues including a description of the usecase.
