### ISSUE TITLE
Make homeservers able to handle registration-with-email without depending on an Identity Server

### ISSUE THREAD

**Issue by lampholder** [matrix-org/synapse#5751]
Ultimately we want to stop allowing third parties to use the Identity Servers at matrix.org and vector.im to send emails on their behalf for any reason.

**Comment by neilisfragile** [comment]
Will need a config option to preserve current behaviour

**Comment by lampholder** [comment]
I've been thinking a little more about whether the 'current behaviour' will represent a desirable state for any homeserver after this change.

The current behavior is that your homeserver will talk to whichever identity server your client tells it to (as long as it is on your whitelist), _except_ when deactivating your account (when it will communicate with whichever identity servers it knows were used to bind specific threepids).

For homeserver admins who want to send registration and password-reset emails via an identity server, it's likely that they will have a specific identity server/servers in mind (since it would be atypical for anyone running an Identity Server to accept mail-send requests on behalf of just anyone).

Would it make sense then for the homeserver configuration options to be one of either:
- Option A:
    - homeserver handles registration and password-reset emails itself
    - all identity activity is handled by the identity server specified by the client
- Option B:
    - homeserver delegates registration and password-reset emails to an identity server specified in homeserver config
    - all identity activity is handled by the identity server specified by the client

This would have no impact on the account deactivation behaviour.

It would also be nice if there were a way to query the homeserver's whitelist of identity servers (I think not being able to do this will result in some glitchy edge cases that are hard to detect and handle).

**Comment by lampholder** [comment]
Having thought about this some more I think ^ is a great idea.

We should make it as clear as possible that the homeserver handles registration and password reset emails by itself, unless an `account_threepid_delegate` is specified in the `homeserver.yaml`. This `account_threepid_delegate` will _probably_ be an Identity Server (though it could be any service that exposes registration and password-reset APIs).

Specifying an `account_threepid_delegate` will have no bearing on any other aspect of the system's interaction with identity servers. Lookups/invites will still be processed by whichever IS the client has asked the HS to communicate with on its behalf.

**Comment by anoadragon453** [comment]
Is there a case where someone would want registration emails to be handled by the IS but the HS handles password resets?

**Comment by anoadragon453** [comment]
> Lookups/invites will still be processed by whichever IS the client has asked the HS to communicate with on its behalf.

This is still filtered by the HS's whitelist, correct?

**Comment by anoadragon453** [comment]
Interestingly, `/register` already has a `bind_email` parameter. Have we taken this into account?

The homeserver should still handle the email sending based on a HS option though.

**Comment by anoadragon453** [comment]
Synapse currently has an `email.trust_identity_server_for_password_resets` option which is `false` by default.

So if we're going with the above solution, in that the IS is getting decoupled from sending registration emails/texts, then `email.trust_identity_server_for_password_resets` should probably be dropped from the config, and instead replaced with `account_threepid_delegate` above, which would default to `None`.

**Comment by anoadragon453** [comment]
I'm currently trying to make `account_threepid_delegate` define the identity server address for use with account registration and password resets, however the client currently sends `id_server` as a field to the homeserver to specify which IS to bind with.

Should we just override this value?

Also https://github.com/matrix-org/synapse/blob/4806651744616bf48abf408034ab9560e33f60ce/synapse/handlers/register.py#L760 currently looks broken because it takes in a `threepid` object which would never have a `threepid_creds` key.

**Comment by anoadragon453** [comment]
So we're going to go with having `account_threepid_delegate` be a string stating which one identity server you trust to handle password resets and registration emails.

If it's set, account/password resets will go through that set identity server. if it's not, then the HS will handle everything. `id_server` on `/_matrix/client/r0/account/password/email/requestToken` and `/_matrix/client/r0/register/email/requestToken` will be completely ignored.

We'd need to update the spec to reflect this.

This also means we can get rid of the server's identity server whitelist, since that was a weak attempt at preventing users from using malicious identity servers which could do nasty things with password resets.

The only place where `id_server` will still matter is `/_matrix/client/r0/account/3pid/email/requestToken`, where the user will be choosing which IS to bind with. We're not touching this endpoint at the moment.

Also `/_matrix/client/r0/register/email|msisdn/requestToken` and `/_matrix/client/r0/account/3pid/email|msisdn/requestToken` in the spec are functionally the same and the former should be removed.

**Comment by dbkr** [comment]
The thing you're going to run into is that only the v1 endpoint of an IS will let you call `requestToken` without an account that's signed the terms, and the plan is to disable the v1 API, so `account_threepid_delegate` will essentially need to point to an *old* IS.

> Also /_matrix/client/r0/register/email|msisdn/requestToken and /_matrix/client/r0/account/3pid/email|msisdn/requestToken in the spec are functionally the same and the former should be removed.

Actually now they're probably more relevant since a HS could send different emails depending on what the user was trying to do.

**Comment by anoadragon453** [comment]
>> Also /_matrix/client/r0/register/email|msisdn/requestToken and /_matrix/client/r0/account/3pid/email|msisdn/requestToken in the spec are functionally the same and the former should be removed.

> Actually now they're probably more relevant since a HS could send different emails depending on what the user was trying to do.

Well one would be the IS sending an email, and the other being the HS sending an email, so you could put different things in the emails that way, no?

**Comment by anoadragon453** [comment]
> The thing you're going to run into is that only the v1 endpoint of an IS will let you call requestToken without an account that's signed the terms, and the plan is to disable the v1 API, so account_threepid_delegate will essentially need to point to an old IS.

Right... so we can't delegate sending registration emails via the IS anymore.

So this option would only be useful for password resets, but I don't really think anyone in their right mind would want to do homeserver password resets through an IS. So... should we just ditch homeserver's calling to IS' for registration/password resets altogether?

**Comment by dbkr** [comment]
> Well one would be the IS sending an email, and the other being the HS sending an email, so you could put different things in the emails that way, no?

Doesn't that mean they're not the same? But yes,`register/email/requestToken` will be the HS sending the email, `account/3pid/email/requestToken` will be the IS (for now at least).

> So this option would only be useful for password resets, but I don't really think anyone in their right mind would want to do homeserver password resets through an IS. So... should we just ditch homeserver's calling to IS' for registration/password resets altogether?

I think we'd already decided to ditch it for registration (although I don't know if that was before we decided on the `account_threepid_delegate` thing). Either way, wfm but it's not really my decision. :)

**Comment by anoadragon453** [comment]
After a meeting IRL, we're keeping `account_threepid_delegate` around but must be clear it is only for use with identity servers which support the v1 endpoints (as the v2 `/register` endpoint will require authentication). We might also rename this option to something else. What do you think @lampholder?

We also need to be very clear during the next Synapse update that homeserver admins are aware of this, as to avoid confusing them when we remove `trust_identity_server_for_password_resets`.

**Comment by richvdh** [comment]
this is now fixed, thanks to #6011 and all the other PRs which have formed the epic privacy project :tada:
