### ISSUE TITLE
Use account_threepid_delegate for sending SMS

### ISSUE THREAD

**Issue by dbkr** [matrix-org/synapse#5929]
Do equivalent to what we've done for email, ie. use the `account_threepid_delegate` to send sms and don't require the client to send an `id_server` param to `/msisdn/requestToken`. Hopefully the `m.require_identity_server` flag can be re-used to signal to the client that an `id_server` is not required for msisdn token request (apart from for binding, as with email).

Unsure how much of this is already done.

**Comment by anoadragon453** [comment]
I think this issue is a bit out of date and has some misinformation in it.

The current state is that we have an `account_threepid_delegates` dict with `email` and `msisdn` keys. If `msisdn` is set to a domain name, `msisdn`-related requests are sent via that domain. If it's empty, all `msisdn`- related tasks return an error stating that the homeserver does not support this.

**Comment by anoadragon453** [comment]
Closing this for now.
