### ISSUE TITLE
Extremities dummy event came down sync

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#6174]
### Description

I received a `org.matrix.dummy_event` down sync which isn't supposed to happen.

```
{
    "type": "org.matrix.dummy_event",
    "sender": "@andrewm:amorgan.xyz",
    "content": {},
    "event_id": "$15704495153065cWESB:amorgan.xyz",
    "origin_server_ts": 1570449515558,
    "unsigned": {
        "age": 2338
    },
    "room_id": "!UwfyezyoefyCIPOOXS:matrix.org"
}
```

Not seeing anything in the homeserver logs about it.

### Version information

- **Homeserver**: amorgan.xyz

If not matrix.org:

- **Version**: v1.4.0

- **Install method**: pip

- **Platform**: debian stretch

**Comment by richvdh** [comment]
isn't it? I thought this was expected. I see them all the time.

**Comment by anoadragon453** [comment]
@erikjohnston claims otherwise

**Comment by benparsons** [comment]
Is <https://github.com/matrix-org/synapse/blob/master/synapse/handlers/message.py#L901> the only use-case for these events?

Would be good to create a document explaining these events because I've just started seeing them *from* my own server (which is weird to witness) and couldn't find anything else.

**Comment by babolivier** [comment]
It looks like a simple enough fix would just be to filter them out in [`filter_events_for_client`](https://github.com/matrix-org/synapse/blob/509e381afa8c656e72f5fef3d651a9819794174a/synapse/visibility.py#L46).

> isn't it? I thought this was expected. I see them all the time.

imho it results in a pretty crappy UX since it means events from X weeks ago can appear randomly in the middle of a convo happening today and "split" the timeline.

**Comment by babolivier** [comment]
Fixed in https://github.com/matrix-org/synapse/pull/7035
