### ISSUE TITLE
Disable user registration by default

### ISSUE THREAD

**Issue by ge0rg** [matrix-org/synapse#6350]
Related to #6348.

I've stumbled over the following in your last blog post:

> please also remember to turn off public registration on your homeserver. Otherwise even with
the changes above, if randoms can sign up on your server to view & join rooms then all bets are
off.

Please urgently make that setting disabled by default in synapse, otherwise you'll end up with an ecosystem of abandoned home servers used by spammers. BTDT in the XMPP world.

Ideally, a server admin should have a way to hand out registration tokens to potential users, or perform registration on their behalf. Otherwise, homeserver admins will be inclined to just enable self-registration and the final effect will be the same.

Number of XMPP servers I've received spam from in the last 14 days: 104.

**Comment by babolivier** [comment]
> Please urgently make that setting disabled by default in synapse, otherwise you'll end up with an ecosystem of abandoned home servers used by spammers.

FWIW registration is already disabled by default on Synapse:

https://github.com/matrix-org/synapse/blob/46c12918add132d8d0cbb808b499c815e2745f72/synapse/config/registration.py#L85-L87

I believe the blog post referred to people who might have thought too quickly about it and enabled registration on their server and let it as is even though it might not be what they want on the longer term.

> Ideally, a server admin should have a way to hand out registration tokens to potential users, or perform registration on their behalf. Otherwise, homeserver admins will be inclined to just enable self-registration and the final effect will be the same.

This is already possible, by setting the configuration parameter `registration_shared_secret` in the configuration file:

https://github.com/matrix-org/synapse/blob/master/docs/sample_config.yaml#L890-L893

It can be used with the `register_new_matrix_user` script so that someone with terminal access to the homeserver's host can create new accounts: https://github.com/matrix-org/synapse/blob/7e179599848a1005f753a1ab58953107fc2540df/INSTALL.md#registering-a-user

This script is using the admin registration API documented here: https://github.com/matrix-org/synapse/blob/master/docs/admin_api/register_api.rst

**Comment by babolivier** [comment]
I believe I've answered your concerns, therefore I'm going to close this issue. If you have further concerns, feel free to mention them in the Matrix room [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org?via=abolivier.bzh&via=privacytools.io&via=jaccu.se) :)

**Comment by Neustradamus** [comment]
@babolivier: For join it, the XMPP Bridge is operational?
https://github.com/matrix-org/matrix-bifrost/issues/73
