### ISSUE TITLE
Search failing with "unknown room" due to trying to search unknown predecessor room for the server

### ISSUE THREAD

**Issue by grinapo** [matrix-org/synapse#6356]
### Description
Searching a room for a string is failing in various (high traffic) rooms. 
The result is (example is for *Synapse admins*):

    {"errcode":"M_NOT_FOUND","error":"Unknown room !HsxjoYRFsDtWBgDQPh:matrix.org"}

for

     room_events: {search_term: "FUBAR", filter: {rooms: ["!mjbDjyNsRXndKLkHIe:matrix.org"]}, order_by: "recent",…}

Notice that the two room_ids are different.

### Steps to reproduce
- go to *Synapse admins* room in RiotWeb (or actually a dozen different ones)
- Search for anything
- get weird error

### Version information
- **Homeserver**:
If not matrix.org: grin.hu

- **Version**:
    "python_version": "3.7.3",
    "server_version": "1.5.0"

- **Install method**:
Debian

- **Platform**:
Debian/buster

**Comment by grinapo** [comment]
As turned out: The "illegal" id is the old (tombstoned) version of the room. However my homeserver is unaware of its existance, can't join it, etc.

**Comment by babolivier** [comment]
More context on this, what seems to happen is that the homeserver realises that it's an upgraded room, therefore tries to look at its previous version, which it knows nothing about since it's not in it and had apparently never been (no row in `rooms` nor `events` for this room ID in the database), but fails to join it for some reason.

When searching, we should make Synapse stop the search and return the results it has if that kind of scenario happens.

**Comment by grinapo** [comment]
So:
* old room was tombstoned and upgraded to new version
* my homeserver does not have anything from the old room, no events
* I have the room creation event

Then
* search seem to try to find the old room_id, tries to search it, see no event or really nothing at all for that
* fails.

**Comment by anoadragon453** [comment]
Fixed by https://github.com/matrix-org/synapse/pull/6385
