### ISSUE TITLE
Make power level defaults for new rooms configurable

### ISSUE THREAD

**Issue by benparsons** [matrix-org/synapse#6660]
**Description:**

Power levels for new rooms are hardcoded (https://github.com/matrix-org/synapse/blob/master/synapse/handlers/room.py#L780), this could be configurable.

**Comment by clokep** [comment]
Permalink to the code: https://github.com/matrix-org/synapse/blob/890c0c041d2d7f84525ad2031caabc74af9feba7/synapse/handlers/room.py#L828-L847

**Comment by tutosfaciles48** [comment]
In order to achieve that, I think we only have to change few files:

synapse/api/auth.py:
`    async def is_room_admin(self, user: UserID, room: RoomID) -> bool:
        """ Check if the given user is a local group admin.

        Args:
            user: user to check
            room: current room

        Returns:
            True if the user is an room admin
        """
        return await self.store.is_room_admin(user, room)`

(L 522, after is_server_admin function)

and registration.py (storage/data_stores/main):
`    async def is_room_admin(self, user, room):
        """Determines if a user is an admin of this room .

        Args:
            user (UserID): user ID of the user to test

        Returns (bool):
            true if the user is a room admin, false otherwise.
        """
        return ... (similary to is_server_admin db request)`

(L 294, after is_server_admin func)

If somebody is interested

**Comment by benparsons** [comment]
Just been discussing with a user who is really missing this feature.

**Comment by anoadragon453** [comment]
Note that this can currently be achieved through use of a pluggable ThirdPartyEventRules module. An example of such a module doing exactly this currently exists [here](https://github.com/matrix-org/synapse-dinsic/blob/0ebdde87399e4195b0f385f7f2511ef16893b07b/synapse/third_party_rules/access_rules.py#L229-L234). 

The definition of ThirdPartyEventRules is [here](https://github.com/matrix-org/synapse/blob/develop/synapse/events/third_party_rules.py), and can be configured in Synapse [via the homeserver config file](https://github.com/matrix-org/synapse/blob/66f75c5b74196c624af6a39d824c93b4a37d63c2/docs/sample_config.yaml#L2500-L2510).

How this works is that ThirdPartyEventRules modules can implement a method called `on_create_room`. Passed to this method is a `config` dict for the room. Setting the `power_level_content_override` key of this dictionary will set the initial power levels for the room. Simply override `on_create_room`, set `power_level_content_override` to whatever you like, and then all new rooms will have those power levels.

You can of course also set different power levels depending on other things set in `config`, such as the room's preset (`config["preset"]`) or other events in `config["initial_state"]`.

**Comment by reech** [comment]
So how would this work with official Synapse Docker image without actually maintaining a custom Synapse image ourselves? 

At runtime we can pass either environment variables or a config fragment via command line args  [https://github.com/matrix-org/synapse/pull/8390](#8390). It seems to me that, in regards to power-levels, to hardcode handlers/room.py is easier since we would need to maintain a custom image in either case? 

So is there a way to actually map a ThirdPartyEventRules python file into the container? Pass a PYTHONPATH environment var with an extra/merged file location which then can be referenced from homeserver.yaml, for example:

```
third_party_event_rules:
  module: "ThirdPartyEventRules_VOLUME_MAPPED_FOLDER.access_rules"
```

**Comment by Mikaela** [comment]
Is this still planned? Both `z-p1` and `z-enhancement` labels appear to be deprecated.

Changing default power levels without having to maintain a fork of Synapse would be helpful towards staying up-to-date and a couple of Finnish communities were discussing earlier today that if they could set their homeservers to give room creator power level 101 instead of 100 would help with trouble with bridges and similar taking PL100 for themselves.

I don't think there is basis for changing it globally (at least without further testing in practice), but that is one example of a case where changing default power levels in Synapse config would be helpful. Others include e.g. giving managed-server server-wide Mjolnir power level.

**Comment by anoadragon453** [comment]
After some [discussion in #synapse-dev](https://matrix.to/#/!XaqDhxuTIlvldquJaV:matrix.org/$hOfCU3NhItRoCMcxXSUmckKOTCB0SGDZfZrWA4oEK18?via=matrix.org&via=element.io&via=vector.modular.im), we're reluctant to add yet another config option for overriding the default power levels in a room, while doing so is possible via a Synapse module. Modules can also inject any events into a room when it is created, affording further flexibility than only `m.room.power_levels` events.

In terms of the difficulty of [using modules with docker](https://github.com/matrix-org/synapse/issues/9944) and with debian, making this easier would have a highly positive impact, and help in this instance.

Personally, for convenience, it may be nice to have a generic Synapse module which can be configured to inject any type of event into newly created rooms - perhaps even with rules on what rooms should and shouldn't be modified.

---

As for how to actually accomplish this with the module system today, you will want to write one (perhaps using [our module template](https://github.com/matrix-org/synapse-module-cookiecutter-template), also see the [writing a module](https://matrix-org.github.io/synapse/develop/modules/writing_a_module.html) documentation) that makes use of the [on_create_room](https://matrix-org.github.io/synapse/develop/modules/third_party_rules_callbacks.html#on_create_room) module callback.

This callback runs when a room is created, is passed a `request_content` dictionary, to which a `power_level_content_override` key can be added/modified, with a value containing new power level rules. The content of this dictionary should match that of the `power_level_content_override` argument to [/_matrix/client/v3/createRoom](https://spec.matrix.org/v1.2/client-server-api/#post_matrixclientv3createroom).

An example of a Synapse module that does this already can be found [here](https://github.com/vector-im/synapse-room-access-rules/blob/996dec76b6fecb496d962b780a6676512dd9c8b4/room_access_rules/__init__.py#L251-L253).

Alternatively, any event(s) can be injected into a newly created room by modifying the `initial_state` attribute of `request_content`.
