### ISSUE TITLE
We should surely be logging requests when they come in.

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#7064]
http://github.com/matrix-org/synapse/pull/6862 moves the 'received request' logline to debug log level. As a result, you can no longer see when requests are coming in and stacking up without being processed (which historically has been a very common failure mode in Synapse, as things get stuck behind a lock or lineariser or whatever), given it could be tens of minutes before the processed logline appears, and you no longer have any way to see the request come in.  You also can no longer read the log lines chronologically - you get random information about a request which is in progress without actually knowing what the request was... until it completes (assuming it gets stuck).  I am very surprised at https://github.com/matrix-org/synapse/pull/6862/files#r375819342, and would love to know why this is considered the 'right choice'.

**Comment by richvdh** [comment]
This was done as part of a set of work in removing the amount of stuff that synapse logs out of the box.

We've had consistent feedback that synapse logs so much in its default configuration that it is impossible to manage, to the extent that people recommend immediately turning the log level down to WARN, and downstream package maintainers ship configurations which do likewise. We then have no chance of debugging *anything*. Fundamentally: as a development team, we've spent too long dumping out frequent log lines "in case they are useful" rather than really considering what is necessary. We need to revisit this as part of building a mature product rather than a proof-of-concept for use by developers and early adopters.

So: the synapse dev team agreed to spend some time reducing the amount of duplicate and redundant information that is logged, hence #6862. 

As for whether the 'received request' lines were worth keeping despite all that: I'd argue heavily against it. They were a significant source of duplication, and I don't think we should be logging multiple lines for each request.

In the default configuration, we should be looking to log summaries that allow us to gain insights into what happened during an operation, rather than logging every single step of that operation. If you have reason to believe that is insufficient - for example, you suspect requests are backing up behind a lineariser - then we can enable DEBUG logging for relevant modules.

**Comment by ara4n** [comment]
Totally agreed that we log too much, and agreed that reducing unnecessary log volume is a good idea.

However, correlating Received versus Processed loglines has always been my first port of call when debugging overloaded Synapse issues over the years - and has consistently been incredibly useful to see when requests are stacking up, and so that one has a clear start/end to a request when reading how a given request misbehaved.  I am incredibly surprised that others aren't finding this too.

Also, back when debugging Apache and other servers which only log when requests complete, I've personally found it confusing and frustrating to only get the end of the request, rather than having a clear record chronologically of what came in, and what went out.

**Comment by erikjohnston** [comment]
The problem is that the `Received` log lines are a huge percentage of the total volume of logs, anywhere from 30-50%. If we don't turn off those log lines then there really isn't a huge amount of point trying to reduce anything else either; I don't think people aren't interested in 5% smaller log files.

So in the end this becomes a trade off between making `Received` log lines DEBUG or continue to have people recommend changing log level to WARNING.

A more general point here is that there is a difference between debugging historic problems (e.g. I tried to do X a few hours ago and it didn't work) vs debugging ongoing performance problems. For the latter we have Prometheus metrics and the ability to hot reload the log config to change log levels, which is hopefully enough to debug problems that would otherwise be caught with `Received` log lines.

**Comment by neilisfragile** [comment]
@ara4n given the above minded to close - please reopen if you want to continue the conversation.
