### ISSUE TITLE
Push notifications `unread count` is always set to 1.

### ISSUE THREAD

**Issue by lampholder** [matrix-org/synapse#7100]
This was reported by a third party and I _believe_ verified in a discussion I had with somebody from the mobile team (I didn't get around to filing an issue before and I'm afraid I forgot who I discussed this with).

It seems that this doesn't cause any problem for the Riot mobile apps because they don't rely on this value.

I didn't know whether this was a Sygnal or Synapse issue, so I've filed it here :)

**Comment by richvdh** [comment]
is this a longstanding bug, or something that has regressed recently?

**Comment by byanes** [comment]
I can confirm this has been happening for at least a few months.

**Comment by lampholder** [comment]
I have no reason to think this is a recent regression (it could always have been this way).

**Comment by anoadragon453** [comment]
If I understand this issue correctly, the problem is that iOS and Android devices are getting JSON blobs from Apple/Google that look something like the following:

```

{
  "notification": {
    "event_id": "$3957tyerfgewrf384",
    "room_id": "!slw48wfj34rtnrf:example.com",
    "type": "m.room.message",
    "sender": "@exampleuser:matrix.org",
    "sender_display_name": "Major Tom",
    "room_name": "Mission Control",
    "room_alias": "#exampleroom:matrix.org",
    "prio": "high",
    "content": {
      "msgtype": "m.text",
      "body": "I'm floating in a most peculiar way."
    },
    "counts": {
      "unread": 1,  # This is 1 no matter what
      "missed_calls": 1
    },
    "devices": [
      {
        "app_id": "org.matrix.matrixConsole.ios",
        "pushkey": "V2h5IG9uIGVhcnRoIGRpZCB5b3UgZGVjb2RlIHRoaXM/",
        "pushkey_ts": 12345678,
        "data": {},
        "tweaks": {
          "sound": "bing"
        }
      }
    ]
  }
}
```

Taken from https://matrix.org/docs/spec/push_gateway/r0.1.1#post-matrix-push-v1-notify

Inspecting a local synapse, I can see it stores non-1 unread counts per room in `event_push_summary`.

```
matrix=> select notif_count from event_push_summary limit 10;
 notif_count 
-------------
           3
           1
           3
           1
           1
           1
           1
           6
           1
           2
(10 rows)

matrix=> 
```

I'll need to set up a testing environment for this. I'll start with Synapse just pushing to a generic python webapp and see if it's sending the right stuff, but in terms of a full test environment, am I correct in thinking that I need a:

* Synapse
* Sygnal
* GPlay dev account
* Forked version of Riot(X) Android

to test this? Perhaps I can work with a mobile dev to complete the chain?

**Comment by anoadragon453** [comment]
I set up a testing device and logged out requests to push gateways.

The following bit of JSON was sent from Synapse -> Sygnal: `'counts': {'unread': 7}, `.

Looks like this my in fact be a Sygnal problem. Investigating that next.

**Comment by anoadragon453** [comment]
Sent a test message though a local Sygnal and it tried to send the following to GCM's servers:

```
{
  "data": {
    "event_id": "$1y4HWcK7s4J75ZCSxMqFk04_RNNRlnNoRHuLu0f-srY",
    "type": "m.room.message",
    "sender": "@_discordpuppet2_1_247199066944145057:amorgan.xyz",
    "room_name": null,
    "room_alias": null,
    "membership": null,
    "sender_display_name": "Guy",
    "content": {
      "msgtype": "m.text",
      "body": "hello",
      "source": "discord",
      "format": "org.matrix.custom.html"
    },
    "room_id": "!bla:amorgan.xyz",
    "prio": "high",
    "unread": 59,
    "missed_calls": null
  },
  "priority": "high",
  "to": "Zmx1ZmZ5Y1hhdC5jaHJpc3RpYW5wYXVseV9mbHVmZnljaGF0OjpCUTZhMTcwN3JmSDN4TjlUMlJFakw1U2xQdTRkTmtwZmFCOUFRUT09"
}
```

...which looks correct to me. Can a mobile dev provide me an example dump of the data they're receiving? Perhaps it's going through a code path I'm not seeing.

Also Synapse sends unread counts for the *amount of unread rooms*, rather than the amount of unread *messages*. Ensure you're testing with at least two rooms with unread messages.

**Comment by anoadragon453** [comment]
Example from an APNS request:

```
{
  "room_id": "!bla:amorgan.xyz",
  "aps": {
    "alert": {
      "loc-key": "MSG_FROM_USER_WITH_CONTENT",
      "loc-args": [
        "Guy",
        "hello"
      ]
    },
    "badge": 59,
    "content-available": 1
  }
}
```

**Comment by anoadragon453** [comment]
@BillCarsonFr and I just tested this out with the latest build of RiotX and got the following JSON blob to the client:

```
 {unread=2, prio=high, event_id=$ki361XmEED1EjxzYtEccSCTJARG-nUvjtUnFAJBYfac, room_id=!TDAtCmtSLiiGjPOZfU:amorgan.xyz}
```

for an account that has 2 unread rooms. We don't seem to be able to reproduce this bug, unless it's only present on iOS?

**Comment by lampholder** [comment]
It's very likely the third party was using iOS (they develop a client for android and iOS but I think they lead with iOS dev)

**Comment by anoadragon453** [comment]
Ok, will check iOS tomorrow then.

**Comment by anoadragon453** [comment]
We've now tested iOS and are seeing a non-1 `"unread_count"` field:

```
2020-04-08 14:53:01.070 Riot[40864:9780614] [AppDelegate][Push] didReceiveIncomingPushWithPayload: applicationState: 2 - type: PKPushTypeVoIP - payload: {
    "event_id" = "$EkkVndQyCUnt5LPoY-YtEsp0KdQ2zwx8lt44R7IMtLo";
    "room_id" = "!ORzgaaFwYQaNxwYWds:matrix.org";
    "unread_count" = 57;
}
```

I'll stop investigating now unless I can get a clear example of it not working.

**Comment by lampholder** [comment]
@byanes - can you provide any more details on how you experienced this issue?

I'm following up with the person who originally reported this to me, too.

**Comment by richvdh** [comment]
sounds like this is behaving as expected.
