### ISSUE TITLE
Support for message to a room, without joining it

### ISSUE THREAD

**Issue by David100mark** [matrix-org/synapse#7129]
Using Matrix for communication is really fantastic!
We use it for our organisation and completly migrated from other messaging-services to Matrix.
We often assign tasks to a group of people, which then create a room for the conversation.
If you want to pass a information to all of them, by now you have to write individual messages to everyone - not very convenient.
I would love to see an option which allows you to turn on direct messages to a room.
An answer to the message (by using the answer button) should then be directed to the original writer.

Thanks a lot!

**Comment by anoadragon453** [comment]
Thanks for using Matrix! However being able to send messages into a room without joining it is against the fundamental model of Matrix, and unlikely to happen anytime soon.

May I suggest restructuring your rooms a bit to allow this instead? You say that you create a room for a group of people for a task, and that to send those people a message you must message each of them individually. Could you not just send a message in the room they're all in? If the problem is that you want to send a message in that room without joining... why not just join it?

It's worth noting that the ability to do actions with a set of users rather than just one at a time should be vastly improved once [Communities v2](https://github.com/matrix-org/matrix-doc/pull/1772) comes about, which isn't long now.

But as for now, we won't allow sending messages into rooms without first being in them.

**Comment by babolivier** [comment]
@David100mark I think [server notices](https://github.com/matrix-org/synapse/blob/master/docs/server_notices.md) (i.e. the ability for a server admin to message every user on the server) might be another way of solving your issue.

**Comment by bpcurse** [comment]
@anoadragon453 I think the use case might have not been described detailed enough.

What hasn't been possible in Matrix until now (without using bridges like email and AFAIK) is to have a room where confidential information is discussed (therefore joining the room for others is out of scope) and still have other users enabled to contact that group (e.g. for a proposal), without creating another room.

@babolivier server notices does not help in this case either

**Comment by anoadragon453** [comment]
As yes, the idea of write-only rooms (or revoking the ability to read messages of a room for certain users) has been discussed before but currently there aren't any concrete plans towards them.

As far as I know there isn't a [Matrix Spec Proposal](https://matrix.org/docs/spec/proposals) for them either yet, however that would be where to start for someone wanting to implement this.
