### ISSUE TITLE
sending to_device messages seems to be much much slower than normal messages on matrix.org

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#7205]
E2E message sending has been incredibly slow over the last few weeks on Matrix.org - this looks to be due to to_device messages taking disproportionately long relative to normal messages - e.g. 10-20s to send to_device versus 2-3s to send normal messages.  For instance, here are the timings of me (see last column for durations) trying to send to_device messages last time I was investigating this:

<img width="1038" alt="Screenshot 2020-03-24 at 17 14 57" src="https://user-images.githubusercontent.com/1294269/78249245-f1209a80-74e5-11ea-9b5e-0c8fe3bbe293.png">

It's not just me seeing this:

<img width="856" alt="Screenshot 2020-04-02 at 13 27 46" src="https://user-images.githubusercontent.com/1294269/78249149-c7677380-74e5-11ea-9481-373bcd38c9c1.png">

**Comment by neilisfragile** [comment]
This is especially important in the context of cross signing UX, since it is one of the first things that the user encounters.

At the very least it would be good to understand if there is a recent regression causing the slowness.

**Comment by neilisfragile** [comment]
The way to repro is to have an end to end room 1:1  with multiple devices, discard a session and watch the network monitor, the PUT to ```to_device``` is very slow.

**Comment by babolivier** [comment]
FWIW it works in the same scenario but with an empty E2EE room with only you in there.

After investigating, it looks like this is because `sendToDevice` requests are going to the master. The master being overloaded, the request sits in the haproxy queue for 20s-30s until it haproxy manages to open a connection with the master.

I don't really know how we could address this, but then I'm not really familiar with worker setups and haproxy.

**Comment by richvdh** [comment]
For now we have set up a dedicated queue in haproxy for sendToDevice requests; hopefully that will mean that they can be handled more quickly.
