### ISSUE TITLE
Update turn documentation

### ISSUE THREAD

**Issue by ogarcia** [matrix-org/synapse#723]
I think that this documentation must be updated:
https://github.com/matrix-org/synapse/blob/master/docs/turn-howto.rst

**Comment by almereyda** [comment]
In which way would you expect it to change?

**Comment by ogarcia** [comment]
The links, for example, are outdated. And I think that need more explain, for example, when it talks about the turn_uris don't specify if this uris must be public or not.

IMHO, would have a full guided sample and do mention that coturn is packaged in most distributions.

**Comment by Zjemm** [comment]
agreed, same problems here

**Comment by MrCustomizer** [comment]
This is still very much an issue. I've tried for several hours now to get coturn up and running, but it just doesn't work. The biggest problems are the things @KlausHans mentioned. If you don't know how to test and troubleshoot the configuration, you are completely lost if it doesn't work right away.

**Comment by MrCustomizer** [comment]
I've figured out my problem and it hadn't anything to do with the coturn setup. So extended documentation on that end would probably not have helped in my case. I still think a little more advice in the README would be helpful for newcomers like me. The thing which got me confused most when first reading the file, was the fact that you need a separate a record domain (turn.myserver.org). I'm still not sure if it really is necessary.
The other thing is the part about blocking and allowing adresses. I'm assuming you only need to set the denied-peer-ip and allowed-peer-ip, if your turn server is behind a NAT. A sentence for clarification on the cases in which you need to or should set these settings would be nice.

**Comment by richvdh** [comment]
If people are aware of updates that are needed here, we would welcome pull requests.

> The links, for example, are outdated

I've skimmed through https://github.com/matrix-org/synapse/blob/master/docs/turn-howto.md and not found any broken links. Which did you have in mind?

> how do i know my configurations are correct?
how can i test coturn?
how can i test synapse is communicating with coturn?

Mostly I think #1519 would help here.

Anyway, the subject of this issue is "update turn documentation", and afaik it *is* up to date, so I'm going to close this issue.
