### ISSUE TITLE
rename username

### ISSUE THREAD

**Issue by helmut72** [matrix-org/synapse#7283]
**Description:**

Please add a feature to rename an username if the new username is free. At least for self hosted servers. If someone marries, she don't want to continue with her old name, but also don't want to lost her old chats.

Thank you

**Comment by richvdh** [comment]
This needs to wait for https://github.com/matrix-org/matrix-doc/pull/1228.

**Comment by Jieiku** [comment]
eeeeek I just setup my second matrix server, luckily I found this before doing anything with it. I just blew it away and reinstalled. Note to self, pick a good name you wont want to change.

**Comment by babolivier** [comment]
@Jieiku Please don't post in old closed issues since this will likely only create noise without solving any issue you might have (this is true in this case but also in the few other old issues you have replied to). If you need help with setting up Synapse, please ask in [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org), and if you want to report a new bug please open a new issue.

**Comment by Jieiku** [comment]
will do, generally when I open a new issue, people simply say, its a duplicate of such and such so close it.... so i generally dont get help either way. I posted here because this was relevant. I am assuming the answer is that you still cannot rename your username.

**Comment by babolivier** [comment]
> people simply say, its a duplicate of such and such so close it

This just means that someone already reported the bug you're trying to report, so the right course of action is to follow the resolution on there, and that if you have any more information to provide or discuss it should happen in that other report rather than on the issue you opened.

> I am assuming the answer is that you still cannot rename your username.

This is the case, yes. As Rich pointed out, this specific feature is blocked behind the MSC (Matrix Spec Change proposal) mentioned above, so the feature won't be available in Synapse until that MSC has been accepted and merged.

**Comment by ThiefMaster** [comment]
> If someone marries, she don't want to continue with her old name, but also don't want to lost her old chats.

That's the perfect example on why:

- changing names in marriage is dumb (but understandable at least if you like the other name better, but in other cases it's dumb)
- not using a NICKNAME as your online identifier is dumb - while you may also find a nickname you picked decades ago boring at some point, it's not something you're likely to change based on your relationship status :D
