### ISSUE TITLE
build debs for ubuntu 20.04

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7293]
focal fossa is being released on 2020-04-23 and is in RC currently; we should add it to the list of things we build debs for

**Comment by lightray22** [comment]
Possibly helpful tip - the existing eoan package can be forcibly installed on focal with only one issue.  Namely, python3-distutils has to be heldback at 3.7.5 rather than 3.8.2.  Focal uses Python 3.8 while matrix eoan apparently relies on 3.7.  Canonical has an issue in that python3-distutils probably should be separated into separate packages for 3.7/3.8 like python itself is on Ubuntu.  But, it's not, so upgrading to focal and then installing the eoan matrix package results in matrix not being able to start because it can't find distutils in the python 3.7 space, though Ubuntu knows to keep python 3.7 installed.

Long way of saying the focal package just needs to be updated to work with python 3.8.

**Comment by sj64** [comment]
Why has this been closed?
There is still no focal deb in dists

install fails:
admint@vultr:~# apt install matrix-synapse-py3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 matrix-synapse-py3 : Depends: python3.6 but it is not installable
                      Recommends: libpq5 (>= 10~~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by babolivier** [comment]
Hi @sj64, this issue hasn't been closed yet.

**Comment by sj64** [comment]
OK - apologies. My mistake, thought the red Closed flag above was for this thread! Good to hear.

**Comment by anchelnl** [comment]
Here also a fool who did do do-release-upgrade before checking package.

Got first :
May 11 13:12:39 dell matrix-synapse[1048]:     from distutils.util import strtobool
May 11 13:12:39 dell matrix-synapse[1048]: ModulqeNotFoundError: No module named 'distutils.util'

and after remove matrix-synapse-py3 and reinstall : 
 matrix-synapse-py3 : Depends: python3.7 but it is not installable

So waiting for focal in the package.

**Comment by lightray22** [comment]
That can be fixed with the workaround I mentioned, just find the eoan package for python3-distutils and downgrade it.

**Comment by richvdh** [comment]
well this turns out to be more of a PITA than expected: [dh-virtualenv](https://github.com/spotify/dh-virtualenv) (which we use to build the debs) seems to be basically unmaintained, and has dependencies which don't exist on focal :-S

**Comment by clokep** [comment]
I believe this is fixed by #7526.
