### ISSUE TITLE
populate_stats_process_rooms runs in the wrong order

### ISSUE THREAD

**Issue by michaelkaye** [matrix-org/synapse#7380]
Upgrading from a 1.0 synapse to the latest causes an issue where the `populate_stats_process_rooms` background task starts running immediately, however I believe it's actually requiring data that is changed as part of `current_state_events_membership` to function correctly.

i think there should be a dependency from `current_state_events_membership` to `populate_stats_process_rooms` to fix this, but there may also be others - is this something that needs to be thought about when choosing background updates' dependencies, i don't think they automatically wait until the ones from previous versions are run.

This isn't a problem when keeping up to date with synapse, but doing larger bulk updates can cause issues.

**Comment by richvdh** [comment]
just having a look at this

**Comment by richvdh** [comment]
We've tried to address this problem in the general case for future versions by making bg updates run in series rather than parallel, and by giving them a number (#7190). For existing updates, it's a bit hard to fix properly without spending a lot of time going through adding dependencies. I think it makes more sense to fix them where they are found.

In this case: did `populate_stats_process_rooms` fail, or did it run and do nothing? The former case is obviously much easier to fix retrospectively.

**Comment by richvdh** [comment]
> In this case: did populate_stats_process_rooms fail, or did it run and do nothing? 

It ran and did nothing.
