### ISSUE TITLE
Multiprocessing

### ISSUE THREAD

**Issue by vjoomens** [matrix-org/synapse#7522]
Hi,

I can't believe the synapse matrix server implementation still uses old school single processing instead of multi threading. Especially if you have a server with lots of users, you really need multi threading for performance.

I know, workers is a nice solution for horizontal scaling, but hey, most servers have multiple cores now and it would IMHO be a real shame not to use these. I'm not a python expert, but it seams to me that this should be a high priority requirement for an application like this, especially if you have lots of users.

Or did I miss something?

Cheers,

Victor.

**Comment by anoadragon453** [comment]
[Worker mode](https://github.com/matrix-org/synapse/blob/develop/docs/workers.md) does allow you to utilise multiple cores on your machine. You can run as many individual workers on your server as you have the resources for.

Multiprocess execution within a single instance of Python is not possible due to the [Global Interpreter Lock](https://docs.python.org/3/glossary.html#term-global-interpreter-lock).
