### ISSUE TITLE
Centos 7 dependencies need updating

### ISSUE THREAD

**Issue by yesennes** [matrix-org/synapse#7570]
### Description

Synapse needs `openssl` and `postgressql-devel` to run the unit tests, but the dependency list for Centos 7 doesn't include it.

### Steps to reproduce

Here's a docker file that reproduces the issue:

```
FROM centos:7

RUN yum install -y epel-release \
 && yum install -y libtiff-devel libjpeg-devel libzip-devel freetype-devel \
                 lcms2-devel libwebp-devel tcl-devel tk-devel redhat-rpm-config \
                 python3-virtualenv libffi-devel openssl-devel\
        wget \
 && yum groupinstall -y "Development Tools" \
 && pip3 install -U pip \
 && pip3 install -U virtualenv

RUN wget https://sqlite.org/2020/sqlite-tools-linux-x86-3310100.zip \
 && unzip sqlite-tools-linux-x86-*.zip \
 && mv /usr/bin/sqlite3 /usr/bin/sqlite3old \
 && cp sqlite-tools-linux-x86-*/sqlite3 /usr/bin/ \
 && yum install -y glibc zlib

RUN git clone https://github.com/matrix-org/synapse.git

WORKDIR /synapse

RUN virtualenv -p python3 env \
 && source env/bin/activate \
 && pip install --upgrade pip \
 && pip install --upgrade setuptools \
 && python -m pip install --no-use-pep517 -e .[all]

CMD source env/bin/activate \
&&  python -m twisted.trial tests
```

It would be nice if the dependencies listed everything necessary to run the unit tests.

### Version information

- **Homeserver**: self hosted

- **Version**: develop

- **Install method**:
 git clone

- **Platform**: Centos 7

**Comment by anoadragon453** [comment]
@yesennes Thank you for providing the docker image, it made it quite easy to test with :)

I seem to find that merely providing `postgresql-devel` allows the Dockerfile to compile. Adding `openssl` didn't seem to have an effect.

Where `postgresql-devel` is required is during the `pip` install, which in your example you've specified to use `.[all]`. This will install the postgresql dependencies as well, which is not what's recommended in the [CentOS installation instructions](https://github.com/matrix-org/synapse/blob/develop/INSTALL.md#centosfedora), but is what's recommended in the [postgresql DB guide](https://github.com/matrix-org/synapse/blob/develop/docs/postgres.md).

At this point the only actions forward at this point I can see is to add a section to the [postgresql DB guide](https://github.com/matrix-org/synapse/blob/develop/docs/postgres.md) that mentions that on CentOS/Fedora one needs to install `postgresql-devel`. What do you think?

**Comment by anoadragon453** [comment]
I've discovered recently that [we assume .[all] is required for unit tests](https://github.com/matrix-org/synapse/blob/2f6afdd8b45c27f30f91873ab3e42cf6ada7045a/synapse/python_dependencies.py#L98), so `postgresql-devel` should indeed be added if you want to run the unit tests.

However, the dependencies listed in [INSTALL.md](https://github.com/matrix-org/synapse/blob/develop/INSTALL.md#centosfedora) are intended for people setting up a server, rather than running unit tests.

I understand that people may want to do this, so I've proposed adding a "Running tests" section to `INSTALL.md`: https://github.com/matrix-org/synapse/issues/7759

I suggest we continue the conversation there as this is a problem that affects all platforms.
