### ISSUE TITLE
Handling of Chat Invitations

### ISSUE THREAD

**Issue by djschilling** [matrix-org/synapse#7572]
I am developing an app that uses matrix (sanypse) as chat backend.

Problem is the following:

1. Person A invites Person B to a Chat.
2. Person A leaves the chat room.
3. Person B still sees the chat invite and when trying to accept the chat invite the error `No known servers` occur.

I also tested that with Riot and it behaves the same so it is probably a synapse problem.

Person B does not get the information that Person A left the room and so i cannot really hide the chat room cause i have no information that Person A "refused" the chat invite.
Am i missing something here or is this a thing that cannot be accomplished currently with synapse?

**Comment by anoadragon453** [comment]
This is a known bug I'm afraid: https://github.com/matrix-org/synapse/issues/6902

It likely happens due to the room being deleted when everyone leaves it. The server no longer knows about the room and thus throws back "No known servers" at the user, as it was unable to find another server to contact to join this unknown room through.

Closing as a duplicate for now, please leave any other thoughts on the original issue.
