### ISSUE TITLE
Synapse uses unspecced URL to fetch remote media

### ISSUE THREAD

**Issue by neilalexander** [matrix-org/synapse#7707]
### Description

Synapse tries to fetch remote media using a non-specced `v1` URL `/_matrix/media/v1/download/`, instead of `/_matrix/media/r0/download/`.

### Steps to reproduce

Try to fetch remote media, e.g. `https://synapse.neilalexander.dev/_matrix/media/r0/download/dendrite.neilalexander.dev/_3aD3qpR-RhMj0D_IjYzIETXYQ3Ie4QgRbh557zGRXE`

`synapse.http.matrixfederationclient - 408 - INFO - GET-126607 - {GET-O-250358} [dendrite.neilalexander.dev] Sending request: GET matrix://dendrite.neilalexander.dev/_matrix/media/v1/download/dendrite.neilalexander.dev/_3aD3qpR-RhMj0D_IjYzIETXYQ3Ie4QgRbh557zGRXE?allow_remote=false; timeout 60.000000s`

### Version information

- **Homeserver**: Synapse

If not matrix.org:

- **Version**: 1.11.0, from docker image `matrixdotorg/synapse latest d64d49dfd131`

- **Install method**: Docker

- **Platform**: VMware Photon OS `Linux photon-machine 4.19.15-1.ph3-esx`

**Comment by clokep** [comment]
Note that it seems Synapse does server both the r0 and v1 versions, so that's good:

https://github.com/matrix-org/synapse/blob/bd6dc17221741d4ceae05ae769a70696ae939336/synapse/app/homeserver.py#L238-L240

(And this is since 737c4223ef25fd2856d0ff6cc111d14b19f1adec, so for a very long time.)

I suspect we can just update Synapse to use the proper r0 version.
