### ISSUE TITLE
Performance of device list updates could be improved (aka /login is unusably slow)

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#7721]
I was investigating why logging in with a new device was leading up to poor performances on my account. It seems like both sending the device list update to other homeservers and other homeservers in turn hitting `GET /_matrix/federation/v1/user/devices/{userId}`.

Looking a bit further, it looks like both code paths end up calling [`_get_e2e_device_keys_txn`](https://github.com/matrix-org/synapse/blob/bd6dc17221741d4ceae05ae769a70696ae939336/synapse/storage/data_stores/main/end_to_end_keys.py#L83-L175) in the database code, which seems to be pretty expensive, and is called multiple time in a row, yet isn't cached. This results in quite bad performances:

![image](https://user-images.githubusercontent.com/5547783/85020132-c8fd1b00-b167-11ea-8cad-c71dcf3bb75a.png)

On the bottom right graph the `_get_e2e_device_keys_txn` transaction (in blue) is originating from sending out the `m.device_list_update` EDUs, while the `get_devices_with_keys_by_user` one (in purple) is originating from responding to `GET /_matrix/federation/v1/user/devices/{userId}`. Both transactions involve calling the `_get_e2e_device_keys_txn` function (in fact, the first one does only that).
On the bottom left graph these two transactions are colored respectively in green and purple.

**Comment by erikjohnston** [comment]
I think the next steps here are to add a cache :+1:

**Comment by hifi** [comment]
In #12048 I had an issue where logging in with a new device pretty much kills synapse for a while because of the device notify on login. Just batching up and slowing down sending the notifies would help a lot.

**Comment by richvdh** [comment]
It's worth mentioning that this effectively prevents logging in with Hydrogen (cf https://github.com/vector-im/hydrogen-web/issues/699)

**Comment by richvdh** [comment]
oh, and fluffychat, which seems to do the same thing

**Comment by erikjohnston** [comment]
Oh, hmm. The problem described in the top of this issue (`_get_e2e_device_keys_txn` goes slow) and the slow login due to `/r0/keys/upload` may not have the same underlying cause. E.g. `/

Note that there seems to be two related but distinct problems:
1. `_get_e2e_device_keys_txn` is slow as mentioned in the issue description
2. `notify_device_updates` is slow

@richvdh ooi what were you seeing? Or was it a combination of the two?

**Comment by richvdh** [comment]
I was seeing all requests to my HS responding with a 502, due to my reverse-proxy timing out. The mean reactor tick time is about 15 seconds, which Synapse is essentially unable to respond to anything. I think it's very busy sending out federation updates.

**Comment by richvdh** [comment]
related: https://github.com/matrix-org/synapse/issues/5373

**Comment by hifi** [comment]
@erikjohnston In #12048 I disabled `notify_device_updates` temporarily and I could login just fine without delays and Synapse was chugging along without stalling.

**Comment by erikjohnston** [comment]
#12132 will hopefully help a bit here, as it smears out sending out device list updates a bit. However, it won't help for the other issues that we're seeing.

My current thinking is that we should  try and get rid of the use of `store.get_users_who_share_room_with_user` in `notify_device_update`, as that is expensive for larger accounts (both in CPU and memory terms). We can instead pull out the rooms for the user, which is enough to wake up the notifier. Then, instead of recording the device update per remote server, we store the device update per room. When the federation sender pulls out the device updates it can find the hosts in the room. 

This does lead to the same amount of work being done (as `self.store.get_users_who_share_room_with_user` effectively just does `get_rooms_for_user` followed by a loop of `get_users_in_room`), but has the advantage of:

1. a lot of the process happens asynchronously, so we can return the `/login` (or whatever) request sooner; and
2. the federation sender can prioritise which rooms and hosts to send out to first, e.g. it could handle rooms in order of when the last message was sent, so that we quickly get device updates to servers that we talk to frequently at the expense of servers that we haven't talked to for ages.

We can also do a vaguely similar thing for presence, i.e. get rid of `store.get_users_who_share_room_with_user`, which should help the perf overhead of presence.

**Comment by ara4n** [comment]
I literally can't log in any more thanks to this. It would be very much appreciated if this could be prioritised...

**Comment by erikjohnston** [comment]
1.58.0rc1 should now include the fix described in https://github.com/matrix-org/synapse/issues/7721#issuecomment-1059308602, so I think this is fixed from a user perspective. Logging in on a large account still takes a *lot* of CPU and DB though, so we may want to investigate that, but for now I think we can close this issue.
