### ISSUE TITLE
purge_events removes too many entries from `event_to_state_groups`?

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7729]
https://github.com/matrix-org/synapse/blob/91e886d615dd24ff0258e06470bca0cc8ffe22eb/synapse/storage/data_stores/main/purge_events.py#L196-L200 : Shouldn't the inner query be limited with where should_delete?

**Comment by erikjohnston** [comment]
No, I don't think so, the `should_delete` is saying that those events should be converted to outliers rather than outright deleted. This is so that we don't delete state events that we need, as well as optionally keeping local events (to enable others to fetch them if necessary). Outliers do not have state associated with them, so its safe to delete their state.
