### ISSUE TITLE
Unable to read a user's messages

### ISSUE THREAD

**Issue by TheEvilSkeleton** [matrix-org/synapse#7900]
### Steps to reproduce

Honestly, I have no idea how I can reproduce it.

## Describe the issue

- **Platform**: A container on a DigitalOcean k8s cluster.

---

EDIT: I've tried using another client (Fractal), but the issue persists.

**Comment by anoadragon453** [comment]
This is known and can be caused by a variety of different circumstances. We've fixed most of the edge cases in the past few months, but encryption errors (commonly referred to as UISIs) are still possible if something breaks in the chain, including most often, slow federation issues.

The best thing to do when encountering these issues is to submit a bug report from your Element app (or try to get whatever logs you can from other clients) citing [this issue](https://github.com/vector-im/riot-web/issues/2996). Someone from the team will then be able to walk back through what happened and perhaps eek out an actionable bug from it.

Please do that if you can (device logs stick around for a while in the Element clients, so may still be worth doing on the devices affected here), but otherwise this isn't actionable from the current information.

Report the logs and we'll open an issue if we find anything. Thanks :slightly_smiling_face:
