### ISSUE TITLE
Invalid signature for server tchncs.de

### ISSUE THREAD

**Issue by sl5net** [matrix-org/synapse#7903]
### Description

tried using element in Linux - Mint for chat to anoter person.

i get:

Failed to join room
Invalid signature for server tchncs.de with key ed25519:a_rOPL: Unable to verify signature for tchncs.de: <class 'nacl.exceptions.BadSignatureError'> Signature was forged or corrupt

### Version information

Element version: 1.7.1
olm version: 3.1.3

Identity Server is https://vector.im
Access Token: <click to reveal>
HomeServer tchncs.de

**Comment by anoadragon453** [comment]
I'm going to guess that this was due to a connection timeout rather than an issue with Synapse.

Looking at tchncs.de, their SSL certs seem up to date, and they are returning a response with `ed25519:a_rOPL` listed: https://tchncs.de:8448/_matrix/key/v2/server/

I recommend you ask again in [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org) if this is a recurring issue. That is where we and the team try to field support queries. Thanks!
