### ISSUE TITLE
`type` property missing for `m.reference` relations

### ISSUE THREAD

**Issue by joepie91** [matrix-org/synapse#7941]
I received the following event from Synapse for a bridged Telegram message:

```js
  {
    type: 'm.room.message',
    room_id: '!redacted:pixie.town',
    sender: '@telegram_redacted:pixie.town',
    content: {
      msgtype: 'm.text',
      body: 'redacted',
      external_url: 'https://t.me/c/redacted'
    },
    origin_server_ts: 1595536311000,
    unsigned: {
      age: 710692,
      'm.relations': {
        'm.reference': {
          chunk: [
            {
              event_id: '$redacted1'
            }
          ]
        }
      }
    },
    event_id: '$redacted2',
    user_id: '@telegram_redacted:pixie.town',
    age: 710692
  },
```

However, [MSC 1849](https://github.com/matrix-org/matrix-doc/blob/matthew/msc1849/proposals/1849-aggregations.md) says:

> m.reference list the event_id and event type of the events which reference that event.

... which implies that the server is *required* to provide the `type` property for the `m.reference` relation, but it is currently missing.

(I realize that the MSC hasn't been finalized and merged yet, but I'm filing an issue anyway to make sure it doesn't get overlooked later.)

**Comment by clokep** [comment]
Is this a bug with the Telegram bridge?

**Comment by joepie91** [comment]
As I understand it, the `m.relations` field is generated by the homeserver based on the related events that it is aware of, so that should be totally separate from any buggy clients/appservices.

(Though even if it were a buggy appservice, that would just make this an input validation issue!)

Anyway, seeing something similar for `origin_server_ts` in `m.annotation`, which is also missing:

```js
  {
    content: {
      body: 'redacted',
      msgtype: 'm.text'
    },
    origin_server_ts: 1595367512866,
    room_id: '!redacted:matrix.org',
    sender: '@redacted:example.com',
    type: 'm.room.message',
    unsigned: {
      age: 171403042,
      'm.relations': {
        'm.annotation': { chunk: [ { type: 'm.reaction', key: '💥', count: 1 } ] }
      }
    },
    event_id: '$redacted',
    user_id: '@redacted:example.com',
    age: 171403042
  },
```

The MSC is slightly less explicit about the requiredness of that one, though.

**Comment by jerinjtitus** [comment]
Can anyone help me, I was trying to find where percisely `m.relations` field is generated. I am not completely sure which one it is.

**Comment by clokep** [comment]
Looks like the code around this is at https://github.com/Yoric/synapse/blob/9dde9c9f01ff8ed4c60314f10d97261739ea0547/synapse/events/utils.py#L382-L393

**Comment by lukasdenk** [comment]
As statet by @joepie91:
>(I realize that the MSC hasn't been finalized and merged yet, but I'm filing an issue anyway to make sure it doesn't get overlooked later.)

the MSC specifying that an `m.reference` must contain a `type` is still a proposal. Furthermore, it seems like [MSC1849](https://github.com/matrix-org/matrix-doc/pull/1849) is split in several proposals (see e.g. [here](https://github.com/uhoreg/matrix-doc/blob/feb337739933461248241cca6c5d8b52d8110510/proposals/2674-event-relationships.md?plain=1#L6-L22)). The specification of event references seems to be handled in [MSC3267](https://github.com/matrix-org/matrix-doc/pull/3267). There, [the specification](https://github.com/matrix-org/matrix-doc/blob/ab551e86309f150150671f17ce9d84dbcdb45c2c/proposals/3267-reference-relations.md?plain=1#L18-L28) is different from this PR's description. 


@clokep Since [MSC3267](https://github.com/matrix-org/matrix-doc/pull/3267) is still ongoing work (more specifically, it has no [proposal lifetime state](https://spec.matrix.org/unstable/proposals/#lifetime-states) label), I would suggest to make clear that this issue should only be resolved after [MSC3267](https://github.com/matrix-org/matrix-doc/pull/3267) is accepted.

**Comment by clokep** [comment]
> Since [MSC3267](https://github.com/matrix-org/matrix-doc/pull/3267) is still ongoing work (more specifically, it has no [proposal lifetime state](https://spec.matrix.org/unstable/proposals/#lifetime-states) label), I would suggest to make clear that this issue should only be resolved after [MSC3267](https://github.com/matrix-org/matrix-doc/pull/3267) is accepted.

Yeah, the state of those MSCs is quite confusing; MSC3267 specifically says it doesn't declare a bundled aggregation format, but MSC2675 also doesn't declare one. (Note that MSC1849 is obsolete as you mention.)

I'll make a note on MSC3267 about this inconsistency, but for now I'm going to close this issue since it isn't clear it is a Synapse issue.
