### ISSUE TITLE
Speed problem in groups with a large number of members

### ISSUE THREAD

**Issue by aliirezaaa** [matrix-org/synapse#8381]
I had a group with 400 members and everything went well but when group members grew, a speed problem occurred on sending a message to the group.

now my group have 20,000 members and sending a message in it takes a long time (about 15 sec).

I tried to fix this problem by using workers and tuning Postgres but no effective changes happened.

Is there any solution to this problem?

my server configuration : 

cpu : 4 core 
ram : 4 GB
hdd: 25GB ssd

**Comment by anoadragon453** [comment]
Please ask for support in [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org) rather than the issue tracker. Thanks :slightly_smiling_face:

As a quick note however, the more servers you have in a room, the more connections your server will need to make to send a message. This often involves setting up a lot of SSL connections, which can be CPU heavy. This would occur on a single worker no matter how many federation senders you have, as they're sharded by room ID. Thus you may have to scale vertically here rather than horizontally to improve this particular usecase.
