### ISSUE TITLE
backoff should be tracked per-room rather than per-server?

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#8498]
it's quite possible for a server to struggle processing fed traffic for a given room, but be able to handle other rooms okay - particularly in a dendrite world where rooms could be on different room servers. we should track back-off per room

**Comment by richvdh** [comment]
I'm not really sure that servers struggling to process traffic is what backoff is designed for. I'd say it's up to the target server to decide whether to selectively drop traffic for particular rooms.

**Comment by ShadowJonathan** [comment]
Why would servers have different processing delays between different rooms on incoming federation? Besides, I don't think it's possible to selectively "withhold" "probable expensive events", as it is not the nature of a sending server to think about how an event might be perceived by the other server, their views could be very much different.

And besides, "waiting" for federation traffic to calm down to send event transactions doesn't make sense, unless it times out, all federation traffic is bound to have the same X amount of processing time if sent, you can be strategic and send only a batch of events from 1 room in 1 transaction, and a batch of events from another room in another transaction, but that makes delivery times very volatile, and it doesn't solve the underlying head-of-the-line blocking that happens when the target server is taking a bit longer to process the one event than it does for the other, before returning the `txn` HTTP response with all results, before the sending server can send another transaction (whats why [MSC 3005](https://github.com/matrix-org/matrix-doc/pull/3005) allows asynchronous acknowledgements)

**Comment by richvdh** [comment]
right, I don't think this is a thing that makes sense.
