### ISSUE TITLE
Option to disable voice- and video-calls between federated homeservers 

### ISSUE THREAD

**Issue by n3rdybyn47ur3** [matrix-org/synapse#8560]
We have one homeserver for our staff members and will have a second one for our students in the near future. Both servers will be federated to share rooms between staff and students. Calls between staff members should be possible. Calls between students should be ok too, but students trying to call staff members will cause some irritation.

Please consider an option to disable voip calls between federated homeservers. Other possible solutions:
-	Blocklists
-	Option to disable voip in synapse

Edit: 
Option three: Opt-Out per user is allready implementet in element

**Comment by auscompgeek** [comment]
Note that this would be impossible in encrypted DMs (without blocking e2ee altogether) since the call negotiation would also be encrypted.

**Comment by anoadragon453** [comment]
@auscompgeek is right in that disabling this from the server is impossible in encrypted rooms, which is the default for all private rooms created in Element today.

This may be a solution that is better solved from the client-side, and I'm assuming you are using Element as your client. Today it is possible to disable VoIP in Element globally by adding the following to Element's `config.json`:

```json
    "settingDefaults": {
        "UIFeature.voip": false
    }
```

This will simply disable the VoIP buttons in the app. You may want students to be able to call each other however, and thus this wouldn't work.

I suggest asking in [#element:matrix.org](https://matrix.to/#/#element:matrix.org) or on https://github.com/vector-im/element-web/issues for configuration option that allows disabling VoIP functionality on a per-homeserver basis.

> Opt-Out per user is allready implementet in element

I'm curious which option you mean here? If it's possible to disable VoIP on a per-user basis already, extending that to a per-homeserver basis shouldn't be too difficult.

**Comment by n3rdybyn47ur3** [comment]
Thank you all for the suggestions.

One can find the option to disable Voip per user (opt-out) in element under "All Settings" -> "Voice & Video" -> "Allow Peer-to-Peer for 1:1 calls". But thats for all calls.

**Comment by anoadragon453** [comment]
@n3rdybyn47ur3 Ah I see, I thought you meant disabling it for *other* users on a per-user basis.

I think this is best addressed client-side. Perhaps an option that allows you to enter a whitelist of domains that the user will be able to call. I don't think there's much we can practically do from the Synapse side on this one. As above, I'd recommend asking in [#element:matrix.org](https://matrix.to/#/#element:matrix.org) or on https://github.com/vector-im/element-web/issues for configuration option that allows disabling VoIP functionality on a per-homeserver basis.

**Comment by hadilq** [comment]
I was thinking about this claim of @auscompgeek 

> Note that this would be impossible in encrypted DMs (without blocking e2ee altogether) since the call negotiation would also be encrypted.

but I cannot make sense out of it! Synapse should know where to send the encrypted DMs, right? I mean the DMs are encrypted but the server side must know from which client it comes and to which client it goes, right? If the server side doesn't know it then it's impossible to rout the DMs!

I found this thread because I also had this request to be able to disable the call/video/voIP from the server side, because I think it's not safe, but I cannot prove it!

**Comment by hadilq** [comment]
Thank you @auscompgeek for your reply. So my request is failed because as you mentioned we don't know the "message type" in the server side, however, let me check the following feature request here with you. If it works I'll create a separated issue if it's needed.

Is it possible to maintain a whitelist in the server side to block any type of requests out of this list? I don't want to transmit any DMs with people outside of a list. It can be disabled by default, but whenever a user enabled it, adding a new user to the whitelist may need a DM from the server side, not the other client. In this way nobody can send me messages, or call, or missed calls, without my pre-approval.

**Comment by auscompgeek** [comment]
As I understand there's no difference between an DM and any other kind of room at the protocol level (other than e2ee).
