### ISSUE TITLE
Deprecate and remove the Shutdown Room Admin API in favour of the Delete Room API

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#8663]
The [delete room admin API](https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/rooms.md#delete-room-api) covers all of the functionality of the [shutdown room admin API](https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/shutdown_room.md) and more.

Instead of having two endpoints that do roughly the same thing, we should deprecate the less useful one.

A deprecation warning will need to go out in the changelog, to allow people to update their third-party code before we eventually remove the API altogether.

**Comment by FanchTheSystem** [comment]
Maybe shutdown api should be modified to allow room admin to close a room and redirect to a new room. 
Without the need to be a server admin, only the room admin right should be enough (because you can be the admin of a room which is not on your server).

For example if I have too room about the same subject, and I want to close one, I would want the user in my old room to be notified that it is closed and where the new room is. (like when you upgrade a room)
In this case, the old room will not have to be purged, as you will want to keep the history.

**Comment by anoadragon453** [comment]
@FanchTheSystem that should probably be the decision of the room admin, rather than a server admin? At the moment we use manual room upgrades to redirect users of a room into another - though the process is indeed quite manual and cannot be done with the GUI in any client.

**Comment by FanchTheSystem** [comment]
@anoadragon453 Yes it is my point, instead of removing "Shutdown Room" from server admin api, it should be transferred to normal api for room admin usage ;) (ie use a room admin token for the curl call)

**Comment by anoadragon453** [comment]
@FanchTheSystem I think that should be discussed on a separate issue. This issue is intended to express that the functionality of the shutdown room admin API has been superseded by the delete room admin API, and we should remove the former as it is currently redundant.

An addition for room admins to do something similar is a good idea, but one that would work in a fundamentally different way internally (you'd need to spec a state event that all servers in the room would agree on). That should be done outside of this issue, which is confined to Synapse's admin API.

**Comment by FanchTheSystem** [comment]
@anoadragon453  You're right, I created a feature request fot it ;)
Thank you !

**Comment by dklimpel** [comment]
Related: #8810

**Comment by anoadragon453** [comment]
This has been done in #8829.
