### ISSUE TITLE
Make it possible to customize /.well-known/matrix/client response

### ISSUE THREAD

**Issue by henrikjohansson712** [matrix-org/synapse#8739]
**Description:**

The response from the well-known endpoint is currently limited to the homeserver and identity server base urls. Chat clients like Element require that some settings are served through this endpoint, which is quite hard to do the way it's currently set up. Would it be possible to add a "well-known" section to homeserver.yaml where you can add custom values?

**Comment by erikjohnston** [comment]
That seems reasonable.

**Comment by samiraguiar** [comment]
I have the same need and was thinking about working on it, but I'm unsure about the best approach.

We could specify the values returned by the `/.well-known/matrix/client` endpoint in a section in `homeserver.yaml`, or we could also specify the path to a JSON file containing such values. However, it would be interesting to avoid hardcoding and have scalable support for other endpoints, such as [`/.well-known/matrix/integrations`](https://github.com/matrix-org/matrix-react-sdk/blob/7b882c63939959f71d68a5882012cd5a06d27afb/src/integrations/IntegrationManagers.ts#L221) and others.

What do you think?

**Comment by seth586** [comment]
Add the following excerpt inside your nginx reverse proxy`server{}` block:

```
location /.well-known/matrix/client {
      return 200 '{"m.homeserver": {"base_url": "https://matrix.org"},"m.identity_server": {"base_url": "https://vector.im"}}';
      add_header Content-Type application/json;
      add_header "Access-Control-Allow-Origin" *;
    }
```

**Comment by cysea** [comment]
I was trying to configure my homeserver to serve the same jitsi query for both element desktop and element web, since synapse serves it's own `/.well-known/matrix/client`, and the other `/.well-known/matrix/client` being my custom one served by nginx for federation purposes.

Nginx: https://domain.tld/.well-known/matrix/client
Homeserver: https://matrix.domain.tld/.well-known/matrix/client
Element web: https://chat.domain.tld/

When creating jitsi conferences from element-desktop, they would be redirected to `app.element.io` and use the `jitsi.riot.im` widget, opposed to my self hosted element-web, which respects the nginx version of `/.well-known/matrix/client`

I tried pointing `matrix.domain.tld/.well-known/matrix/client` to `domain.tld/.well-known/matrix/client`, and now even though both links serve the same content, element-desktop is still not respecting which jitsi server to use, nor the custom location of element-web.
I might be doing this wrong, but this bypass doesn't seem to do the job for me.

So for element-web to use my jitsi server, it was as easy as editing the `config.json` file:
```
"jitsi": {
    "preferredDomain": "jitsi.domain.tld"
}
```
And afterwards adding the following to nginx's .well-known.
```
"im.vector.riot.jitsi": {
     "preferredDomain": "jitsi.domain.tld"
}
```
And then when opening a conference in element-web, it goes to:
https://chat.domain.tld/foobar?jitsi.html#conferenceDomain=jitsi.domain.tld...

To fix this we just need a way of editing synapse's `matrix.domain.tld/.well-known/matrix/client` in `homeserver.yml`.

**Comment by manju-rn** [comment]
Any updates on when this feature is expected to be rolled out?  This would make it easy to host synapse without needing a nginx proxy
