### ISSUE TITLE
Synapse returns 200 for PUT to message send but message is not persisted

### ISSUE THREAD

**Issue by jaywink** [matrix-org/synapse#8762]
### Description

There is a Synapse which started returning 200 OK for PUT messages when sending messages but the messages have stopped persisting into the room. Synapse has been restarted since. When sending messages in a fresh session (in Element), the messages get persisted.

> 2020-11-16 08:03:55,336 - synapse.access.http.8008 - 311 - INFO - PUT-9787- 1.2.3.4 - 8008 - {@user:xxxxxxx.ems.host} Processed request: 0.005sec/-0.000sec (0.004sec, 0.000sec) (0.001sec/0.001sec/1) 59B 200 "PUT /_matrix/client/r0/rooms/!BCoxxxxxxx:xxxxxxxxxx.ems.host/send/m.room.message/1164?access_token=<redacted> HTTP/1.1" "Net::Async::Matrix" [0 dbevts]

The client sending the messages is Matrixmon. Have verified the messages do not end up in the `events` table either.

I have the credentials for the account for the problematic session which can be used to reproduce locally.

### Version information

EMS hosted Synapse v1.22.1

**Comment by erikjohnston** [comment]
Our working theory here is that the client was reusing a transaction ID, which would result in a request like that (very fast, only one transaction, etc).

**Comment by michaelkaye** [comment]
We can see from the transaction table that there was a break in sent messages at after 22:15:43 until 22:21:22 ; at which point 8 were sent in the same second; we would expect ~ 10 to be sent in this period if they were all sent 'late'.

That doesn't explain what happened after 22:23 though; at that point no further tokens were inserted into the database table and we continued to get these failed sends for the next 8h or so.

From the matrixmon logs, it looks like every transaction listed in event_txn_id corresponds to a sent message by the system; the ones that are missing don't have any events sent in that time period, so this seems to line up with events being dropped because their transaction ID has already been used.

```
[2020/11/16 08:37:54] Use of uninitialized value $txn_id in hash element at mon.pl line 162.
```

Is somewhat suspicious though.

And a bit of a further look; it seems like matrixmon generates transaction ids by setting txn_id to 1 on launch and incrementing.

So what's actually happened here is that matrixmon started on a host about 1000 messages ago (less than 24h) and then (i believe) restarted having lost it's local txn_id cache. The new database table and filtering means that this matrixmon then started sending txn_id's from 1 again, which caused it all to be dropped.

so GOOD NEWS! synapse isn't dropping messages.

I'm going to file an issue on matrixmon for this.

**Comment by michaelkaye** [comment]
(the matrixmon instance was restarted at 22:21, corresponding to this reset of the transaction ID)
