### ISSUE TITLE
Missing 'origin' field when responding to send_join over federation

### ISSUE THREAD

**Issue by gnieto** [matrix-org/synapse#8786]
### Description

Synapse is not sending `origin` field on federation send join endpoint as defined on spec: https://matrix.org/docs/spec/server_server/r0.1.4#put-matrix-federation-v2-send-join-roomid-eventid

Origin is missing here: https://github.com/matrix-org/synapse/blob/79bfe966e08a2212cc2fae2b00f5efb2c2185543/synapse/handlers/federation.py#L1577

**Comment by richvdh** [comment]
I feel like we should remove it from the spec, rather than add it to synapse, since it's redundant to the Authorization header.

Technically that would be a breaking change in the spec, but if synapse has never sent it I'm inclined to simply consider its presence a bug in the spec.

**Comment by richvdh** [comment]
see: https://github.com/matrix-org/matrix-doc/issues/1664#issuecomment-731153498

**Comment by richvdh** [comment]
Closing this; I consider it a spec bug, not a Synapse one.

**Comment by DMRobertson** [comment]
Recently related: https://github.com/matrix-org/sytest/pull/1293

**Comment by richvdh** [comment]
There seems to have been some broken logic here, though I don't think it changes my conclusions.

> I feel like we should remove it from the spec, rather than add it to synapse, since it's redundant to the Authorization header.

The `Authorization` header is irrelevant here, since that applies to *requests*, and this issue is about *responses*.

But still, `origin` serves no purpose here: we know which server we connected to, and that is the what the spec currently defines the `origin` field to mean:

![image](https://user-images.githubusercontent.com/1389908/195343572-8b0d4453-74c6-413d-bd7e-ef0ec8d5082e.png)
