### ISSUE TITLE
synapse_forward_extremities metric appears to have no rooms in it for periods of time

### ISSUE THREAD

**Issue by benbz** [matrix-org/synapse#8792]
![image](https://user-images.githubusercontent.com/1325121/99870936-a071c500-2bce-11eb-9b90-73664ad16a89.png)

So it appears like Synapse is reporting there are 0 rooms with <= Infinity Forward Extremities. This appears to happen semi-regularly

**Comment by clokep** [comment]
That's a bit odd, is this new behavior or has it been going on for a while?

Note that this value is only updated every 60 minutes (updated by the `read_forward_extremities` background task), so that's why it seems to oscillate between the two values.

**Comment by benbz** [comment]
The graphs I have access to only go back 30 days. I believe I can see this behaviour going on for the whole of that period, but it is difficult to tell

**Comment by anoadragon453** [comment]
Assuming this isn't due to performance or configuration changes, the only way I could see this being possible is if the query for this metric returning zero rows:

https://github.com/matrix-org/synapse/blob/437a99fb99f42e64a0488ffe0a394cbc60921254/synapse/storage/databases/main/metrics.py#L66-L89

Handing `[]` to `_extremities_collecter.update_data` will clear all values.

@benbz is the `synapse_excess_extremity_events` bucket showing similar behaviour btw?

**Comment by benbz** [comment]
`synapse_excess_extremity_events` does seem to exhibit the same behaviour.

One thing I will say is that all the examples I saw in the last 48 hours seem to correspond to a server restart. And metrics only start being non-zero an hour later. I can't confirm/deny whether the historical ones all relate to a server restart

**Comment by anoadragon453** [comment]
Aha! Well that bucket won't be updated until at least 1 hour has passed since the server has started up, so on the next scrape we'd see 0's.

One solution is to just call the function immediately, and then again every 1hr. Looks like we actually do this already for some metrics: https://github.com/matrix-org/synapse/blob/fe0f4a3591302176c7eea48a54f6ed83d9eb4aa9/synapse/app/phone_stats_home.py#L175-L177

**Comment by richvdh** [comment]
> One solution is to just call the function immediately, and then again every 1hr. 

It might be a bit annoying to have to call that relatively expensive query during startup. can we instead just not emit the metric until the query has run?
