### ISSUE TITLE
How to uninstall matrix_synapse using terminal

### ISSUE THREAD

**Issue by luffybhaagi** [matrix-org/synapse#8840]
I have installed matrix_synapse looking at below link:
https://www.digitalocean.com/community/tutorials/how-to-install-matrix-synapse-on-ubuntu-16-04.

I have gone no where in installing matrix_synapse and throwing installation errors due to imperfect installations from my side. Can anyone help unistall and 
[homeserver.log](https://github.com/matrix-org/synapse/files/5611685/homeserver.log)
installing synapse server in ubuntu 20.14 version ?.

**Comment by anoadragon453** [comment]
Hello. It looks like you enabled ACME in Synapse without installing the [relevant python dependencies](https://github.com/matrix-org/synapse/blob/856eab606b17bcd78549ff12e9d41a62d441af07/synapse/python_dependencies.py#L96-L101).

However, note that [ACMEv1 has been deprecated](https://github.com/matrix-org/synapse/blob/develop/docs/ACME.md#deprecation-of-acme-v1) for new domains since June 2020, and Synapse doesn't yet support ACMEv2 (waiting on upstream), so ACME probably won't be very useful to you at this point :slightly_frowning_face: 

ACME support *should* be working again in the future, but for now, please request your own certificates.

Additionally, note that support requests like this one are best asked in [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org), using a free matrix.org account if necessary.

Thanks!
