### ISSUE TITLE
Add different database support

### ISSUE THREAD

**Issue by jjabinx** [matrix-org/synapse#8852]
Hi everyone! I'm not very experienced in opening Issues on github so I apologize if something's not the way I'm supposed to write it.

I'm working with Synapse (and Element in the Forntend) and I've noticed the only options for a database are SQLite (for development only) and PostgreSQL.
I have some time of experience with SQLServer and Oracle administration, and already have an existing SQLServer locally, and would like to be able to place my database on it as well to centralize all my data.

Is this something that's planned or in progress, or will Synapse stay on PostgreSQL support only for the foreseeable future?

Thanks!

**Comment by anoadragon453** [comment]
Hello! Your issue is written fine :slightly_smiling_face: 

At the moment we indeed plan to stick with SQLite and Postgres for the foreseeable (with Postgres being the much more performant option). We're unlikely to add another database engine into the mix due to the incredible amount of maintenance burden each engine needs to properly support.

SQLite is useful as it requires zero setup to get going, whereas Postgres is primarily for production usecases.

See https://github.com/matrix-org/synapse/issues/2112 for a similar question and the resulting discussion.
