### ISSUE TITLE
Username change/Account transfer

### ISSUE THREAD

**Issue by 35609902357** [matrix-org/synapse#9064]
The possibility of changing username or transferring the account would be a great convenience to have. For example if someone wants to change the username for some reason, the only possible way would be to create another account, add all rooms and contacts and lose all chats in the process. Simply changing the username would be the best, if it can't be done for technical reasons, then a feature to transfer all contacts, chats and backed up keys would be a good solution too.

**Comment by SimonBrandner** [comment]
@35609902357 You can try to migrate using [this](https://ems.element.io/tools/matrix-migration), but be cautious

**Comment by clokep** [comment]
I don't think this is currently possible with the current matrix spec since matrix IDs are embedded into events (see matrix-org/matrix-doc#1228. There's some other links in there about decentralized user accounts which could be used to migrate an account between homeservers, but I don't see any reason it couldn't be used on the same homeserver, but different accounts.

I'm going to close this since this isn't a synapse issue at the moment, but a broader spec issue.

**Comment by 35609902357** [comment]
@clokep This issue was open as a feature request, since the feature is not yet implemented why close it? This feature is offered by all the major messaging platforms already. There's no point sweeping the dust under the carpet.

**Comment by clokep** [comment]
@35609902357 The discussion around this feature is taking place at the specification level, this needs to be done first so the various homeserver and client implementations can agree on how this can be implemented.

**Comment by rokejulianlockhart** [comment]
https://github.com/matrix-org/matrix-spec-proposals/pull/1228

**Comment by clokep** [comment]
> @clokep, where can I follow it?

matrix-org/matrix-spec-proposals#2787 should be a reasonable jumping off point.
