### ISSUE TITLE
SSO: allow white listing clients to bypass the SSO confirmation step

### ISSUE THREAD

**Issue by pini-gh** [matrix-org/synapse#9160]
Hi,

I've set up a self hosted configuration with a Synapse and an Element-web instances on the same domain. The Synapse instance is locked to accounts registered on our domain, and the Element-web instance defaults to our own Synapse home server.

Authentication uses our SSO (OIDC via LemonLDAP::ng). everything works like a charm, but there is this annoying SSO configuration step keeping asking us:
> The application at element.example.com is requesting full access to your example.com Matrix account.
> If you don't recognise this address, you should ignore this and close this tab.

Since we manage both instances, a white list option to allow bypassing this confirmation step would be appreciated.

Thanks in advance for considering.

**Comment by clokep** [comment]
I believe this should be covered by the `sso.client_whitelist` setting:

https://github.com/matrix-org/synapse/blob/ebd534b58d9d53dc5086a9dd9cb176868c7b93ef/docs/sample_config.yaml#L1886-L1904

I'm going to close this (since we already support this!), but please shout if that doesn't solve your issue and let us know what's going on!

**Comment by pini-gh** [comment]
Oops I missed that! Thanks!
