### ISSUE TITLE
Add a new `/versions` flag to configure megolm outbound keys pre-sharing

### ISSUE THREAD

**Issue by giomfo** [matrix-org/synapse#9178]
To speedup sending a message in an encrypted rooms, we are considering the possibility to pre-share megolm outbound keys when opening a room. So when typing/sending a message (in most cases) outbound keys are already shared and setup.
Note: element-web does it already when you start typing.

This change may entail some side effects (like network congestion when a high number of members will open the room), so we consider we should be able to notify the clients about the best mode of pre-sharing to apply. So we suggest introducing a new `_matrix/client/versions` flag: `io.element.e2ee_outbound_keys_pre_sharing`

We would consider 3 values:
- disabled
- on_typing
- on_room_opening

**Comment by manuroe** [comment]
@bmarty suggested the following instead of hacking `_matrix/client/versions` for defining Element apps behavior that other matrix clients will probably not follow. 
The following makes a clear separation between homeserver capabilities expressed in  `/versions` and very specific application settings, that must be defined "elsewhere" if we want dynamic behavior.
 
We already have needs for element mobile apps to have a place where they can retrieve dynamic information. 
The first need is the latest version available in the stores so that we can suggest users to upgrade. This is filed at https://github.com/vector-im/element-android/issues/2180.
We can use this config file to define properties like the one proposed in this issue, `e2ee_outbound_keys_pre_sharing`. This is very similar with what element-web does with its [config.json](https://app.element.io/config.json).

One instance/fork of element uses its own config.json to determine its behavior. 

If you are ok with this approach, we just need the path of this file for ios, android google play version and fdroid.

The default behavior will be `on_typing` to match current element-web behavior.

**Comment by manuroe** [comment]
I would advise `on_typing` as default behavior because:
- this is what element web currently does
- it creates less to_device events traffic than `on_room_opening` and the improvement should be noticeable in terms of UX.

**Comment by clokep** [comment]
Using something like config.json seems like a better approach since this doesn't really involved the homeserver.

I think we can close this based on our previous conversation?
