### ISSUE TITLE
room_stats_historical and user_stats_historical appear unused

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#9602]
We have a whole lot of code which maintains the `room_stats_historical` and `user_stats_historical` tables (and a config option, `bucket_size`, which configures how it is populated), but afaict they are never actually used.

It's not obvious to me what the purpose of these tables are for, and I'd argue that unless we have a clear usecase for them, the tables and dead code should be stripped out.

It looks like the concept of historical stats was introduced by @ara4n in the initial commits in #4338, though it subsequently got refactored out of recognition by #5971. @ara4n: any comments on the purpose of this, and/or objections to it being ripped out.

Also of interest (and would need updating) is the doc, https://github.com/matrix-org/synapse/blob/v1.29.0/docs/room_and_user_statistics.md.

**Comment by richvdh** [comment]
another point on this: according to the doc, it was originally envisaged that we would expire old entries from the `historical` tables. That code has never been written, and meanwhile this data is taking up lots of space on peoples' databases.

**Comment by anoadragon453** [comment]
I thought during #6739 that we actually did use this table as we make a select from it here:

https://github.com/matrix-org/synapse/blob/44ce919c706fba46899dc496ab0ef244ac648bd7/synapse/storage/databases/main/stats.py#L328-L337

but it turns out that function is only called from the tests. So indeed, we don't seem to use this table in practice (though there are a few tests that mandate it be kept up to date currently).
