### ISSUE TITLE
Consider to include a Dockerfile

### ISSUE THREAD

**Issue by silvio** [matrix-org/synapse#969]
Currently I maintain http://github.com/silvio/docker-matrix. I think it would be a great idea to include this approach to the official synapse sources.

The surplus would be that every release of matrix gets an official docker release. Bug fixes and Security fixes could be released very early.

The user can pull a specific releases via `docker pull matrix-org/docker-matrix:v3.4` or the latest version via `docker pull matrix-org/docker-matrix:latest`.

The current docker file needs changes for this.

**Comment by almereyda** [comment]
I can only support a vote for official Docker images of the Matrix ecosystem, especially since services can be quickly spun up with that infrastructure.

Yet as the Docker ecosystem is moving fast and breaking often, the recent moves on `compose` and `swarm` ask for catching up and splitting a server into a combination of individual services. The links in #378 show an approach which forked of the excellent preliminary work of @silvio:

* https://github.com/allmende/docker-matrix/blob/master/docker-compose.yml
* https://hub.docker.com/u/allmende/dashboard/

I was using a two step set up procedure involving `docker-compose -f generate.yml up` ([generate.yml](https://github.com/allmende/docker-matrix/blob/master/generate.yml)) as a one off command preparing the configs, and only then starting the deamons via `docker-compose up -d`. Unfortunately this is not yet documented in the docker-matrix README.

The source repositories for the individual images live at:

* https://lab.allmende.io/allmende/docker-vector/tree/master
* https://lab.allmende.io/allmende/docker-synapse/tree/master
* https://lab.allmende.io/allmende/docker-coturn/tree/master

I was always thinking I had something to hide, why they are not on GitHub (yet) as the configurations used include already public facts of the actual allmende.io deployment and are not generalised.

I am especially not fond of https://lab.allmende.io/allmende/docker-vector/blob/master/Dockerfile#L72-73, but believe the new [ARG keyword](https://docs.docker.com/engine/reference/builder/#/arg) may come in handy here.

Please have a look, fork off and see if we can build something together out of our different branches.

**Comment by fuzzy76** [comment]
Any more thoughts on this? FWIW, docker best practices revolve around 1 process per container, so I agree that one service per container makes more sense. It also allows me to choose myself which services I want.

**Comment by ara4n** [comment]
I absolutely agree that we need an official Dockerfile.  @superdump perhaps you can add this at medium-prio to your hit list?

**Comment by almereyda** [comment]
Best known preliminary work from @silvio above is in:

* https://github.com/silvio/docker-matrix and now also
* https://github.com/silvio/matrix-riot-docker

or moved to GitHub

* https://github.com/allmende/docker-matrix
  * https://github.com/allmende/docker-synapse
  * https://github.com/allmende/docker-vector
  * https://github.com/allmende/docker-coturn

while I am still unsure about how to run the integrations service and the 3PID sydent service for my own environment.
Other approaches live in

* https://github.com/cloudfleet/docker-matrix (forked from allmende/docker-matrix and concluded with LDAP)
* https://github.com/jcgruenhage/docker-synapse
* https://github.com/ptman/synapse-docker
* https://github.com/ilianaw/dockerfiles/tree/master/synapse

**Comment by fuzzy76** [comment]
...which is the problem. I have no idea which to pick, and don't want to get stuck with something that's abandoned when synapse get an official setup.

**Comment by ptman** [comment]
https://github.com/matrix-org/synapse/pull/2482

**Comment by ptman** [comment]
@fuzzy76 It should be quite easy to move from dropped image to official, when that day comes. Data lives in database (and media_store/). Config needs to be rescued.

**Comment by richvdh** [comment]
now finally fixed by https://github.com/matrix-org/synapse/pull/2846
