### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by f1-outsourcing** [matrix-org/synapse#9839]
If you want to build on something else like alpine, it seems you have to copy lots of files from github. Can't these be included in pip packages or so?

In the old Dockerfile I think you had the pip install matrix-[xxx] packages are these still being updated?

I assume this 
`COPY synapse /synapse/synapse/`
copies the whole synapse dir from github not? Why is this? Why is this not a package?

If you keep the docker file more like the install manual[1], it also prevents having different bugs being reported from docker images and python packages. I think it is better to distribute the packages and work everywhere with the packages.

[1]
 https://github.com/matrix-org/synapse/blob/develop/INSTALL.md

**Comment by anoadragon453** [comment]
Our [packages on PyPI](https://pypi.org/project/matrix-synapse/) are indeed still updated. The reason we don't simply just install from PyPI in the Dockerfile is so that building the Docker image will use the currently checked-out source code, rather than simply pulling the latest Synapse release. This can be useful if you need to build a Synapse docker image from the current branch, like we do when testing PR branches using [Complement](https://github.com/matrix-org/complement).

If you would like to build a Synapse Dockerfile based on Alpine which installs Synapse via the latest release on PyPI, then that should work fine. We certainly could have two Dockerfiles in our repo - one that compiles an image from the checked out source, and another that pulls from PyPI (or even just a build argument to toggle between the two). But so far I don't think we've seen much evidence of bugs appearing in the Docker image as a result of compiling from the repo instead of PyPI.

The contents of the PyPI packages are just a packaged form of the repo anyways?

**Comment by richvdh** [comment]
I don't think we're planning to make any changes in this area, so I'm going to go ahead and close this issue.
