### ISSUE TITLE
Docker version tags removed from Docker Hub

### ISSUE THREAD

**Issue by mserajnik** [matrix-org/synapse#9860]
Is there a reason why the Docker image tags for both releases `v1.32.0` and `v1.32.1` on Docker Hub first got added and then removed again?

I had a an automated backup script script fail twice now because those tags suddenly didn't exist anymore when I tried to pull them.

**Comment by anoadragon453** [comment]
Hey @mserajnik, sorry for the inconvenience. We ended up needing to retract both the 1.32.0 and 1.32.1 releases due to serious regressions that snuck in at the last minute. Part of this retraction was pulling the docker images, and repointing `latest` back to 1.30.1. Details on the issues are in [the changelog](https://github.com/matrix-org/synapse/blob/develop/CHANGES.md).

The rationale was to protect deployments in the wild from upgrading and potentially breaking their Prometheus instances, though we understood that doing so could cause disruption. We're looking to improve our process when situations like this occur (especially lowering the chance of similar regressions happening again), and will be evaluating the decision to pull docker releases as part of that.

We're completely open to feedback though. Was there something that we could have done better here that would have been less disruptive with regards to your infrastructure?

**Comment by clokep** [comment]
> Was there something that we could have done better here that would have been less disruptive with regards to your infrastructure?

I think the discussion we had internally is that we should have left the tags there, but pointed latest to v1.31.0? This would mean that no one would auto-upgrade, but people explicitly targeting those versions would get them?

**Comment by mserajnik** [comment]
Thanks for the clarification.

> Was there something that we could have done better here that would have been less disruptive with regards to your infrastructure?

My main problem was that I didn't find any information about the images getting pulled (and the releases were still available here on GitHub, so that made it more confusing) and that I didn't know if I could've just downgraded my installation to `1.31.0` (after using both `1.32.0` and `1.32.1`) or if that could've causes issues because of any potential `1.32.0`/`1.32.1` database migrations.

I'll close this issue as it's been cleared up. Thank you!
