### ISSUE TITLE
Investigate regression in matrix.org's send PDU lag.

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#9863]
After deploying develop the federation send PDU metrics show a sharp increase in lag on senders 2 and 3 (but not 1 and 4):

![Screenshot from 2021-04-22 10-33-04](https://user-images.githubusercontent.com/8428120/115699730-d5409e80-a35d-11eb-8874-c5a3d40c096c.png)

While 4 sees a sharp decline in the counts:

![Screenshot from 2021-04-22 11-28-42](https://user-images.githubusercontent.com/8428120/115699830-f3a69a00-a35d-11eb-81e0-1f46ccfd77a3.png)

One potentially related PR that was deployed at the time is https://github.com/matrix-org/synapse/pull/9702.

The CPU, memory usage and DB scheduling time of all federation senders look healthy and with no change.

**Comment by anoadragon453** [comment]
We deployed matrix-org-hotfixes @ 9979fef4fef1220515c4d1916c70cd461984f035 (develop @ fe604a022a7142157da7e90a40330beb2a11af7a merged in with #9702 reverted) to matrix.org on April 27th 17:55 UK to see whether federation performance would improve, as we were seeing federation slowdowns.

After the deploy, federation lag spikes did not really go away (this may just be attributed to an increase in traffic), the overall speed of outgoing PDUs trended dramatically closer towards the 25-50ms bucket:

![image](https://user-images.githubusercontent.com/1342360/116387473-c13fe580-a812-11eb-8500-4039629d973b.png)

The amount of EDU/PDUs we were sending out did not seem to change too much across deploys:

![image](https://user-images.githubusercontent.com/1342360/116387633-e59bc200-a812-11eb-9315-e207fdf0d8e9.png)

And neither did the rate of transactions:

![image](https://user-images.githubusercontent.com/1342360/116387696-f5b3a180-a812-11eb-8403-20da97418b0a.png)

We're backing out the change for v1.33.0rc1 due to the delay it looks to introduce to sending events over federation. Hopefully the data above can help in diagnosing what part of #9702 caused the slowdown.

**Comment by ShadowJonathan** [comment]
@anoadragon453 @erikjohnston can you confirm, with the current view of that very first graph, that after the regression, the problem has been fixed?

And for that matter, what're the relevant metrics involved in the first two graphs? `synapse_event_processing_lag_by_event`?

**Comment by anoadragon453** [comment]
> can you confirm - with the current view of that very first graph - that after the revert, the problem has been fixed?

Here's the current view of the graph. The extreme spikes are at April 26th 15:00 and 20:00 UK, and look to have been caused by a large ramp up of outgoing EDUs at each point in time.

![image](https://user-images.githubusercontent.com/1342360/116534830-f1eb5200-a8da-11eb-9900-b478d8c6cc86.png)

Yep! The source for the graphs are in the [Synapse grafana dashboard](https://github.com/matrix-org/synapse/tree/develop/contrib/grafana). But the metrics for each graph are:

* Federation Send PDU lag quantiles: `histogram_quantile(0.99, sum(rate(synapse_event_processing_lag_by_event_bucket{name='federation_sender',index=~"$index",instance="$instance"}[$bucket_size])) by (le))`
* Federation Send PDU lag: `sum(rate(synapse_event_processing_lag_by_event_bucket{instance="$instance",name="federation_sender"}[$bucket_size])) by (le)`

**Comment by ShadowJonathan** [comment]
Could you maybe give me some metrics that regard `event_processing_loop_room_count`?

**Comment by callahad** [comment]
> i think re-adding the parallelization to the PR could fix the metrics.

We're happy to take another shot at this with that re-added

**Comment by ShadowJonathan** [comment]
> > i think re-adding the parallelization to the PR could fix the metrics.
> 
> We're happy to take another shot at this with that re-added

I wouldn't wanna take it blindly, so @anoadragon453, if you have time, could you give me some information on the `event_processing_loop_room_count` counter? With the average of rooms processed per federation_sender.

**Comment by anoadragon453** [comment]
@ShadowJonathan Does this give you what you need?

![image](https://user-images.githubusercontent.com/1342360/116555808-b3629100-a8f4-11eb-8528-f19a44b4bcdd.png)

`rate(synapse_event_processing_loop_room_count{name="federation_sender",instance="$instance",index=~"$index"}[$bucket_size])`

**Comment by ShadowJonathan** [comment]
Yes, thank you, and judging from that graph, I can see how the problem is exacerbated; previously, the processing coroutines would queue up somewhat around 40 concurrent database queries (for prev_events and whatnot), now it happens serially.

**Comment by ShadowJonathan** [comment]
I've submitted a fix in #9908, lets see how this one turns out.

**Comment by erikjohnston** [comment]
I'm going to close this as we backed out the original patch.
