### ISSUE TITLE
SynapseError: 401 - Invalid macaroon passed

### ISSUE THREAD

**Issue by Sr-Preet** [matrix-org/synapse#9901]
I'm getting this Invalid Macaroon Passed error along with, Unauthorized Error, while trying to add the threepid.
Can anyone please help me.

**Comment by babolivier** [comment]
This issue sounds like there is an issue with your access token, which doesn't necessarily mean a Synapse bug. Since this issue tracker isn't the best place for support, please ask in [`#synapse:matrix.org`](https://matrix.to/#/#synapse:matrix.org) or open a thread in the [discussions tab](https://github.com/matrix-org/synapse/discussions).
