### ISSUE TITLE
Appservices cannot create rooms with a large invite list

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#9952]
I thought this was fixed in #9663 but it's still a bug as of v1.33.0. Trying to create a room while inviting 7 users caused the homeserver to respond with `{ errcode: 'M_UNKNOWN', error: 'Cannot invite so many users at once' }`

**Comment by babolivier** [comment]
The issue seems to come from this code within the `create_room` function:

https://github.com/matrix-org/synapse/blob/4b965c862dc66c0da5d3240add70e9b5f0aa720b/synapse/handlers/room.py#L679-L680

It looks like this is because this code isn't using the `RateLimiter` class, probably due to the fact that we don't want to check if the user can invite just one user but potentially many of them. So either we should add this kind of capability to the `RateLimiter` and use it there, or tweak this code path to look up overrides from the database and appservice configs, which sounds like more faff to me.
